'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {LessonPackage} from '@/lib/packages/types';
import WhatsAppIcon from '@/components/site/whatsapp-icon';
type Slot={id:string;starts_at:string;ends_at:string;mode:string};
type Data={students:{id:string;name:string}[];studentId:string;packages:LessonPackage[];ready:boolean;live:boolean;preview:boolean;warning?:string};
const date=(s:string)=>new Intl.DateTimeFormat('it-IT',{dateStyle:'full',timeZone:'Europe/Rome'}).format(new Date(s));
const time=(s:string)=>new Intl.DateTimeFormat('it-IT',{timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(s));
export default function PurchaseView(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[slots,setSlots]=useState<Slot[]|null>(null),[booking,setBooking]=useState(''),[selected,setSelected]=useState(''),[subject,setSubject]=useState('Matematica'),[day,setDay]=useState(''),[message,setMessage]=useState('');
 const purchaseAttempt=useRef<{id:string;studentId:string;units:1|5}|null>(null),bookingAttempt=useRef<{id:string;packageId:string;slotId:string;subject:string}|null>(null);
 const refresh=useCallback(async(studentId?:string)=>{const params=new URLSearchParams(window.location.search);if(studentId){if(params.get('studente')&&params.get('studente')!==studentId)params.delete('acquisto');params.set('studente',studentId);}const r=await fetch('/api/acquisti?'+params,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);return d as Data;},[]);
 useEffect(()=>{let active=true;refresh().then(d=>{if(!active)return;const id=new URLSearchParams(window.location.search).get('acquisto'),p=d.packages.find(p=>p.id===id&&p.status==='active'&&p.remaining>0&&(p.payment_method!=='online'||!!p.live_mode===d.live));if(p){setMessage('Pagamento confermato. Ora puoi scegliere gli appuntamenti, oppure prenotare più avanti.');void loadSlots(p.id);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[refresh]);
 async function buy(units:1|5){if(!data)return;setBusy(true);setError('');try{let a=purchaseAttempt.current;if(!a||a.units!==units||a.studentId!==data.studentId)a=purchaseAttempt.current={id:crypto.randomUUID(),studentId:data.studentId,units};const r=await fetch('/api/acquisti',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(a)}),d=await r.json();if(!r.ok)throw Error(d.error);if(!d.url?.startsWith('https://checkout.stripe.com/'))throw Error('Pagamento non disponibile.');window.location.assign(d.url);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function loadSlots(packageId:string){setBooking(packageId);setSelected('');setSlots(null);setError('');try{const r=await fetch('/api/acquisti/prenota',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setSlots(d.slots);setDay(d.slots[0]?date(d.slots[0].starts_at):'');}catch(e){setError((e as Error).message);}}
 async function reserve(){if(!data||!selected)return;setBusy(true);setError('');try{let a=bookingAttempt.current;if(!a||a.packageId!==booking||a.slotId!==selected||a.subject!==subject)a=bookingAttempt.current={id:crypto.randomUUID(),packageId:booking,slotId:selected,subject};const r=await fetch('/api/acquisti/prenota',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...a,studentId:data.studentId})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Lezione prenotata. La trovi nell’area studente, in Lezioni e saldi.');bookingAttempt.current=null;await refresh(data.studentId);await loadSlots(booking);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="purchase-workspace public-spaced">{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!data?<p role="status">Caricamento dei tuoi acquisti…</p>:<>{data.warning&&<p role="alert">{data.warning}</p>}<label>Studente<select value={data.studentId} disabled={busy} onChange={async e=>{setBooking('');setSlots(null);setMessage('');setError('');try{await refresh(e.target.value);}catch(e){setError((e as Error).message);}}}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
 {!data.ready?<p className="reading-callout">Il pagamento online è in preparazione. Per acquistare puoi concordare contanti o POS con Francesco.</p>:!data.live&&<p className="reading-callout">Modalità prova: non vengono addebitati soldi reali.</p>}
 <div className="public-card-grid public-spaced"><article className="public-panel"><h2>Una lezione</h2><p className="catalog-price">20 € <small>55 minuti · individuale</small></p><button className="button dark" disabled={busy||!data.ready||!!data.warning} onClick={()=>buy(1)}>Acquista una lezione</button></article><article className="public-panel"><h2>5 lezioni</h2><p className="catalog-price">95 € <small>19 € per incontro · 55 minuti ciascuno</small></p><button className="button dark" disabled={busy||!data.ready||!!data.warning} onClick={()=>buy(5)}>Acquista 5 lezioni</button></article></div>
 <section className="public-spaced"><h2>Le tue lezioni acquistate</h2><button className="button outline" disabled={busy} onClick={()=>refresh(data.studentId).catch(e=>setError(e.message))}>Verifica pagamento</button>{data.packages.length===0&&<p>Non ci sono ancora lezioni acquistate per questo studente.</p>}{data.packages.map(p=><article key={p.id} className="registry-card"><h3>{p.units===1?'Lezione individuale':`${p.units} lezioni individuali`} · {(p.amount/100).toLocaleString('it-IT')} €</h3>{p.status==='active'&&(p.payment_method!=='online'||!!p.live_mode===data.live)?<><p>{p.remaining} lezioni ancora da prenotare.</p>{p.remaining>0&&<button className="button dark" disabled={busy} onClick={()=>loadSlots(p.id)}>Scegli gli orari · consigliato</button>}</>:<><p>{p.payment_method==='online'&&!!p.live_mode!==data.live?'Acquisto di un altro ambiente Stripe: contatta Francesco per la verifica.':p.status==='awaiting'?'Pagamento da completare o verificare.':'Acquisto chiuso: contatta Francesco per il saldo.'}</p>{p.status==='awaiting'&&p.payment_method==='online'&&!!p.live_mode===data.live&&data.ready&&<button className="button outline" disabled={busy||!!data.warning} onClick={()=>{purchaseAttempt.current={id:p.id,units:p.units===5?5:1,studentId:data.studentId};buy(p.units===5?5:1);}}>Riprendi pagamento</button>}</>}</article>)}</section>
 {booking&&<section className="public-panel public-spaced"><h2>Prenota dalle lezioni acquistate</h2><p>Scegli un giorno, l’orario e la materia. Puoi fissare gli altri incontri più avanti.</p><label>Materia<select value={subject} disabled={busy} onChange={e=>setSubject(e.target.value)}>{['Matematica','Informatica','Sistemi e Reti'].map(s=><option key={s}>{s}</option>)}</select></label>{slots===null?<p role="status">Caricamento orari…</p>:slots.length===0?<p>Non ci sono orari aperti per le lezioni a pagamento. Le lezioni acquistate restano disponibili: <a className="whatsapp-link" href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>concorda un orario con Francesco</a>.</p>:<><div className="purchase-days" role="group" aria-label="Giorno della lezione">{[...new Set(slots.map(s=>date(s.starts_at)))].map(d=><button key={d} className="button outline" disabled={busy} aria-pressed={day===d} onClick={()=>{setDay(d);setSelected('');}}>{d}</button>)}</div><fieldset><legend>Orari · {day}</legend><div className="purchase-slots">{slots.filter(s=>date(s.starts_at)===day).map(s=><label key={s.id}><input type="radio" name="paid-slot" checked={selected===s.id} disabled={busy} onChange={()=>setSelected(s.id)}/><span><strong>{time(s.starts_at)}–{time(s.ends_at)}</strong><small>{s.mode==='Lodi'?'In presenza a Lodi':'Online'}</small></span></label>)}</div></fieldset><div className="actions"><button className="button dark" disabled={busy||!selected||!data.packages.some(p=>p.id===booking&&p.status==='active'&&p.remaining>0)} onClick={reserve}>{busy?'Attendi…':'Conferma la lezione'}</button><a className="button outline" href="/studente?vista=pacchetti">Prenoto più avanti</a></div></>}</section>}</>}
 </section>;
}
