import {publicPageMetadata} from '@/lib/site-seo';
import {MessagesSquare,PenLine,NotebookPen} from 'lucide-react';

export function generateMetadata(){return publicPageMetadata('/metodo');}
export default function Page(){return <main className="wrap subject-page">
  <section className="subject-intro"><h1>Come si svolgono le lezioni</h1><p>Per organizzare le lezioni mi baso sul programma che stai seguendo a scuola o all’università e sugli esercizi che devi saper svolgere. Guardare un tuo tentativo, anche incompleto, mi aiuta a capire se bisogna riprendere la teoria oppure lavorare su un passaggio specifico.</p><p className="reading-emphasis">Durante la spiegazione puoi farmi domande e chiedere di tornare su un passaggio. Non serve aspettare la fine della lezione se qualcosa non è chiaro.</p></section>
  <ol className="lesson-timeline">
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><MessagesSquare size={22}/></span><span className="subject-audience">01 · Il primo incontro</span><h2>Guardiamo il programma</h2></div><div className="timeline-body"><p>Nel primo incontro gratuito parliamo delle difficoltà che stai incontrando e del tempo che manca alla prova. Dopo aver guardato il programma possiamo accordarci sugli argomenti da riprendere e su un primo numero di lezioni.</p><details suppressHydrationWarning className="reading-disclosure"><summary>Se vuoi, puoi fare anche un test gratuito</summary><p>È facoltativo e controlla alcuni concetti di base, senza valutare tutto il programma.</p><a className="text-link" href="/?richiesta=test">Fai il test gratuito</a></details></div></li>
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><PenLine size={22}/></span><span className="subject-audience">02 · Durante la lezione</span><h2>Spiegazioni ed esercizi</h2></div><div className="timeline-body"><p>Alterniamo la spiegazione al lavoro sugli esercizi. Ti mostro come affrontare un problema o leggere il codice, poi ti lascio provare e guardiamo insieme il risultato. Gli errori e i dubbi che emergono ci aiutano a scegliere cosa riprendere nella lezione successiva.</p><div className="reading-callout"><h3>Per i ragazzi con DSA</h3><p>Con i ragazzi con DSA parto dalle abitudini di studio e dagli strumenti che usano già. Nel primo incontro possiamo parlare di schemi e tempi di lavoro, per capire come affrontare gli esercizi e quali passaggi richiedono più attenzione.</p></div></div></li>
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><NotebookPen size={22}/></span><span className="subject-audience">03 · Tra gli incontri</span><h2>Ritrovi il lavoro e le correzioni</h2></div><div className="timeline-body"><p>Se vogliamo aggiungere del lavoro da svolgere tra gli incontri, ci accordiamo sugli esercizi e sulle correzioni che seguirò. Nell’area studente puoi ritrovare i materiali assegnati, consegnare quello che hai fatto e rileggere i miei commenti prima della lezione successiva.</p><a className="button outline" href="/piattaforma">Prova un esempio dell’area studente</a><p className="reading-note">Non è un servizio illimitato di correzione o assistenza. Per un dubbio breve puoi scrivermi; gli argomenti da riprendere insieme li affrontiamo a lezione. Accessi e contenuti li assegno personalmente.</p></div></li>
  </ol>
  <details suppressHydrationWarning className="public-disclosure"><summary>Come uso l’IA per matematica e informatica</summary><p>L’IA può servire per confrontare una spiegazione, controllare un ragionamento o capire un errore nel codice. Una risposta può sembrare convincente anche quando contiene un errore, quindi il risultato va sempre verificato.</p><p>Durante lo studio ti chiedo comunque di svolgere gli esercizi e spiegare i passaggi. Confrontare la soluzione con il tuo tentativo può far emergere un passaggio da riprendere, mentre copiarla senza saperla spiegare non ci permette di capire cosa hai imparato.</p></details>
  <div className="actions"><a className="button dark" href="/incontro">Prenota i 15 minuti gratuiti</a><a className="button outline" href="/domande">Informazioni per studenti e genitori</a></div>
</main>;}
