import {publicPageMetadata} from '@/lib/site-seo';
import {MessagesSquare,PenLine,NotebookPen} from 'lucide-react';

export function generateMetadata(){return publicPageMetadata('/metodo');}
export default function Page(){return <main className="wrap subject-page">
  <section className="subject-intro"><h1>Partiamo da quello che non ti torna</h1><p>Un esercizio, un passaggio della spiegazione o del codice che non funziona. Mi mostri cosa hai provato e lo riprendiamo insieme.</p><p className="reading-emphasis">Puoi interrompermi e chiedere di rispiegare: preferisco fermarmi su un dubbio che lasciarlo lì.</p></section>
  <ol className="lesson-timeline">
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><MessagesSquare size={22}/></span><span className="subject-audience">01 · Il primo incontro</span><h2>Guardiamo il programma</h2></div><div className="timeline-body"><p>Nel primo incontro gratuito guardiamo le difficoltà e la data della prova. Decidiamo da dove partire e quante lezioni prevedere.</p><details suppressHydrationWarning className="reading-disclosure"><summary>Se vuoi, puoi fare anche un test gratuito</summary><p>È facoltativo e controlla alcuni concetti di base, senza valutare tutto il programma.</p><a className="text-link" href="/?richiesta=test">Fai il test gratuito</a></details></div></li>
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><PenLine size={22}/></span><span className="subject-audience">02 · Durante la lezione</span><h2>Ti mostro. Poi provi tu.</h2></div><div className="timeline-body"><p>Ti mostro i passaggi di un esercizio o del codice. Poi provi tu, fermandoci dove hai dubbi. Correggiamo il lavoro e decidiamo quali argomenti riprendere nell’incontro successivo.</p><div className="reading-callout"><h3>Per i ragazzi con DSA</h3><p>Possiamo usare schemi, riprendere i passaggi e dedicare più tempo agli esercizi che lo richiedono. Ne parliamo nel primo incontro, partendo da come sei abituato a studiare.</p></div></div></li>
    <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><NotebookPen size={22}/></span><span className="subject-audience">03 · Tra gli incontri</span><h2>Ritrovi il lavoro e le correzioni</h2></div><div className="timeline-body"><p>Ho costruito un’area studente dove trovi materiali, esercizi e correzioni. Se vuoi lavorare anche da casa, concordiamo quali esercizi fare e quali correggere. Puoi consegnare il lavoro e rileggere i miei commenti.</p><a className="button outline" href="/piattaforma">Prova un esempio dell’area studente</a><p className="reading-note">Non è un servizio illimitato di correzione o assistenza. Per un dubbio breve puoi scrivermi; gli argomenti da riprendere insieme li affrontiamo a lezione. Accessi e contenuti li assegno personalmente.</p></div></li>
  </ol>
  <details suppressHydrationWarning className="public-disclosure"><summary>Come uso l’IA per matematica e informatica</summary><p>L’IA può servire per confrontare una spiegazione, controllare un ragionamento o capire un errore nel codice. Il risultato va verificato: anche una risposta scritta bene può essere sbagliata.</p><p>Durante lo studio ti chiedo comunque di svolgere gli esercizi e spiegare i passaggi. Copiare una soluzione non ci dice se hai capito; confrontarla con il tuo tentativo può invece aiutarci a trovare il punto da riprendere.</p></details>
  <div className="actions"><a className="button dark" href="/incontro">Prenota i 15 minuti gratuiti</a><a className="button outline" href="/domande">Informazioni per studenti e genitori</a></div>
</main>;}
