import {publicPageMetadata} from '@/lib/site-seo';
import {MessagesSquare,PenLine,NotebookPen} from 'lucide-react';
export function generateMetadata(){return publicPageMetadata('/metodo');}
export default function Page(){return <main className="wrap subject-page">
 <section className="subject-intro"><h1>Come si svolgono le lezioni</h1><p>Partiamo dal tuo programma e dagli esercizi che ti danno difficoltà. Puoi interrompermi e chiedere di riprendere un passaggio quando vuoi.</p></section>
 <ol className="lesson-timeline">
  <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><MessagesSquare size={22}/></span><span className="subject-audience">Il primo incontro</span><h2>Programma e obiettivi</h2></div><div className="timeline-body"><p>In 15 minuti gratuiti guardiamo programma, difficoltà e data della prova. Poi concordiamo gli argomenti e un primo numero di lezioni.</p><details className="reading-disclosure"><summary>Test gratuito facoltativo</summary><p>Controlla alcuni concetti di base, non tutto il programma.</p><a className="text-link" href="/?richiesta=test">Fai il test gratuito</a></details></div></li>
  <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><PenLine size={22}/></span><span className="subject-audience">Durante la lezione</span><h2>Spiegazione, poi provi tu</h2></div><div className="timeline-body"><p>Vediamo un esempio, svolgi un esercizio e lo controlliamo insieme. Gli errori ci indicano cosa riprendere, nella teoria o nel codice.</p><details className="reading-disclosure"><summary>Lezioni con ragazzi con DSA</summary><p>Partiamo dagli strumenti e dalle abitudini di studio già usati a scuola. Concordiamo schemi e tempi, dedicando attenzione ai passaggi più difficili.</p></details></div></li>
  <li><div className="timeline-heading"><span className="timeline-marker" aria-hidden="true"><NotebookPen size={22}/></span><span className="subject-audience">Tra gli incontri</span><h2>Materiali e correzioni</h2></div><div className="timeline-body"><p>Se concordiamo esercizi a casa, li consegni nell’area studente e ritrovi lì materiali e correzioni.</p><a className="button outline" href="/piattaforma">Guarda un esempio</a><details className="reading-disclosure"><summary>Cosa comprende il lavoro tra le lezioni</summary><p>Esercizi e correzioni si concordano prima. Per un dubbio breve puoi scrivermi; le spiegazioni più lunghe si affrontano a lezione. L’assistenza non è illimitata e assegno personalmente accessi e contenuti.</p></details></div></li>
 </ol>
 <details className="public-disclosure"><summary>Come uso l’IA per matematica e informatica</summary><p>Può servire per confrontare spiegazioni, verificare un ragionamento o capire un errore nel codice. Le risposte vanno controllate, anche quando sembrano convincenti.</p><p>Gli esercizi li svolgi tu e devi saper spiegare i passaggi. Confrontiamo la risposta con il tuo tentativo per capire dove fermarci; copiarla non ci dice cosa hai imparato.</p><ul><li>In matematica controlliamo i passaggi con ciò che hai studiato.</li><li>In informatica leggiamo e proviamo il codice, cambiando anche i dati di partenza. Devi saperlo capire e modificare.</li></ul></details>
 <div className="actions"><a className="button dark" href="/incontro">Incontro gratuito</a><a className="button outline" href="/domande">Domande sulle lezioni</a></div>
 </main>;}
