import { z } from 'zod';
import { bookingDb } from '@/lib/booking/runtime';
import { isRequestOwner } from '@/lib/request-admin';
import { failure,LearningError,privateHeaders,sameOrigin } from '@/lib/learning/access';
import { homeworkData } from '@/lib/homework/data';
const id=z.string().uuid(),title=z.string().trim().min(2).max(160),copy=z.string().trim().min(1).max(10000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s;}).nullable();
const command=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('task'),id,studentId:id,planId:id.nullable(),version:z.number().int().min(0).nullable(),title,subject:title,instructions:copy,dueDate:date,status:z.enum(['draft','published','archived'])}),
 z.object({kind:z.literal('feedback'),id,version:z.number().int().min(0),feedback:copy,status:z.enum(['draft','published']),reviewStatus:z.enum(['accepted','revise'])}),
]);
export async function GET(request:Request){try{if(!await isRequestOwner())throw new LearningError('Accesso riservato al tutor.',403);const db=bookingDb(),students=await db.prepare('SELECT id,name,status FROM students ORDER BY status,name,id LIMIT 1001').all<{id:string;name:string;status:string}>(),selected=new URL(request.url).searchParams.get('studente')||students.results.find(s=>s.status==='active')?.id||students.results[0]?.id||null;if(!selected)return Response.json({students:[],selected:null,assignments:[],submissions:[],plans:[],truncated:false,studentLimit:false,planLimit:false},{headers:privateHeaders});const student=await db.prepare('SELECT id,name,status FROM students WHERE id=?').bind(selected).first<{id:string;name:string;status:string}>();if(!student)throw new LearningError('Studente non disponibile.',404);const [data,plans]=await Promise.all([homeworkData(selected,false),db.prepare('SELECT id,title,status FROM study_plans WHERE student_id=? ORDER BY updated_at DESC,id LIMIT 51').bind(selected).all()]);const list=students.results.slice(0,1000);if(!list.some(s=>s.id===selected))list.push(student);return Response.json({...data,students:list,selected,plans:plans.results.slice(0,50),studentLimit:students.results.length>1000,planLimit:plans.results.length>50},{headers:privateHeaders});}catch(e){return failure(e);}}
export async function POST(request:Request){try{
 if(!await isRequestOwner())throw new LearningError('Accesso riservato al tutor.',403);sameOrigin(request);const raw=await request.text();if(raw.length>16000)throw new LearningError('Testo troppo lungo.',413);const parsed=command.safeParse(JSON.parse(raw));if(!parsed.success)throw new LearningError('Controlla titolo, testi e data.');const p=parsed.data,db=bookingDb(),now=new Date().toISOString();
 if(p.kind==='task'){
  if(!await db.prepare("SELECT id FROM students WHERE id=? AND status='active'").bind(p.studentId).first())throw new LearningError('Ripristina lo studente prima di modificare il compito.',409);
  if(p.planId&&!await db.prepare('SELECT id FROM study_plans WHERE id=? AND student_id=?').bind(p.planId,p.studentId).first())throw new LearningError('Il piano deve appartenere alla stessa scheda.',403);
  const values=[p.planId,p.title,p.subject,p.instructions,p.dueDate],fields=['plan_id','title','subject','instructions','due_date'];const existing=await db.prepare('SELECT * FROM homework_assignments WHERE id=?').bind(p.id).first<Record<string,unknown>>();
  if(p.version===null){if(existing){if(existing.student_id===p.studentId&&existing.version===0&&existing.status===p.status&&fields.every((f,i)=>existing[f]===values[i]))return Response.json({ok:true,id:p.id},{headers:privateHeaders});throw new LearningError('Compito già aggiornato. Riaprilo prima di salvare.',409);}
   const result=await db.prepare(`INSERT INTO homework_assignments(id,student_id,plan_id,title,subject,instructions,due_date,status,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM students WHERE id=? AND status='active') AND (? IS NULL OR EXISTS(SELECT 1 FROM study_plans WHERE id=? AND student_id=?)) ON CONFLICT DO NOTHING`).bind(p.id,p.studentId,...values,p.status,now,now,p.studentId,p.planId,p.planId,p.studentId).run();if(!result.meta.changes)throw new LearningError('Dati aggiornati. Ricarica i compiti.',409);
  }else{
   if(!existing||existing.student_id!==p.studentId)throw new LearningError('Compito non disponibile.',404);
   const result=await db.prepare(`UPDATE homework_assignments SET plan_id=?,title=?,subject=?,instructions=?,due_date=?,status=?,version=version+1,updated_at=? WHERE id=? AND student_id=? AND version=? AND EXISTS(SELECT 1 FROM students WHERE id=? AND status='active') AND (? IS NULL OR EXISTS(SELECT 1 FROM study_plans WHERE id=? AND student_id=?)) AND (NOT EXISTS(SELECT 1 FROM homework_submissions WHERE assignment_id=homework_assignments.id) OR (plan_id IS ? AND title=? AND subject=? AND instructions=? AND due_date IS ?))`).bind(...values,p.status,now,p.id,p.studentId,p.version,p.studentId,p.planId,p.planId,p.studentId,...values).run();if(!result.meta.changes)throw new LearningError('Compito aggiornato, oppure già consegnato: dopo la prima consegna puoi cambiare solo la visibilità. Riaprilo dall’elenco.',409);
  }
 }else{
  const result=await db.prepare(`UPDATE homework_submissions SET feedback=?,feedback_status=?,review_status=?,version=version+1,reviewed_at=? WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM homework_assignments a JOIN students student ON student.id=a.student_id WHERE a.id=homework_submissions.assignment_id AND student.status='active') AND NOT EXISTS(SELECT 1 FROM homework_submissions newer WHERE newer.assignment_id=homework_submissions.assignment_id AND newer.attempt>homework_submissions.attempt)`).bind(p.feedback,p.status,p.reviewStatus,now,p.id,p.version).run();if(!result.meta.changes)throw new LearningError('Consegna aggiornata, tentativo superato o scheda archiviata. Riapri l’ultima consegna.',409);
 }
 return Response.json({ok:true,id:p.id},{headers:privateHeaders});
 }catch(e){return failure(e instanceof SyntaxError?new LearningError('Dati non validi.'):e);}}
