'use client';
import {useEffect,useState,useRef} from 'react';
import type {ConsultationRecurrence} from '@/lib/consultation-recurrence';
export default function DailyConsultations({onSaved}:{onSaved:()=>Promise<void>}){
 const [rule,setRule]=useState<ConsultationRecurrence|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const pending=useRef<string|null>(null);
 async function load(){try{const r=await fetch('/api/gestione/incontri/ricorrenza',{cache:'no-store'});if(!r.ok)throw Error('Disponibilità giornaliera non disponibile.');setRule(((await r.json()) as {rule:ConsultationRecurrence|null}).rule);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);pending.current??=JSON.stringify({startDate:f.get('startDate'),from:f.get('from'),to:f.get('to'),mode:f.get('mode')});await send('POST',pending.current);}
 async function send(method:string,body:string){setBusy(true);setError('');try{const r=await fetch('/api/gestione/incontri/ricorrenza',{method,headers:{'Content-Type':'application/json'},body});const d=await r.json() as {rule:ConsultationRecurrence;error?:string};if(!r.ok)throw Error(d.error||'Disponibilità non salvata.');setRule(d.rule);pending.current=null;setNotice(d.rule.active?'Disponibilità giornaliera attiva.':'Disponibilità giornaliera sospesa. Gli incontri già prenotati sono conservati.');await onSaved();}catch(e){setError((e as Error).message);await load();}finally{setBusy(false);}}
 return <section className="consultation-recurring"><h2>Incontri gratuiti ogni giorno</h2>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading?<p>Caricamento disponibilità…</p>:rule?<><p><strong>{rule.active?'Attiva':'Sospesa'} · Dal {rule.start_date.split('-').reverse().join('/')} · {rule.from_time}–{rule.to_time}</strong><br/>Tutti i giorni, sabato e domenica inclusi, senza data di fine. {rule.mode==='Entrambe'?'Online o a Lodi, a scelta.':rule.mode==='Lodi'?'In presenza a Lodi.':'Online.'}</p><p>Si aprono progressivamente le prossime cinque settimane. Incontri da 15 minuti, con 5 minuti tra un appuntamento e il successivo. Lezioni, prenotazioni e orari bloccati restano esclusi.</p><button className="button outline" disabled={busy} onClick={()=>void send('PATCH',JSON.stringify({active:!rule.active,version:rule.version}))}>{busy?'Salvataggio…':rule.active?'Sospendi disponibilità giornaliera':'Riattiva disponibilità giornaliera'}</button></>:<form onSubmit={save}><p>Apri la stessa fascia ogni giorno, senza data di fine. Potrai sospendere la ricorrenza o bloccare i singoli orari dal calendario.</p><fieldset disabled={busy||!!pending.current}><div className="form-grid"><label>Dal giorno<input name="startDate" type="date" defaultValue="2026-11-02" required/></label><label>Modalità<select name="mode" defaultValue="Entrambe"><option value="Entrambe">Online o a Lodi</option><option value="Online">Solo online</option><option value="Lodi">Solo a Lodi</option></select></label><label>Dalle<input name="from" type="time" defaultValue="10:00" required/></label><label>Alle<input name="to" type="time" defaultValue="18:30" required/></label></div></fieldset><button className="button dark" disabled={busy}>{busy?'Salvataggio…':pending.current?'Riprova gli stessi dati':'Attiva disponibilità giornaliera'}</button></form>}</section>;
}
