'use client';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Menu,X,CalendarDays,LayoutDashboard,Inbox,Clock,Users,UsersRound,BookOpen,ClipboardCheck,ListChecks,Package,Gift,KeyRound,FileText,Mail,Download,Eye,Globe} from 'lucide-react';
import {managementGroups,managementSection} from '@/lib/management/navigation';
const icons={today:LayoutDashboard,requests:Inbox,calendar:CalendarDays,free:Clock,students:Users,groups:UsersRound,courses:BookOpen,homework:ClipboardCheck,plans:ListChecks,packages:Package,referrals:Gift,accounts:KeyRound,templates:FileText,mail:Mail,export:Download};
export default function ManagementShell({children,owner}:{children:ReactNode;owner:boolean}){
 const path=usePathname()||'/gestione',[open,setOpen]=useState(false),toggle=useRef<HTMLButtonElement>(null),nav=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;function key(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}}function outside(e:PointerEvent){if(!nav.current?.contains(e.target as Node)&&!toggle.current?.contains(e.target as Node))setOpen(false);}document.addEventListener('keydown',key);document.addEventListener('pointerdown',outside);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('pointerdown',outside);};},[open]);
 return <div className={'tutor-shell'+(!owner?' tutor-locked':'')}><a className="skip" href="#tutor-content">Vai al contenuto</a><header className="tutor-header"><a className="tutor-brand" href="/gestione/oggi"><img src="/francesco-fracchia-logo.png" alt="Francesco Fracchia" width={2172} height={724}/><span>Area tutor</span></a><div className="tutor-header-actions"><a href="/" className="tutor-external"><Globe size={18} aria-hidden="true"/>Sito pubblico</a>{owner&&<a href="/studente" className="tutor-external"><Eye size={18} aria-hidden="true"/>Anteprima studente</a>}{owner&&<button className="tutor-menu" ref={toggle} aria-label={open?'Chiudi menu gestione':'Apri menu gestione'} aria-expanded={open} aria-controls="tutor-navigation" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button>}</div></header>
 {owner&&<aside className={'tutor-sidebar'+(open?' is-open':'')} ref={nav} id="tutor-navigation"><nav aria-label="Navigazione gestione">{managementGroups.map(g=><section key={g.label}><h2>{g.label}</h2>{g.items.map(i=>{const Icon=icons[i.icon];return <a href={i.href} key={i.href} aria-current={path===i.href?'page':undefined} onClick={()=>setOpen(false)}><Icon size={18} aria-hidden="true"/>{i.label}</a>;})}</section>)}</nav><div className="tutor-sidebar-footer"><a href="/account">Il mio account</a><span>Site privato · email e pagamenti in prova</span></div></aside>}
 <div className="tutor-content" id="tutor-content" tabIndex={-1}><p className="tutor-breadcrumb">{owner?'Area tutor · '+managementSection(path):'Accesso riservato al tutor'}</p>{children}</div></div>;
}
