import { requestDetails,detailText,type RequestRow } from '@/lib/requests/types';
import { consultationDate,consultationTime } from '@/lib/consultations';

export default function RequestContext({row}:{row:RequestRow}) {
 const details=requestDetails(row.details);
 const assessment=row.assessment?requestDetails(row.assessment):null;
 const participants=Array.isArray(details.participants)?details.participants:[];
 const review=assessment&&Array.isArray(assessment.review)?assessment.review:[];
 return <>{detailText(details,'referralCode')&&<p>Codice invita un amico: <strong>{detailText(details,'referralCode')}</strong> · <a href={'/gestione/inviti?richiesta='+row.id}>Verifica invito e premio</a></p>}<dl className="request-review">{Object.entries(row.kind==='contact'?{Email:row.email,Materia:row.subject,Messaggio:detailText(details,'message')}:{Email:row.email,Telefono:detailText(details,'phone'),Materia:row.subject,Studi:detailText(details,'studentType'),Istituto:detailText(details,'institution'),'Classe / corso':detailText(details,'year'),Docente:detailText(details,'teacher'),Programma:detailText(details,'program'),Obiettivo:detailText(details,'goal'),'Data obiettivo':detailText(details,'deadline'),Disponibilità:detailText(details,'availability'),Modalità:detailText(details,'mode'),Livello:detailText(details,'level')}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value||'—'}</dd></div>)}</dl>
 {row.kind==='consultation'&&detailText(details,'consultationId')&&<section><h3>Appuntamento dal calendario</h3>{detailText(details,'appointmentStart')&&<p>{consultationDate(detailText(details,'appointmentStart'))} · {consultationTime(detailText(details,'appointmentStart'))}{detailText(details,'appointmentEnd')&&'–'+consultationTime(detailText(details,'appointmentEnd'))}</p>}<p>Per cancellare l’appuntamento usa la gestione degli incontri. Lo stato della richiesta non cambia la prenotazione.</p><a className="button outline" href="/gestione/incontri">Gestisci incontro gratuito</a></section>}
 {row.kind==='group'&&<section><h3>{details.groupRequest==='existing'?'Gruppo già formato':'Ricerca di un gruppo'}</h3><p>Dimensione preferita: {detailText(details,'groupSize')||'Da concordare'}</p>{participants.map((p,i)=>{if(!p||typeof p!=='object')return null;return <p key={i}><b>{String(p.name||'')}</b> · {String(p.level||'Preparazione da verificare')}</p>;})}<p>{detailText(details,'sharedProgram')}</p><p>{detailText(details,'groupNotes')}</p></section>}
 {assessment&&<section><h3>Test: {detailText(assessment,'test')} · {typeof assessment.score==='number'?assessment.score:'—'}%</h3><p>{detailText(assessment,'student')}</p>{review.map((q,i)=>{if(!q||typeof q!=='object')return null;return <div className="assessment-answer" key={i}><b>{q.correct?'✓':'○'} {String(q.topic||'')} · {q.correct?'Risposta corretta':'Da ripassare'}</b><p>{String(q.question||'')}</p><p>Risposta dello studente: <strong>{String(q.answer||'')}</strong></p><p>Risposta corretta: {String(q.correctAnswer||'')}</p><small>{String(q.explanation||'')}</small></div>;})}{!review.length&&<p>Questo test non contiene il dettaglio delle risposte.</p>}</section>}
 </>;
}
