'use client';
import {useRef,useState,type FormEvent} from 'react';
import type {RequestRow} from '@/lib/requests/types';
import {leadSources,localInput} from '@/lib/management/operations';
import {romeDateTime} from '@/lib/lesson-plan';
import {messageText} from '@/lib/management/templates';
import TemplateTools from './template-tools';
export default function RequestFollowup({row,onSaved}:{row:RequestRow;onSaved:(row:RequestRow)=>void}){
 const [last,setLast]=useState(localInput(row.last_contact_at)),[action,setAction]=useState(row.next_action||''),[date,setDate]=useState(row.next_action_date||''),[source,setSource]=useState(row.source||'unknown'),[notes,setNotes]=useState(row.followup_notes||''),[message,setMessage]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const messageForm=useRef<HTMLFormElement>(null);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),contactInput=String(f.get('lastContactAt')||''),nextDate=String(f.get('nextActionDate')||'');setLast(contactInput);setDate(nextDate);setBusy(true);setError('');setNotice('');try{const lastContactAt=contactInput?romeDateTime(contactInput.slice(0,10),contactInput.slice(11,16)):null;const r=await fetch('/api/gestione/richieste/seguito',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,version:row.followup_version??null,lastContactAt,nextAction:action,nextActionDate:nextDate||null,source,notes})}),d=await r.json() as {error?:string;version:number};if(!r.ok)throw Error(d.error||'Seguito non salvato.');onSaved({...row,last_contact_at:lastContactAt,next_action:action.trim(),next_action_date:nextDate||null,source,followup_notes:notes.trim(),followup_version:d.version});setNotice('Seguito salvato. Nessun messaggio inviato.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="request-followup"><h3>Seguito della richiesta</h3><p>Informazioni riservate alla gestione. La data dell’ultimo contatto va aggiornata dopo aver parlato o scritto alla persona.</p><form onSubmit={save}><fieldset disabled={busy}><label>Ultimo contatto · ora di Roma<input type="datetime-local" name="lastContactAt" value={last} onChange={e=>setLast(e.target.value)}/></label><button type="button" className="text-link" onClick={()=>setLast(localInput(new Date().toISOString()))}>Ho contattato la persona adesso</button><label>Prossima azione<input value={action} onChange={e=>{setAction(e.target.value);if(!e.target.value.trim())setDate('');}} maxLength={300} placeholder="Es. Concordare gli orari del gruppo"/></label><label>Data del prossimo contatto<input type="date" name="nextActionDate" value={date} onChange={e=>setDate(e.target.value)} disabled={!action.trim()}/></label><label>Come è arrivato il contatto?<select value={source} onChange={e=>setSource(e.target.value)}>{Object.entries(leadSources).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Note interne<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label><button className="button dark">{busy?'Salvataggio…':'Salva seguito'}</button></fieldset></form>{error&&<p role="alert" className="error">{error} Il testo resta nel modulo; usa “Aggiorna” nell’elenco per riaprire la versione salvata.</p>}{notice&&<p role="status">{notice}</p>}<details className="message-draft"><summary>Prepara un messaggio</summary><form ref={messageForm} onSubmit={e=>e.preventDefault()}><TemplateTools kind="message" formRef={messageForm} onApply={values=>setMessage(messageText(values.body||'',row.name,row.subject))}/><label>Bozza del messaggio<textarea name="body" value={message} maxLength={4000} rows={5} onChange={e=>setMessage(e.target.value)}/></label><button className="button outline" type="button" disabled={!message.trim()} onClick={async()=>{try{await navigator.clipboard.writeText(message);setNotice('Messaggio copiato. Puoi controllarlo e inviarlo personalmente.');}catch{setError('Copia il testo selezionandolo nel campo.');}}}>Copia il messaggio</button><p>Nei modelli puoi usare {'{nome}'} e {'{materia}'}. Copiare la bozza non aggiorna automaticamente l’ultimo contatto.</p></form></details></section>;
}
