'use client';
import {useEffect,useRef,useState,type RefObject} from 'react';
import {templateFields,templateValues,type TemplateKind,type TutorTemplate} from '@/lib/management/templates';
export default function TemplateTools({kind,formRef,onApply,disabled=false}:{kind:TemplateKind;formRef:RefObject<HTMLFormElement|null>;onApply?:(values:Record<string,string>)=>void;disabled?:boolean}){
 const [models,setModels]=useState<TutorTemplate[]>([]),[chosen,setChosen]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[truncated,setTruncated]=useState(false);const pendingId=useRef('');
 useEffect(()=>{const c=new AbortController();setLoading(true);fetch('/api/gestione/modelli?tipo='+kind,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as {templates:TutorTemplate[];truncated:boolean;error?:string};if(!r.ok)throw Error(d.error||'Modelli non disponibili.');return d as {templates:TutorTemplate[];truncated:boolean};}).then(d=>{if(!c.signal.aborted){setModels(d.templates);setTruncated(d.truncated);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[kind,reload]);
 function apply(){const model=models.find(m=>m.id===chosen);if(!model||!formRef.current)return;const values=templateValues(kind,model.content);for(const [key,value] of Object.entries(values)){const control=formRef.current.elements.namedItem(key);if(control instanceof HTMLInputElement||control instanceof HTMLTextAreaElement)control.value=value;}onApply?.(values);setNotice('Testi inseriti nel modulo. Controllali prima di salvare.');}
 async function save(){if(!formRef.current)return;setBusy(true);setError('');setNotice('');try{const f=new FormData(formRef.current),content=Object.fromEntries(templateFields[kind].map(field=>[field.name,String(f.get(field.name)||'')]));pendingId.current||=crypto.randomUUID();const r=await fetch('/api/gestione/modelli',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:pendingId.current,version:null,kind,name,content,status:'active'})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Modello non salvato.');pendingId.current='';setName('');setNotice('Modello salvato. Nessun contenuto è stato assegnato o inviato.');setReload(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="template-tools"><summary>Usa o salva un modello</summary><p>Un modello inserisce soltanto i testi. Studente, date, appuntamento e visibilità restano da scegliere nel modulo. Non inserire dati personali nei modelli riutilizzabili.</p><div className="template-tool-row"><label>Modello<select value={chosen} disabled={disabled||busy||loading} onChange={e=>setChosen(e.target.value)}><option value="">{loading?'Caricamento…':'Scegli un modello'}</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button type="button" className="button outline" disabled={disabled||busy||!chosen} onClick={apply}>Inserisci i testi</button></div><p>I testi del modulo verranno sostituiti. Il contenuto originale del modello resta salvato.</p><div className="template-tool-row"><label>Nome per salvare questi testi<input value={name} maxLength={120} onChange={e=>setName(e.target.value)} disabled={disabled||busy}/></label><button type="button" className="button outline" disabled={disabled||busy||name.trim().length<2} onClick={()=>void save()}>{busy?'Salvataggio…':'Salva come modello'}</button></div>{truncated&&<p>Mostriamo i primi 200 modelli. Puoi archiviarli nella gestione modelli.</p>}{error&&<div role="alert" className="error"><p>{error}</p><button type="button" className="text-link" onClick={()=>setReload(n=>n+1)}>Ricarica modelli</button></div>}{notice&&<p role="status">{notice}</p>}<a className="text-link" href="/gestione/modelli">Gestisci i modelli</a></details>;
}
