import { isRequestOwner } from '@/lib/request-admin';
import { resolveStudent,resolveGroup } from '@/lib/students/resolve';
import { newNoticeStatement,noticeStatements,dispatchAppointmentNotices } from '@/lib/notifications/appointments';
import { bookingDb,paymentConfig } from '@/lib/booking/runtime';
import { lessonDates,romeDateTime } from '@/lib/lesson-plan';
import { z } from 'zod';
const participant=z.object({studentId:z.string().uuid().optional(),name:z.string().trim().min(2).max(100),email:z.string().email().max(254)});
const schema=z.object({batchId:z.string().uuid(),name:z.string().trim().min(2).max(100),email:z.string().email().max(254),subject:z.string().trim().min(2).max(100),mode:z.enum(['Online','Lodi']),paymentMethod:z.enum(['online','pos','cash']).default('online'),alreadyPaid:z.boolean().default(false),studentId:z.string().uuid().optional(),groupId:z.string().uuid().optional(),participants:z.array(participant).min(1).max(4).optional(),notes:z.string().max(2000),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^\d{2}:\d{2}$/),repeat:z.enum(['single','multiple','weekly','fortnightly']),count:z.number().int().min(1).max(24),extraDates:z.array(z.string().regex(/^\d{4}-\d{2}-\d{2}$/)).max(23)});
export async function POST(request:Request){if(!await isRequestOwner())return Response.json({error:'Accesso non consentito.'},{status:403});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Origine non consentita.'},{status:403});try{const raw=await request.text();if(raw.length>6000)return Response.json({error:'Richiesta troppo grande.'},{status:413});const parsed=schema.safeParse(JSON.parse(raw));if(!parsed.success)return Response.json({error:'Controlla i dati della lezione.'},{status:400});const p=parsed.data;const db=bookingDb();const existing=await db.prepare('SELECT id FROM scheduled_lessons WHERE series_id=?').bind(p.batchId).all();if(existing.results.length)return Response.json({ok:true,count:existing.results.length});
 const selectedGroup=p.groupId?await resolveGroup(p.groupId):null;
 const people=selectedGroup?selectedGroup.members:await Promise.all((p.participants||[{name:p.name,email:p.email,studentId:p.studentId}]).map(resolveStudent));
 if(new Set(people.map(x=>x.email.toLowerCase())).size!==people.length)return Response.json({error:'Inserisci un’email diversa per ogni partecipante.'},{status:400});
 const amount=people.length===1?2000:1500;const groupId=selectedGroup?.id||(people.length>1?crypto.randomUUID():null);
 const registryStatements=groupId&&!selectedGroup?[
 db.prepare('INSERT INTO student_groups(id,name,subject,created_at,updated_at) VALUES(?,?,?,?,?)').bind(groupId,p.name,p.subject,new Date().toISOString(),new Date().toISOString()),
 ...people.map(s=>db.prepare('INSERT INTO group_members(group_id,student_id) VALUES(?,?)').bind(groupId,s.id))]:[];
 const dates=lessonDates(p);const occurrences=dates.map(d=>{const start=romeDateTime(d,p.time);if(Date.parse(start)<=Date.now()||Date.parse(start)>Date.now()+366*86400000)throw Error('INVALID_DATE');if(p.paymentMethod==='online'&&!p.alreadyPaid&&Date.parse(start)<=Date.now()+3600000)throw Error('PAY_NOW');return {id:crypto.randomUUID(),start,end:new Date(Date.parse(start)+55*60000).toISOString()};});const now=new Date().toISOString();const statements=occurrences.flatMap(o=>{const payees=people.map(person=>({person,id:crypto.randomUUID(),token:crypto.randomUUID()+crypto.randomUUID()}));return [
 db.prepare("INSERT INTO scheduled_lessons(id,series_id,name,email,subject,starts_at,ends_at,mode,notes,payment_method,payment_status,paid_at,student_id,group_id,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'planned',?)").bind(o.id,p.batchId,p.name,p.email,p.subject,o.start,o.end,p.mode,p.notes,p.paymentMethod,p.alreadyPaid?'paid':'awaiting',p.alreadyPaid?now:null,people.length===1?people[0].id:null,groupId,now),
 ...payees.map(({person,id,token})=>db.prepare("INSERT INTO lesson_payments(id,lesson_id,access_token,student_id,name,email,amount,status,paid_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,o.id,token,person.id,person.name,person.email,amount,p.alreadyPaid?'manual_paid':'awaiting',p.alreadyPaid?now:null,now)),
 ...payees.map(({person,id,token})=>newNoticeStatement('lesson',o.id,p.alreadyPaid||p.paymentMethod!=='online'?'confirmed':'reserved',0,{id:o.id,subject:p.subject,starts_at:o.start,ends_at:o.end,mode:p.mode,payment_method:p.paymentMethod,payment_status:p.alreadyPaid?'paid':'awaiting'},{name:person.name,email:person.email,studentId:person.id,notifications:person.notifications,amount,paymentLink:paymentConfig().origin?`${paymentConfig().origin}/pagamento?saldo=${id}#${token}`:undefined},"status='planned'")),
 db.prepare("UPDATE booking_slots SET status='scheduled',booking_id=? WHERE status='available' AND julianday(starts_at)<julianday(?)+5.0/1440 AND julianday(ends_at)>julianday(?)-5.0/1440").bind(o.id,o.end,o.start),
 db.prepare("INSERT INTO booking_slots(id,starts_at,ends_at,mode,status,booking_id) SELECT ?,?,?,?,'scheduled',? WHERE NOT EXISTS(SELECT 1 FROM booking_slots WHERE starts_at=? AND booking_id=?)").bind('manual-'+o.id,o.start,o.end,p.mode,o.id,o.start,o.id)
]});await db.batch([...registryStatements,...statements]);const notifications=await dispatchAppointmentNotices();return Response.json({ok:true,count:occurrences.length,notifications},{status:201});}catch(e){const msg=String(e);if(msg.includes('LESSON_CONFLICT'))return Response.json({error:'Una delle date si sovrappone a una lezione o a un orario bloccato. Nessuna lezione della serie è stata salvata.'},{status:409});if(msg.includes('STUDENT_INACTIVE')||msg.includes('GROUP_INACTIVE'))return Response.json({error:'Studente o gruppo non disponibile: controlla l’anagrafica.'},{status:409});if(msg.includes('PAY_NOW'))return Response.json({error:'A meno di un’ora dalla lezione verifica prima il pagamento oppure concorda POS/contanti.'},{status:400});if(msg.includes('INVALID_DATE')||msg.includes('non valid'))return Response.json({error:'Scegli date future entro un anno e un orario valido.'},{status:400});return Response.json({error:'Non siamo riusciti a salvare le lezioni. Riprova.'},{status:503});}}
export async function PATCH(request:Request){
 if(!await isRequestOwner())return new Response(null,{status:403});if(request.headers.get('origin')!==new URL(request.url).origin)return new Response(null,{status:403});
 try{
  const raw=await request.text();if(raw.length>500)return new Response(null,{status:413});const p=z.object({id:z.string().uuid(),action:z.enum(['mark-paid','method']),method:z.enum(['online','pos','cash']).optional()}).parse(JSON.parse(raw));
  const db=bookingDb();const old=await db.prepare('SELECT version,payment_method FROM scheduled_lessons WHERE id=?').bind(p.id).first<{version:number;payment_method:string}>();if(!old)return new Response(null,{status:404});
  const now=new Date().toISOString();const deadline=new Date(Date.now()+3600000).toISOString();const version=old.version+1;const operationId=crypto.randomUUID();
  const gate=" AND status='planned' AND payment_status NOT IN ('paid','payment_review') AND NOT EXISTS(SELECT 1 FROM lesson_payments WHERE lesson_id=scheduled_lessons.id AND (status IN ('pending','payment_review','paid') OR stripe_session IS NOT NULL))";
  let change;if(p.action==='mark-paid')change=db.prepare("UPDATE scheduled_lessons SET payment_status='paid',paid_at=?,version=version+1,operation_id=? WHERE id=? AND version=?"+gate+" AND (payment_method!='online' OR starts_at>?)").bind(now,operationId,p.id,old.version,deadline);
  else{if(!p.method)return new Response(null,{status:400});change=db.prepare("UPDATE scheduled_lessons SET payment_method=?,payment_status='awaiting',version=version+1,operation_id=? WHERE id=? AND version=?"+gate+" AND (?!='online' OR starts_at>?)").bind(p.method,operationId,p.id,old.version,p.method,deadline);}
  const notices=await noticeStatements('lesson',p.id,p.action==='mark-paid'?'confirmed':'modified',version,{payment_status:p.action==='mark-paid'?'paid':'awaiting',payment_method:p.method||old.payment_method},"status='planned' AND operation_id='"+operationId+"'");
  const statements=[change,...(p.action==='mark-paid'?[db.prepare("UPDATE lesson_payments SET status='manual_paid',paid_at=? WHERE lesson_id=? AND status='awaiting' AND EXISTS(SELECT 1 FROM scheduled_lessons WHERE id=? AND version=? AND operation_id=? AND payment_status='paid')").bind(now,p.id,p.id,version,operationId)]:[]),...notices];
  const results=await db.batch(statements);if(!results[0].meta.changes)return Response.json({error:'Lezione già saldata, scaduta o con checkout Stripe collegato. Ricarica il calendario.'},{status:409});
  await dispatchAppointmentNotices();return Response.json({ok:true});
 }catch{return Response.json({error:'Aggiornamento non riuscito.'},{status:400});}
}
