'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { civilDate,lessonDate } from '@/lib/study/types';
import { late,pendingDue,reviewLabels,type Assignment,type HomeworkData,type Submission } from '@/lib/homework/types';
function Task({task,attempts,studentId,preview,canSubmit,onSaved}:{task:Assignment;attempts:Submission[];studentId:string;preview:boolean;canSubmit:boolean;onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const attemptId=useRef('');const form=useRef<HTMLFormElement>(null),latest=attempts[0],allowed=canSubmit&&attempts.length<20&&(!latest||(latest.feedback_status==='published'&&latest.review_status==='revise'));
 function fileUrl(kind:'task'|'submission',id:string){const p=new URLSearchParams({kind,id,studente:studentId});if(preview)p.set('anteprima',studentId);return '/api/studente/compiti/file?'+p;}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!attemptId.current)attemptId.current=crypto.randomUUID();const f=new FormData(e.currentTarget);f.set('id',attemptId.current);f.set('assignmentId',task.id);const body=String(f.get('body')||'').trim(),file=f.get('file');if(!body&&(!(file instanceof File)||!file.size)){setError('Scrivi una risposta o scegli un file.');return;}if(file instanceof File&&file.size>10*1024*1024){setError('Il file supera 10 MB.');return;}setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/studente/compiti',{method:'POST',body:f}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Consegna non completata.');setNotice('Consegna ricevuta. Francesco potrà correggerla.');attemptId.current='';form.current?.reset();onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <article className="learning-course homework-task student-focus-target" id={'homework-'+task.id} tabIndex={-1}><div className="homework-heading"><div><span className="booking-badge">{task.subject}</span><h3>{task.title}</h3>{task.plan_title&&<p>Piano: {task.plan_title}</p>}</div><span className="booking-badge">{latest?reviewLabels[latest.review_status]:'Da consegnare'}</span></div>{task.due_date&&<p>Consegna entro {civilDate(task.due_date)}{!latest&&pendingDue(task.due_date)?' · Data superata, puoi ancora consegnare':''}</p>}<p className="learning-copy">{task.instructions}</p>{task.filename&&<a className="button outline" href={fileUrl('task',task.id)}>Scarica esercizi · {task.filename}</a>}{notice&&<p role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}{allowed&&<form ref={form} className="homework-submit" onSubmit={submit} onChange={()=>{attemptId.current='';}}><h4>{latest?'Nuovo tentativo':'La tua consegna'}</h4><fieldset disabled={busy}><label>Risposta o spiegazione<textarea name="body" maxLength={10000} rows={5}/></label><label>Allegato, facoltativo<input type="file" name="file" accept="application/pdf,image/png,image/jpeg,text/plain"/></label><p>PDF, PNG, JPEG o testo UTF-8, fino a 10 MB. Puoi consegnare anche soltanto una risposta scritta.</p><button className="button dark">{busy?'Invio…':'Invia consegna'}</button></fieldset></form>}{!canSubmit&&<p>{preview?'L’anteprima è in sola lettura.':'Il referente può leggere compiti, consegne e correzioni. Solo lo studente può inviare una consegna.'}</p>}{attempts.length>=20&&<p>Hai raggiunto 20 tentativi. Contatta Francesco per proseguire.</p>}{attempts.length>0&&<section className="homework-attempts"><h4>Consegne e correzioni</h4>{attempts.map(s=><details key={s.id} open={s.id===latest?.id}><summary>Tentativo {s.attempt} · {lessonDate(s.created_at)} · {reviewLabels[s.review_status]}</summary>{late(s.created_at,task.due_date)&&<p>Consegnato dopo la data indicata.</p>}{s.body&&<p className="learning-copy">{s.body}</p>}{s.filename&&<a className="button outline" href={fileUrl('submission',s.id)}>Scarica consegna · {s.filename}</a>}{s.feedback_status==='published'?<div className="homework-feedback"><h4>Correzione di Francesco</h4><p className="learning-copy">{s.feedback}</p>{s.reviewed_at&&<p>Condivisa il {lessonDate(s.reviewed_at)}</p>}</div>:<p>La correzione non è ancora stata condivisa.</p>}</details>)}</section>}</article>;
}
export default function StudentHomework({studentId,preview}:{studentId:string;preview:boolean}){
 const [data,setData]=useState<(HomeworkData&{canSubmit:boolean})|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setError('');const p=new URLSearchParams({studente:studentId});if(preview)p.set('anteprima',studentId);fetch('/api/studente/compiti?'+p,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as HomeworkData&{canSubmit:boolean;error?:string};if(!r.ok)throw Error(d.error||'Compiti non disponibili.');return d;}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[studentId,preview,revision]);
 return <section><h2>Compiti e correzioni</h2>{error&&<div className="error" role="alert"><p>{error}</p><button className="button outline" onClick={()=>setRevision(v=>v+1)}>Riprova</button></div>}{!data&&!error&&<p role="status">Caricamento…</p>}{data&&<>{data.truncated&&<p>Mostriamo gli ultimi 50 compiti condivisi. Per lo storico precedente contatta Francesco.</p>}{!data.assignments.length&&<div className="booking-empty"><p>Non ci sono ancora compiti assegnati. Quando Francesco li pubblicherà, vedrai qui gli esercizi da consegnare e le correzioni.</p></div>}{data.assignments.map(task=><Task key={task.id} task={task} attempts={data.submissions.filter(s=>s.assignment_id===task.id)} studentId={studentId} preview={preview} canSubmit={data.canSubmit} onSaved={()=>setRevision(v=>v+1)}/>)}</>}</section>;
}
