'use client';
import WhatsAppIcon from '@/components/site/whatsapp-icon';
import { useEffect,useState } from 'react';
import type { PackageData } from '@/lib/packages/types';
const date=(s:string)=>new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(s));
export default function StudentPackages({studentId,preview}:{studentId:string;preview:boolean}){
 const [data,setData]=useState<PackageData|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController(),p=new URLSearchParams({studente:studentId});if(preview)p.set('anteprima',studentId);fetch('/api/studente/pacchetti?'+p,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as PackageData&{error?:string};if(c.signal.aborted)return;if(!r.ok)throw Error(d.error||'Pacchetti non disponibili.');setData(d);setError('');}).catch(e=>{if(!c.signal.aborted){setData(null);setError(e.message);}});return()=>c.abort();},[studentId,preview,revision]);
 return <section className="student-packages"><h2>I tuoi pacchetti</h2><p>5 lezioni individuali da 55 minuti a 95 €, pagate insieme. Puoi scegliere gli orari aperti dopo il pagamento o concordarli con Francesco.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="actions">{!preview&&<a className="button dark" href="/acquista">Acquista o prenota lezioni</a>}<button className="button outline" onClick={()=>setRevision(v=>v+1)}>Aggiorna pacchetti</button></div>{!data&&!error?<p role="status">Caricamento…</p>:data&&<>{!data.packages.length&&<p>Non hai ancora pacchetti registrati. Per informazioni <a href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>scrivi a Francesco</a>.</p>}{data.packages.map(p=><article className="registry-card" key={p.id}><h3>{p.status==='voided'?'Pacchetto annullato':`${p.remaining} / ${p.units} lezioni residue`}</h3><p>{p.units} {p.units===1?"lezione individuale":"lezioni individuali"} · {p.amount/100} €</p>{p.status==='awaiting'?<p>Il pagamento deve ancora essere completato o verificato.</p>:p.status==='active'?<><p>Saldo registrato{p.paid_at?' il '+date(p.paid_at):''}.</p><p>{p.remaining?'Concorda con Francesco giorno e orario delle prossime lezioni.':'Tutte le lezioni del pacchetto sono state associate.'}</p></>:<p>Per verificare l’annullamento e l’eventuale saldo contatta Francesco.</p>}<ul>{data.uses.filter(x=>x.package_id===p.id).map(x=><li key={x.id}>{date(x.starts_at)} · {x.subject} · {x.status==='returned'?'Restituita al pacchetto':x.lesson_status==='planned'?'Coperta dal pacchetto':'Da verificare con Francesco'}</li>)}</ul></article>)}<p>Il credito “Invita un amico” si usa su altre lezioni: non si somma al prezzo del pacchetto. Uno spostamento mantiene l’associazione; se l’appuntamento viene annullato, la lezione torna nel pacchetto. Eventuali rimborsi si concordano con Francesco.</p>{data.truncated&&<p>Mostriamo fino a 200 pacchetti e utilizzi. Per lo storico precedente contatta Francesco.</p>}</>}</section>;
}
