'use client';
import WhatsAppIcon from '@/components/site/whatsapp-icon';
import { useEffect,useState } from 'react';
import ReferralTerms from '@/components/site/referral-terms';
import type { ReferralData } from '@/lib/referrals/rules';
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n/100);
const date=(s:string)=>new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeZone:'Europe/Rome'}).format(new Date(s));
export default function StudentReferrals({studentId,preview}:{studentId:string;preview:boolean}){
 const [data,setData]=useState<ReferralData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[origin,setOrigin]=useState('');
 useEffect(()=>{const c=new AbortController(),p=new URLSearchParams({studente:studentId});if(preview)p.set('anteprima',studentId);fetch('/api/studente/inviti?'+p,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as ReferralData&{error?:string};if(!r.ok)throw Error(d.error||'Inviti non disponibili.');return d;}).then(d=>{if(!c.signal.aborted){setData(d);setOrigin(window.location.origin);setError('');}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[studentId,preview,revision]);
 async function create(){setBusy(true);setError('');try{const r=await fetch('/api/studente/inviti',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Operazione non confermata. Riprova.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const url=data?.code&&origin?origin+'/invita?codice='+data.code:'';
 async function copy(){try{await navigator.clipboard.writeText(url);setNotice('Link copiato.');}catch{setNotice('Seleziona e copia il link dal campo qui sopra.');}}
 return <section className="student-referrals"><h2>Invita un amico</h2><p>Condividi il tuo link con un compagno. Se iniziate a fare lezione insieme, il premio è maggiore.</p><ReferralTerms/>{error&&<div className="error" role="alert"><p>{error}</p><button className="text-link" onClick={()=>setRevision(v=>v+1)}>Riprova</button></div>}{!data&&!error?<p role="status">Caricamento inviti…</p>:data&&<><article className="referral-share"><h3>Il tuo link</h3>{data.code?<><label>Link da condividere<input readOnly value={url} onFocus={e=>e.currentTarget.select()}/></label><p>Codice: <strong>{data.code}</strong></p><div className="actions"><button className="button outline" onClick={copy}>Copia link</button><a className="button outline" href={'https://wa.me/?text='+encodeURIComponent('Se vuoi fare lezioni di matematica o informatica con Francesco, qui trovi informazioni e il mio codice invito: '+url)} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Condividi su WhatsApp</a><a className="text-link" href={'/invita?codice='+data.code}>Apri pagina invito</a></div></>:<><p>{preview?'Il tutor può preparare il codice da Gestione inviti.':'Prepara un link associato alla tua scheda studente.'}</p><button className="button outline" disabled={busy||preview} onClick={create}>{busy?'Preparazione…':'Crea il mio link'}</button></>}<p className="form-note">Durante la revisione il sito resta privato: condividere il link non concede accesso dall’esterno. Nessun messaggio viene inviato automaticamente.</p>{notice&&<p role="status">{notice}</p>}</article><h3>I tuoi crediti</h3>{!data.credits.length&&<p>Non ci sono ancora premi assegnati.</p>}<div className="referral-options">{data.credits.map(c=><article className="registry-card" key={c.id}><span className="booking-badge">{c.kind==='group'?'Solo lezioni di gruppo':'Lezioni individuali o di gruppo'}</span><h4>{money(c.remaining)} residui su {money(c.amount)}</h4><p>Valido fino al {date(c.expires_at)}.</p><p>{c.status==='revoked'?'Premio annullato.':c.remaining===0?'Credito utilizzato.':c.available?'Concorda con Francesco la lezione su cui usarlo, prima del pagamento.':'Credito scaduto o da verificare con Francesco.'}</p></article>)}</div><h3>Inviti registrati</h3>{!data.invites.length?<p>Gli inviti compaiono dopo che Francesco ha collegato la richiesta alla scheda dell’amico.</p>:<ul className="referral-history">{data.invites.map((r,i)=><li key={r.id}><strong>Invito {i+1}</strong> · {date(r.created_at)} · {r.status==='pending'?'In verifica':r.status==='rewarded'?'Premio assegnato':r.status==='rejected'?'Non idoneo':'Premio annullato'}</li>)}</ul>}<p className="form-note">Non vengono mostrati recapiti, lezioni o saldi dell’altra persona.</p>{data.truncated&&<p>Mostriamo gli ultimi 200 inviti e crediti. Per lo storico precedente contatta Francesco.</p>}</>}
 </section>;
}
