'use client';
import { useEffect,useState } from 'react';
import { civilDate,lessonDate,type StudyData } from '@/lib/study/types';
function Copy({title,text}:{title:string;text:string}){return text?<div className="study-copy"><h4>{title}</h4><p className="learning-copy">{text}</p></div>:null;}
export default function StudentStudy({studentId,preview,focusedId}:{studentId:string;preview:boolean;focusedId?:string|null}){
 const [data,setData]=useState<StudyData|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setError('');const p=new URLSearchParams({studente:studentId});if(preview)p.set('anteprima',studentId);fetch('/api/studente/piano?'+p,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as StudyData&{error?:string};if(!r.ok)throw Error(d.error||'Percorso temporaneamente non disponibile.');return d;}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[studentId,preview,revision]);
 return <section>{error?<div className="error" role="alert"><p>{error}</p><button className="button outline" onClick={()=>setRevision(v=>v+1)}>Riprova</button></div>:!data?<p role="status">Caricamento del percorso…</p>:<><h2>Il tuo piano di studio</h2>{data.truncated.plans&&<p>Mostriamo gli ultimi 50 piani condivisi. Per quelli precedenti contatta Francesco.</p>}{!data.plans.length&&<div className="booking-empty"><p>Non c’è ancora un piano condiviso. Quando Francesco lo pubblicherà, vedrai gli obiettivi e gli argomenti che avete concordato.</p></div>}{data.plans.map(p=><article className="learning-course study-plan student-focus-target" id={'plan-'+p.id} tabIndex={-1} key={p.id}><span className="booking-badge">{p.subject}</span><h3>{p.title}</h3>{p.target_date&&<p className="study-target">Obiettivo entro {civilDate(p.target_date)}</p>}<Copy title="Obiettivo" text={p.objective}/><Copy title="Situazione iniziale" text={p.starting_point}/><Copy title="Argomenti su cui lavorare" text={p.topics}/><Copy title="Prossimi passi" text={p.next_steps}/></article>)}<h2>Riepiloghi delle lezioni</h2>{data.truncated.summaries&&<p>Mostriamo gli ultimi 100 riepiloghi condivisi.</p>}{!data.summaries.length&&<div className="booking-empty"><p>Quando Francesco condivide il riepilogo di una lezione, puoi leggerlo qui con gli esercizi da svolgere.</p></div>}{data.summaries.map(s=><article className="registry-card study-summary student-focus-target" id={'summary-'+s.id} tabIndex={-1} key={s.id}><p>{lessonDate(s.starts_at)} · {s.subject}</p><h3>{s.title}</h3>{['cancelled','expired'].includes(s.appointment_status)&&<p>La lezione è cancellata o scaduta. Puoi comunque leggere il riepilogo già condiviso.</p>}<details open={focusedId==='summary-'+s.id}><summary>Argomenti, esercizi e prossimi passi</summary><Copy title="Argomenti affrontati e risultati" text={s.topics}/><Copy title="Esercizi da svolgere" text={s.practice}/><Copy title="Preparazione per la prossima lezione" text={s.next_steps}/></details></article>)}</>}</section>;
}
