import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));
let owner=false,user=null,beforeWrite=null,beforePut=null,failAfterWrite=false;
const db={prepare(query){const bind=(...args)=>({async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){if(beforeWrite&&/^(INSERT|UPDATE)/.test(query)){const f=beforeWrite;beforeWrite=null;f();}const r=sql.prepare(query).run(...args);if(failAfterWrite){failAfterWrite=false;throw Error('simulated lost database acknowledgement');}return {meta:{changes:Number(r.changes)}};}});return {bind,...bind()};}};
const objects=new Map(),env={BUCKET:{async put(key,bytes){objects.set(key,new Uint8Array(bytes));if(beforePut){const f=beforePut;beforePut=null;f();}},async delete(key){objects.delete(key);},async get(key){const bytes=objects.get(key);return bytes?{body:bytes,size:bytes.length,httpEtag:'"test"'}:null;}}};
globalThis.__homework={bookingDb:()=>db,isRequestOwner:async()=>owner,getAccount:async()=>user,env};
async function compile(path,replace=s=>s){const source=replace(await readFile(new URL('../'+path,import.meta.url),'utf8')).replace("import { bookingDb } from '@/lib/booking/runtime';",'const {bookingDb}=globalThis.__homework;').replace("import { isRequestOwner } from '@/lib/request-admin';",'const {isRequestOwner}=globalThis.__homework;').replace("import { getAccount } from '@/lib/auth/session';",'const {getAccount}=globalThis.__homework;').replace("import { env } from '@/lib/runtime-env';",'const {env}=globalThis.__homework;').replace("from 'zod'",'from '+JSON.stringify(import.meta.resolve('zod')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');}
const helpers=await import(await compile('lib/homework/types.ts'));assert.equal(helpers.late('2026-07-01T21:59:59Z','2026-07-01'),false);assert.equal(helpers.late('2026-07-01T22:00:00Z','2026-07-01'),true);assert.equal(helpers.late('2026-01-01T23:00:00Z','2026-01-01'),true);assert.equal(helpers.late('2026-01-02T00:00:00Z',null),false);
const access=await compile('lib/learning/access.ts'),data=await compile('lib/homework/data.ts'),files=await compile('lib/homework/files.ts',s=>s.replace("from '@/lib/learning/access'",'from '+JSON.stringify(access))),serve=await compile('lib/learning/files.ts',s=>s.replace("from './access'",'from '+JSON.stringify(access)));
const replace=s=>s.replace("from '@/lib/learning/access'",'from '+JSON.stringify(access)).replace("from '@/lib/homework/data'",'from '+JSON.stringify(data)).replace("from '@/lib/homework/files'",'from '+JSON.stringify(files)).replace("from '@/lib/learning/files'",'from '+JSON.stringify(serve));
const admin=await import(await compile('app/api/gestione/compiti/route.ts',replace)),adminFile=await import(await compile('app/api/gestione/compiti/file/route.ts',replace)),student=await import(await compile('app/api/studente/compiti/route.ts',replace)),studentFile=await import(await compile('app/api/studente/compiti/file/route.ts',replace));
const [a,b,c,plan]=Array.from({length:4},()=>crypto.randomUUID()),now=new Date().toISOString(),base='https://site.example';
for(const [id,name] of [[a,'Anna'],[b,'Bruno'],[c,'Carla']])sql.prepare("INSERT INTO students(id,name,email,notes,created_at,updated_at) VALUES(?,?,?,'PRIVATE NOTE',?,?)").run(id,name,id+'@example.test',now,now);
for(const [id,role] of [['student','student'],['parent','guardian']]){sql.prepare('INSERT INTO accounts(id,email,name,role,password_hash,must_change_password,created_at,updated_at) VALUES(?,?,?,?,?,0,?,?)').run(id,id+'@example.test',id,role,'test-only',now,now);for(const sid of role==='guardian'?[a,b]:[a])sql.prepare('INSERT INTO account_student_access(account_id,student_id,created_at) VALUES(?,?,?)').run(id,sid,now);}
sql.prepare("INSERT INTO study_plans(id,student_id,title,subject,objective,status,created_at,updated_at) VALUES(?,?,'PRIVATE DRAFT PLAN','Math','Goal','draft',?,?)").run(plan,a,now,now);
const actor=(role='student')=>user={id:role,role:role==='parent'?'guardian':'student',auth_version:0,must_change_password:0};
const req=(path,method='GET',body,origin=base)=>new Request(base+path,{method,headers:{Origin:origin,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});
const task=(sid=a,status='draft')=>({kind:'task',id:crypto.randomUUID(),studentId:sid,planId:null,version:null,title:'Limiti',subject:'Analisi 1',instructions:'Svolgere tre limiti e spiegare i passaggi',dueDate:'2026-01-01',status});
const send=p=>admin.POST(req('/api/gestione/compiti','POST',p));
const get=sid=>student.GET(req('/api/studente/compiti?studente='+sid));
function submission(taskId,id=crypto.randomUUID(),body='La mia risposta',file=null){const f=new FormData();f.set('id',id);f.set('assignmentId',taskId);f.set('body',body);if(file)f.set('file',file);return f;}
const submit=f=>student.POST(req('/api/studente/compiti','POST',f));
const pdf=()=>new File(['%PDF-1.7\nsynthetic exercise'],'esercizi.pdf',{type:'application/pdf'});
async function upload(taskId,version,file=pdf()){const f=new FormData();f.set('id',taskId);f.set('version',String(version));f.set('file',file);return adminFile.PUT(req('/api/gestione/compiti/file','PUT',f));}
const download=(kind,id,sid=a)=>studentFile.GET(req('/api/studente/compiti/file?'+new URLSearchParams({kind,id,studente:sid})));
const feedback=(id,version,status='draft',reviewStatus='revise',text='PRIVATE DRAFT FEEDBACK')=>send({kind:'feedback',id,version,status,reviewStatus,feedback:text});
try{
 assert.equal((await admin.GET(req('/api/gestione/compiti'))).status,403);assert.equal((await get(a)).status,401);assert.equal((await upload(crypto.randomUUID(),0)).status,403);
 owner=true;const input={...task(),planId:plan},other=task(b,'published');assert.equal((await admin.POST(req('/api/gestione/compiti','POST',input,'https://evil.example'))).status,403);
 for(const p of [input,other])assert.equal((await send(p)).status,200);assert.equal((await send(input)).status,200);assert.equal((await send({...input,id:crypto.randomUUID(),studentId:b})).status,403);assert.equal((await send({...task(),dueDate:'2026-02-30'})).status,400);
 const bad=new File(['<html>pretend PDF</html>'],'bad.pdf',{type:'application/pdf'});assert.equal((await upload(input.id,0,bad)).status,400);assert.equal(objects.size,0);
 assert.equal((await upload(input.id,0,new File([new Uint8Array(10*1024*1024+1)],'huge.pdf',{type:'application/pdf'}))).status,413);assert.equal((await upload(input.id,0)).status,200);assert.equal(sql.prepare('SELECT status FROM homework_assignments WHERE id=?').get(input.id).status,'draft');assert.equal(objects.size,1);
 const published={...input,version:1,status:'published'};assert.equal((await send(published)).status,200);assert.equal((await send({...published,version:1})).status,409);
 owner=false;actor();let d=await (await get(a)).json();assert.equal(d.assignments.length,1);assert.equal(d.assignments[0].plan_title,null);assert.equal(d.canSubmit,true);assert.equal((await get(b)).status,403);assert.equal((await download('task',other.id)).status,404);assert.equal((await download('task',input.id)).status,200);
 assert.equal((await submit(submission(input.id,crypto.randomUUID(),''))).status,400);assert.equal((await student.POST(req('/api/studente/compiti','POST',submission(input.id),'https://evil.example'))).status,403);
 actor('parent');assert.equal((await (await get(b)).json()).canSubmit,false);assert.equal((await submit(submission(input.id))).status,403);actor();
 const firstId=crypto.randomUUID(),form=()=>submission(input.id,firstId,'Passaggi di Anna',pdf());assert.equal((await submit(form())).status,200);assert.equal((await submit(form())).status,200);assert.equal(objects.size,2);assert.equal(sql.prepare('SELECT count(*) n FROM homework_submissions').get().n,1);assert.equal((await submit(submission(input.id,firstId,'Changed body',pdf()))).status,409);assert.equal((await submit(submission(input.id,crypto.randomUUID(),'Other attempt',pdf()))).status,409);assert.equal(objects.size,2);
 let r=await download('submission',firstId);assert.equal(r.status,200);assert.equal(await r.text(),'%PDF-1.7\nsynthetic exercise');assert.ok(r.headers.get('Content-Disposition').startsWith('attachment'));assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');
 owner=true;assert.equal((await send({...input,version:2,instructions:'Rewritten instructions',status:'published'})).status,409);assert.equal((await upload(input.id,2)).status,409);assert.equal(objects.size,2);
 assert.equal((await feedback(firstId,0)).status,200);owner=false;d=await (await get(a)).json();assert.equal(d.submissions[0].feedback,'');assert.equal(d.submissions[0].review_status,'pending');assert.ok(!JSON.stringify(d).includes('PRIVATE DRAFT'));assert.equal((await submit(submission(input.id))).status,409);
 owner=true;assert.equal((await feedback(firstId,1,'published','revise','Rivedi la fattorizzazione')).status,200);owner=false;
 const secondId=crypto.randomUUID(),textOnly=submission(input.id,secondId,'Secondo tentativo');textOnly.set('file','');assert.equal((await submit(textOnly)).status,200);d=await (await get(a)).json();assert.equal(d.submissions.length,2);assert.equal(d.submissions[0].attempt,2);assert.equal(d.submissions[1].feedback,'Rivedi la fattorizzazione');
 owner=true;assert.equal((await feedback(firstId,2,'published')).status,409);assert.equal((await feedback(secondId,0,'published','accepted','Passaggi corretti')).status,200);assert.equal((await feedback(secondId,0,'published','revise','Stale overwrite')).status,409);owner=false;assert.equal((await submit(submission(input.id))).status,409);
 const encoded=JSON.stringify(await (await get(a)).json());for(const secret of ['PRIVATE NOTE','object_key','content_hash','submitted_by','PRIVATE DRAFT PLAN'])assert.ok(!encoded.includes(secret),secret);
 actor('parent');assert.equal((await download('submission',firstId)).status,200);assert.equal((await download('submission',firstId,b)).status,404);actor();
 sql.prepare("UPDATE account_student_access SET status='revoked' WHERE account_id='student' AND student_id=?").run(a);assert.equal((await get(a)).status,403);assert.equal((await download('submission',firstId)).status,403);sql.prepare("UPDATE account_student_access SET status='active' WHERE account_id='student' AND student_id=?").run(a);
 owner=true;assert.equal((await send({...input,version:2,status:'archived'})).status,200);owner=false;assert.equal((await (await get(a)).json()).assignments.length,0);assert.equal((await download('submission',firstId)).status,404);owner=true;assert.equal((await adminFile.GET(req('/api/gestione/compiti/file?kind=submission&id='+firstId))).status,200);
 const raceTask=task(a,'published');assert.equal((await send(raceTask)).status,200);owner=false;beforePut=()=>sql.prepare("UPDATE homework_assignments SET status='draft' WHERE id=?").run(raceTask.id);assert.equal((await submit(submission(raceTask.id,crypto.randomUUID(),'Race',pdf()))).status,409);assert.equal(objects.size,2);owner=true;assert.equal((await send({...raceTask,version:0,status:'published'})).status,200);owner=false;
 const uncertainId=crypto.randomUUID();failAfterWrite=true;assert.equal((await submit(submission(raceTask.id,uncertainId,'Received despite timeout',pdf()))).status,503);assert.equal(objects.size,3);assert.equal((await submit(submission(raceTask.id,uncertainId,'Received despite timeout',pdf()))).status,200);assert.equal(objects.size,3);
 owner=true;const lockedRace=task(a,'published');assert.equal((await send(lockedRace)).status,200);beforeWrite=()=>sql.prepare("INSERT INTO homework_submissions(id,assignment_id,submitted_by,attempt,content_hash,created_at) VALUES(?,?,'student',1,'test',?)").run(crypto.randomUUID(),lockedRace.id,now);assert.equal((await send({...lockedRace,version:0,instructions:'Concurrent rewrite'})).status,409);
 owner=true;const capped=task(a,'published');assert.equal((await send(capped)).status,200);for(let i=1;i<=20;i++)sql.prepare("INSERT INTO homework_submissions(id,assignment_id,submitted_by,attempt,content_hash,feedback_status,review_status,created_at) VALUES(?,?,'student',?,'test','published','revise',?)").run(crypto.randomUUID(),capped.id,i,now);owner=false;assert.equal((await submit(submission(capped.id))).status,409);
 owner=true;const revoked=task(a,'published');assert.equal((await send(revoked)).status,200);owner=false;beforePut=()=>sql.prepare("UPDATE accounts SET auth_version=auth_version+1 WHERE id='student'").run();assert.equal((await submit(submission(revoked.id,crypto.randomUUID(),'Revoked during upload',pdf()))).status,409);assert.equal(objects.size,3);sql.prepare("UPDATE accounts SET auth_version=0 WHERE id='student'").run();owner=true;
 sql.prepare("UPDATE students SET status='archived' WHERE id=?").run(a);assert.equal((await send({...raceTask,version:1,status:'archived'})).status,409);owner=false;assert.equal((await get(a)).status,403);assert.equal((await download('submission',uncertainId)).status,403);owner=true;assert.ok((await (await admin.GET(req('/api/gestione/compiti?studente='+a))).json()).submissions.length>0);
 console.log('PASS: private assignments/files, role isolation, parent read-only, draft feedback protection, content lock, late deliveries, immutable attempts, revision/acceptance, CAS conflicts, archive/revocation, upload signatures/limits, concurrent guards and recovery after uncertain database commit.');
}finally{delete globalThis.__homework;sql.close();}
