import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));
let owner=false,unavailable=false,loseWrite=false;
const db={prepare(query){if(unavailable)throw Error('Unavailable');const bind=(...args)=>({query,args,async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const changes=Number(sql.prepare(query).run(...args).changes);if(loseWrite){loseWrite=false;throw Error('Lost acknowledgement');}return {meta:{changes}};}});return {bind,...bind()};},async batch(statements){sql.exec('BEGIN');try{const r=statements.map(s=>/RETURNING/.test(s.query)?{results:sql.prepare(s.query).all(...s.args)}:{results:[],meta:{changes:Number(sql.prepare(s.query).run(...s.args).changes)}});sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
globalThis.__launch={bookingDb:()=>db,isRequestOwner:async()=>owner,getAccount:async()=>null,env:{DB:db},paymentConfig:()=>({ready:true}),stripe:()=>{throw Error('Must not contact Stripe');}};
async function compile(path,replace=s=>s){const source=replace(await readFile(new URL('../'+path,import.meta.url),'utf8')).replace(/import \{\s*bookingDb\s*\} from '@\/lib\/booking\/runtime';/g,'const {bookingDb}=globalThis.__launch;').replace(/import \{\s*isRequestOwner\s*\} from '@\/lib\/request-admin';/g,'const {isRequestOwner}=globalThis.__launch;').replace(/import \{\s*getAccount\s*\} from '@\/lib\/auth\/session';/g,'const {getAccount}=globalThis.__launch;').replace(/import \{\s*env\s*\} from '@\/lib\/runtime-env';/g,'const {env}=globalThis.__launch;').replace(/import \{\s*validateReferral\s*\} from '@\/lib\/referrals\/server';/g,'const validateReferral=async()=>{};').replace("from 'zod'",'from '+JSON.stringify(import.meta.resolve('zod')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');}
const limitURL=await compile('lib/public-request-limit.ts'),store=await compile('lib/request-store.ts'),catalog=await compile('lib/catalog.ts'),dates=await compile('lib/lesson-plan.ts'),consult=await compile('lib/consultations.ts',s=>s.replace("from '@/lib/lesson-plan'",'from '+JSON.stringify(dates))),access=await compile('lib/learning/access.ts'),exportsURL=await compile('lib/management/export.ts');
const recurrenceURL=await compile('lib/consultation-recurrence.ts',s=>s.replace("from '@/lib/consultations'",'from '+JSON.stringify(consult)));
const link=s=>s.replace("from '@/lib/consultation-recurrence'",'from '+JSON.stringify(recurrenceURL)).replace("from '@/lib/public-request-limit'",'from '+JSON.stringify(limitURL)).replace("from '@/lib/request-store'",'from '+JSON.stringify(store)).replace("from '@/lib/catalog'",'from '+JSON.stringify(catalog)).replace("from '@/lib/consultations'",'from '+JSON.stringify(consult)).replace("from '@/lib/learning/access'",'from '+JSON.stringify(access)).replace("from '@/lib/management/export'",'from '+JSON.stringify(exportsURL));
const contact=await import(await compile('app/api/contatti/route.ts',link)),requests=await import(await compile('app/api/requests/route.ts',link)),meeting=await import(await compile('app/api/incontri/route.ts',link)),dataExport=await import(await compile('app/api/gestione/esportazione/route.ts',link));
const checkout=await import(await compile('app/api/booking/checkout/route.ts',s=>link(s).replace("import { bookingDb,paymentConfig,stripe } from '@/lib/booking/runtime';",'const {bookingDb,paymentConfig,stripe}=globalThis.__launch;').replace("import { resolveStudent } from '@/lib/students/resolve';",'const resolveStudent=async()=>{throw Error("Must not create student");};').replace("import { newNoticeStatement,dispatchAppointmentNotices } from '@/lib/notifications/appointments';",'const newNoticeStatement=()=>{},dispatchAppointmentNotices=()=>{};')));
const {limitPublicRequest}=await import(limitURL),{exportTables}=await import(exportsURL),base='https://site.example';
const req=(path,p,ip,origin=base)=>new Request(base+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...(ip?{'CF-Connecting-IP':ip}:{})},body:JSON.stringify(p)});
const body=(email='qa@example.invalid')=>({id:crypto.randomUUID(),name:'QA Genitore',email,subject:'Matematica',message:'Test',consent:true,website:''});
const full=email=>({...body(email),kind:'pre-registration',details:{studentType:'Università',institution:'',year:'',teacher:'',program:'Analisi 1',goal:'',deadline:'',availability:'Lunedì',mode:'Online',level:'',groupSize:'',companion:false,phone:''},assessment:null});
const reset=()=>sql.exec('DELETE FROM public_request_limits');
const saved=body(),oldNow=Date.now,now=oldNow();
try{
 Date.now=()=>now;
 // Shared email allowance across all forms; case normalization and exact retries.
 assert.equal((await contact.POST(req('/api/contatti',saved))).status,201);
 for(let i=0;i<4;i++)assert.equal((await requests.POST(req('/api/requests',full('QA@EXAMPLE.INVALID')))).status,201);
 let r=await contact.POST(req('/api/contatti',body()));assert.equal(r.status,429);assert.ok(Number(r.headers.get('Retry-After'))>0);assert.equal(r.headers.get('Cache-Control'),'no-store');
 assert.equal((await contact.POST(req('/api/contatti',saved))).status,200);assert.equal((await contact.POST(req('/api/contatti',{...saved,message:'changed'}))).status,409);
 assert.equal((await meeting.POST(req('/api/incontri',{...body(),slotId:crypto.randomUUID(),phone:'',studentType:'Superiori',mode:'Online'}))).status,429);
 assert.equal((await checkout.POST(req('/api/booking/checkout',{slotId:crypto.randomUUID(),name:'QA',email:'qa@example.invalid',subject:'Matematica',consent:true}))).status,429);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM students').get().n,0);assert.equal(sql.prepare('SELECT COUNT(*) n FROM bookings').get().n,0);
 const retry=full('retry@example.invalid');loseWrite=true;assert.equal((await requests.POST(req('/api/requests',retry))).status,200);assert.equal((await requests.POST(req('/api/requests',retry))).status,200);assert.equal((await requests.POST(req('/api/requests',{...retry,subject:'Changed'}))).status,409);assert.equal((await requests.POST(req('/api/requests',full(),'',''))).status,403);
 // Atomic counters admit only five concurrent new submissions.
 reset();const concurrent=await Promise.all(Array.from({length:12},()=>contact.POST(req('/api/contatti',body('race@example.invalid')))));assert.equal(concurrent.filter(r=>r.status===201).length,5);assert.equal(concurrent.filter(r=>r.status===429).length,7);
 reset();for(let i=0;i<20;i++)assert.equal(await limitPublicRequest(req('/api/contatti',{},'203.0.113.4'),'ip-'+i+'@example.invalid'),null);assert.equal((await limitPublicRequest(req('/api/contatti',{},'203.0.113.4'),'other@example.invalid')).status,429);
 reset();for(let i=0;i<100;i++)assert.equal(await limitPublicRequest(req('/api/contatti',{}),'total-'+i+'@example.invalid'),null);assert.equal((await limitPublicRequest(req('/api/contatti',{}),'extra@example.invalid')).status,429);const bucketRows=sql.prepare('SELECT COUNT(*) n FROM public_request_limits').get().n;for(let i=0;i<20;i++)assert.equal((await limitPublicRequest(req('/api/contatti',{}),'overflow-'+i+'@example.invalid')).status,429);assert.equal(sql.prepare('SELECT COUNT(*) n FROM public_request_limits').get().n,bucketRows);
 assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM public_request_limits').all()).includes('@'));assert.ok(!JSON.stringify(sql.prepare('SELECT * FROM public_request_limits').all()).includes('203.0.113.4'));
 Date.now=()=>now+3600000;assert.equal(await limitPublicRequest(req('/api/contatti',{}),'qa@example.invalid'),null);assert.equal(sql.prepare('SELECT COUNT(*) n FROM public_request_limits WHERE expires_at<=?').get(Date.now()).n,0);
 unavailable=true;assert.equal((await contact.POST(req('/api/contatti',body('outage@example.invalid')))).status,503);unavailable=false;
 // Owner-only downloadable operational data, no auth credentials or sensitive notification links.
 assert.equal((await dataExport.GET()).status,403);assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{}))).status,403);owner=true;assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{},'', 'https://evil.example'))).status,403);
 const stamp=new Date(now).toISOString(),student=crypto.randomUUID(),course=crypto.randomUUID(),module=crypto.randomUUID(),material=crypto.randomUUID(),account=crypto.randomUUID();
 sql.prepare("INSERT INTO students(id,name,email,notes,created_at,updated_at) VALUES(?,'QA Student','student@example.invalid','Keep this operational note',?,?)").run(student,stamp,stamp);
 sql.prepare("INSERT INTO accounts(id,name,email,role,password_hash,created_at,updated_at) VALUES(?,'QA','account@example.invalid','student','PASSWORD SECRET',?,?)").run(account,stamp,stamp);sql.prepare('INSERT INTO account_sessions(token_hash,account_id,auth_version,expires_at,created_at) VALUES(?,?,0,?,?)').run('SESSION SECRET',account,now+1000,now);
 sql.prepare("INSERT INTO courses(id,title,subject,created_at,updated_at) VALUES(?,'Analisi','Matematica',?,?)").run(course,stamp,stamp);sql.prepare("INSERT INTO course_modules(id,course_id,title) VALUES(?,?,'Equazioni')").run(module,course);sql.prepare("INSERT INTO course_materials(id,module_id,title,kind,object_key,filename,mime,size,created_at) VALUES(?,?,'Esercizi','file','materials/fixture.pdf','esercizi.pdf','application/pdf',100,?)").run(material,module,stamp);
 sql.prepare("INSERT INTO notifications(id,event_key,entity_type,entity_id,kind,recipient,subject,body,payload,status,created_at,updated_at) VALUES('n','event','test','x','test','email@example.invalid','Promemoria','PAYMENT SECRET','PAYLOAD SECRET','preview',?,?)").run(stamp,stamp);
 r=await dataExport.GET();assert.equal(r.headers.get('Cache-Control'),'private, no-store');const overview=await r.json();assert.ok(overview.counts.some(row=>row.name==='students'&&row.count===1));
 r=await dataExport.POST(req('/api/gestione/esportazione',{}));assert.equal(r.status,200,await r.clone().text());assert.match(r.headers.get('Content-Disposition'),/attachment.*\.json/);assert.equal(r.headers.get('Vary'),'Cookie');let d=await r.json();assert.equal(d.version,1);assert.equal(d.tables.students[0].notes,'Keep this operational note');assert.equal(d.attachments.length,1);assert.equal(d.attachments[0].filename,'esercizi.pdf');assert.deepEqual(Object.keys(d.tables).sort(),Object.keys(exportTables).sort());assert.equal(d.tables.account_student_access.length,0);for(const [table,rows] of Object.entries(d.tables))for(const row of rows)assert.deepEqual(Object.keys(row).sort(),exportTables[table].split(' ').sort());assert.equal(d.counts.requests,sql.prepare('SELECT COUNT(*) n FROM requests').get().n);
 for(const secret of ['PASSWORD SECRET','SESSION SECRET','PAYMENT SECRET','PAYLOAD SECRET','password_hash','token_hash','access_token','stripe_session'])assert.ok(!JSON.stringify(d.tables).includes(secret),secret);
 // No silently partial download when row or byte budgets are exceeded.
 sql.exec("WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<20001) INSERT INTO tutor_templates(id,name,kind,content,created_at,updated_at) SELECT 'limit-'||n,'Test','message','{}','test','test' FROM seq");r=await dataExport.POST(req('/api/gestione/esportazione',{}));assert.equal(r.status,413);assert.equal(r.headers.get('Content-Disposition'),null);sql.exec('DELETE FROM tutor_templates');
 sql.prepare("INSERT INTO tutor_templates(id,name,kind,content,created_at,updated_at) VALUES('big','Test','message',?,'test','test')").run('x'.repeat(11*1024*1024));assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{}))).status,413);sql.exec('DELETE FROM tutor_templates');sql.prepare("INSERT INTO tutor_templates(id,name,kind,content,created_at,updated_at) VALUES('table-budget','Test','message',?,'test','test')").run('x'.repeat(1800000));assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{}))).status,413);sql.exec('DELETE FROM tutor_templates');
 unavailable=true;assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{}))).status,503);unavailable=false;assert.equal((await dataExport.POST(req('/api/gestione/esportazione',{}))).status,200);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM notifications').get().n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lesson_payments').get().n,0);
 console.log('PASS: persistent atomic public limits across four forms, hashed counters/expiry, exact retries and collisions, concurrent cap, IP/global caps, fail closed; owner-only consistent data export, explicit column allowlist, attachment manifest, no credentials/message tokens, complete-or-error budgets and recovery; no emails or payments.');
}finally{Date.now=oldNow;sql.close();delete globalThis.__launch;}
