import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));
let owner=false,loseRun=false,beforeRun=null;
const db={prepare(query){const bind=(...args)=>({async first(){return sql.prepare(query).get(...args)||null;},async all(){try{return {results:sql.prepare(query).all(...args)};}catch(e){console.error('Failed query:',query,e.message);throw e;}},async run(){if(beforeRun){const f=beforeRun;beforeRun=null;f();}const r=sql.prepare(query).run(...args);if(loseRun){loseRun=false;throw Error('Lost acknowledgement');}return {meta:{changes:Number(r.changes)}};}});return {bind,...bind()};}};
globalThis.__ops={bookingDb:()=>db,isRequestOwner:async()=>owner,getAccount:async()=>null};
async function compile(path,replace=s=>s){const source=replace(await readFile(new URL('../'+path,import.meta.url),'utf8')).replace(/import \{\s*bookingDb\s*\} from '@\/lib\/booking\/runtime';/g,'const {bookingDb}=globalThis.__ops;').replace(/import \{\s*isRequestOwner\s*\} from '@\/lib\/request-admin';/g,'const {isRequestOwner}=globalThis.__ops;').replace(/import \{\s*getAccount\s*\} from '@\/lib\/auth\/session';/g,'const {getAccount}=globalThis.__ops;').replace("from 'zod'",'from '+JSON.stringify(import.meta.resolve('zod')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');}
const access=await compile('lib/learning/access.ts'),dates=await compile('lib/lesson-plan.ts'),ops=await compile('lib/management/operations.ts',s=>s.replace("from '@/lib/lesson-plan'",'from '+JSON.stringify(dates))),templates=await compile('lib/management/templates.ts');
const replace=s=>s.replace("from '@/lib/learning/access'",'from '+JSON.stringify(access)).replace("from '@/lib/management/operations'",'from '+JSON.stringify(ops)).replace("from '@/lib/management/templates'",'from '+JSON.stringify(templates));
const requests=await import(await compile('app/api/gestione/richieste/route.ts',replace)),follow=await import(await compile('app/api/gestione/richieste/seguito/route.ts',replace)),models=await import(await compile('app/api/gestione/modelli/route.ts',replace)),bulk=await import(await compile('app/api/gestione/compiti/assegnazione/route.ts',replace)),today=await import(await compile('app/api/gestione/oggi/route.ts',replace));
const helpers=await import(ops),modelHelpers=await import(templates),base='https://site.example',req=(path,method='GET',body,origin=base)=>new Request(base+path,{method,headers:{Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),now=new Date().toISOString();
const [a,b,c]=Array.from({length:3},()=>crypto.randomUUID());for(const [id,name] of [[a,'Anna'],[b,'Bruno'],[c,'Carla']])sql.prepare('INSERT INTO students(id,name,email,notes,created_at,updated_at) VALUES(?,?,?,\'PRIVATE STUDENT NOTE\',?,?)').run(id,name,id+'@example.invalid',now,now);
function request(name,subject='Matematica',status='new',created=now){const id=crypto.randomUUID();sql.prepare("INSERT INTO requests(id,kind,name,email,subject,details,status,created_at,consent_version) VALUES(?,'contact',?,?,?,'{}',?,?,'test')").run(id,name,id+'@example.invalid',subject,status,created);return id;}
const first=request('Anna'),scheduled=request('Bruno','Informatica','contacted'),closed=request('Chiusa','Analisi','closed');
const get=(query='')=>requests.GET(req('/api/gestione/richieste'+query));
const followInput={id:first,version:null,lastContactAt:now,nextAction:'Concordare giorno',nextActionDate:helpers.romeDay(),source:'letuelezioni',notes:'PRIVATE FOLLOWUP'};
async function patch(p,status=200){const r=await follow.PATCH(req('/api/gestione/richieste/seguito','PATCH',p));assert.equal(r.status,status,await r.clone().text());return r;}
const task=()=>({recipients:[a,b].map(studentId=>({id:crypto.randomUUID(),studentId})),title:'Equazioni',subject:'Matematica',instructions:'Mostra tutti i passaggi',dueDate:'2026-10-20',status:'draft'});
const assign=p=>bulk.POST(req('/api/gestione/compiti/assegnazione','POST',p));
const model={id:crypto.randomUUID(),version:null,kind:'message',name:'Primo contatto',content:{body:'Ciao {nome}, parliamo di {materia}.'},status:'active'};
const saveModel=p=>models.POST(req('/api/gestione/modelli','POST',p));
try{
 for(const r of [await get(),await models.GET(req('/api/gestione/modelli')),await today.GET(),await assign(task()),await saveModel(model),await follow.PATCH(req('/api/gestione/richieste/seguito','PATCH',followInput))])assert.equal(r.status,403);
 owner=true;assert.equal((await follow.PATCH(req('/api/gestione/richieste/seguito','PATCH',followInput,'https://evil.example'))).status,403);assert.equal((await models.POST(req('/api/gestione/modelli','POST',model,'https://evil.example'))).status,403);assert.equal((await bulk.POST(req('/api/gestione/compiti/assegnazione','POST',task(),'https://evil.example'))).status,403);
 loseRun=true;await patch(followInput,503);await patch(followInput);await patch(followInput);assert.equal(sql.prepare('SELECT version FROM request_followups WHERE request_id=?').get(first).version,0);
 await patch({...followInput,version:0,nextAction:'Richiamare'});await patch({...followInput,version:0,nextAction:'Overwrite'},409);
 await patch({...followInput,version:1,nextAction:'',nextActionDate:null});await patch({...followInput,version:2,nextActionDate:'2026-02-30'},400);await patch({...followInput,version:2,source:'evil'},400);await patch({...followInput,version:2,lastContactAt:new Date(Date.now()+86400000).toISOString()},400);await patch({...followInput,id:crypto.randomUUID()},404);
 await patch({...followInput,version:2});await patch({...followInput,id:scheduled,lastContactAt:null,nextActionDate:'2099-01-01'});await patch({...followInput,id:closed});
 for(let i=0;i<205;i++)request('Recent '+i,'Informatica','closed');
 let r=await get();assert.equal((await r.json()).truncated,true);r=await get('?q=Anna&status=new&kind=contact&source=letuelezioni');let d=await r.json();assert.equal(d.requests.length,1);assert.equal(d.requests[0].followup_notes,'PRIVATE FOLLOWUP');assert.equal(r.headers.get('Cache-Control'),'private, no-store');
 assert.equal((await (await get('?q=%25')).json()).requests.length,0);const wildcard=request('Literal_%');assert.equal((await (await get('?q=_%25')).json()).requests[0].id,wildcard);assert.equal((await get('?source=constructor')).status,400);assert.equal((await get('?id=not-uuid')).status,400);assert.equal((await get('?q='+encodeURIComponent('x'.repeat(101)))).status,400);assert.equal((await (await get('?id='+scheduled)).json()).requests[0].id,scheduled);
 loseRun=true;assert.equal((await saveModel(model)).status,503);assert.equal((await saveModel(model)).status,200);assert.equal(sql.prepare('SELECT COUNT(*) n FROM tutor_templates').get().n,1);assert.equal((await saveModel({...model,version:0,name:'Primo messaggio'})).status,200);assert.equal((await saveModel({...model,version:0,name:'Stale'})).status,409);assert.equal((await saveModel({...model,id:crypto.randomUUID(),content:{body:'Hello',studentId:a}})).status,400);assert.equal((await saveModel({...model,version:1,status:'archived',name:'Primo messaggio'})).status,200);assert.equal((await (await models.GET(req('/api/gestione/modelli?tipo=message'))).json()).templates.length,0);assert.equal((await (await models.GET(req('/api/gestione/modelli'))).json()).templates.length,1);assert.equal(modelHelpers.messageText(model.content.body,'Anna','Matematica'),'Ciao Anna, parliamo di Matematica.');
 const batch=task();loseRun=true;assert.equal((await assign(batch)).status,503);assert.equal((await assign(batch)).status,200);assert.equal((await assign(batch)).status,200);assert.equal(sql.prepare('SELECT count(*) n FROM homework_assignments').get().n,2);assert.equal((await assign({...batch,instructions:'Different'})).status,409);assert.equal((await assign({...task(),recipients:[{id:crypto.randomUUID(),studentId:a},{id:crypto.randomUUID(),studentId:a}]})).status,400);
 const invalid=task();invalid.recipients[1].studentId=crypto.randomUUID();assert.equal((await assign(invalid)).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM homework_assignments').get().n,2);
 const raced=task();beforeRun=()=>sql.prepare("UPDATE students SET status='archived' WHERE id=?").run(b);assert.equal((await assign(raced)).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM homework_assignments').get().n,2);sql.prepare("UPDATE students SET status='active' WHERE id=?").run(b);
 const conflicting=task();conflicting.recipients[0].id=batch.recipients[1].id;assert.equal((await assign(conflicting)).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM homework_assignments').get().n,2);sql.prepare('UPDATE homework_assignments SET version=1 WHERE id=?').run(batch.recipients[0].id);assert.equal((await assign(batch)).status,409);

 for(const kind of ['task','plan','summary']){const content=Object.fromEntries(modelHelpers.templateFields[kind].map(f=>[f.name,f.required?'Testo di esempio':'']));assert.equal((await saveModel({...model,id:crypto.randomUUID(),version:null,kind,content})).status,200);assert.ok(Object.keys(modelHelpers.templateValues(kind,JSON.stringify(content))).length);assert.equal((await saveModel({...model,id:crypto.randomUUID(),kind,content:{...content,studentId:a}})).status,400);}
 const archivedCopies=task();archivedCopies.recipients[1].studentId=c;sql.prepare("UPDATE students SET status='archived' WHERE id=?").run(c);assert.equal((await assign(archivedCopies)).status,409);assert.equal(sql.prepare('SELECT COUNT(*) n FROM homework_assignments').get().n,2);
 // Today: Rome boundaries, confirmed events, latest visible pending correction, manual saldo only.
 for(const [date,hours] of [['2026-03-29',23],['2026-10-25',25],['2026-10-07',24]]){const w=helpers.dayWindow(date);assert.equal((Date.parse(w.end)-Date.parse(w.start))/3600000,hours);}
 assert.equal(helpers.romeDay(new Date('2026-10-06T22:30:00Z')),'2026-10-07');
 const day=helpers.romeDay(),w=helpers.dayWindow(day),start=new Date(Date.parse(w.start)+10*3600000).toISOString(),end=new Date(Date.parse(start)+3300000).toISOString();
 for(const status of ['planned','cancelled']){const id=crypto.randomUUID();sql.prepare("INSERT INTO scheduled_lessons(id,series_id,name,email,subject,starts_at,ends_at,mode,notes,status,created_at,payment_method) VALUES(?,?,'Anna','anna@example.invalid','Matematica',?,?,'Online','PRIVATE LESSON NOTE',?,?,'cash')").run(id,id,start,end,status,now);sql.prepare("INSERT INTO lesson_payments(id,lesson_id,access_token,name,email,amount,status,created_at) VALUES(?,?,'SECRET TOKEN','Anna','a@example.invalid',2000,'awaiting',?)").run(crypto.randomUUID(),id,now);}
 const online=crypto.randomUUID();sql.prepare("INSERT INTO scheduled_lessons(id,series_id,name,email,subject,starts_at,ends_at,mode,notes,status,created_at,payment_method) VALUES(?,?,'Bruno','b@example.invalid','Informatica',?,?,'Online','', 'planned',?,'online')").run(online,online,new Date(Date.parse(start)+7200000).toISOString(),new Date(Date.parse(end)+7200000).toISOString(),now);sql.prepare("INSERT INTO lesson_payments(id,lesson_id,access_token,name,email,amount,status,created_at) VALUES(?,?,'SECRET TOKEN','Bruno','b@example.invalid',2000,'awaiting',?)").run(crypto.randomUUID(),online,now);
 const published=task();published.status='published';assert.equal((await assign(published)).status,200);const assignment=published.recipients[0].id;for(const attempt of [1,2])sql.prepare("INSERT INTO homework_submissions(id,assignment_id,submitted_by,attempt,body,content_hash,created_at) VALUES(?,?,'PRIVATE ACCOUNT',?,'PRIVATE BODY','HASH',?)").run(crypto.randomUUID(),assignment,attempt,now);

 const slot=crypto.randomUUID(),booking=crypto.randomUUID(),bstart=new Date(Date.parse(w.start)+14*3600000).toISOString(),bend=new Date(Date.parse(bstart)+3300000).toISOString();sql.prepare("INSERT INTO booking_slots(id,starts_at,ends_at,mode) VALUES(?,?,?,'Lodi')").run(slot,bstart,bend);sql.prepare("INSERT INTO bookings(id,slot_id,access_token,name,email,subject,status,created_at) VALUES(?,?,'BOOKING SECRET','Carla','c@example.invalid','Informatica','confirmed',?)").run(booking,slot,now);
 const cslot=crypto.randomUUID(),consultation=crypto.randomUUID(),cstart=new Date(Date.parse(w.start)+16*3600000).toISOString(),cend=new Date(Date.parse(cstart)+900000).toISOString();sql.prepare("INSERT INTO consultation_slots(id,starts_at,ends_at,mode,created_at) VALUES(?,?,?,'Online',?)").run(cslot,cstart,cend,now);sql.prepare("INSERT INTO consultations(id,slot_id,request_id,name,email,subject,student_type,mode,starts_at,ends_at,payload_hash,created_at) VALUES(?,?,?,'Nuovo contatto','n@example.invalid','Matematica','Superiori','Online',?,?,'HASH',?)").run(consultation,cslot,first,cstart,cend,now);
 const packageId=crypto.randomUUID();sql.prepare("INSERT INTO lesson_packages(id,student_id,amount,units,unit_amount,payment_method,created_at) VALUES(?,?,9500,5,1900,'cash',?)").run(packageId,a,now);
 d=await (await today.GET()).json();assert.equal(d.appointments.length,4);assert.deepEqual(new Set(d.appointments.map(a=>a.kind)),new Set(['lesson','booking','consultation']));assert.equal(d.corrections.length,1);assert.equal(d.saldos.length,2);assert.ok(d.saldos.some(s=>s.kind==='package'&&s.amount===9500));assert.ok(d.followups.some(r=>r.id===first));assert.ok(!d.followups.some(r=>r.id===scheduled||r.id===closed));for(const secret of ['SECRET TOKEN','PRIVATE LESSON NOTE','PRIVATE FOLLOWUP','PRIVATE BODY','PRIVATE ACCOUNT','example.invalid'])assert.ok(!JSON.stringify(d).includes(secret),secret);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM notifications').get().n,0);
 console.log('PASS: owner access, CSRF, server search beyond 200, literal wildcards, provenance, private followups with CAS/retry, template lifecycle, atomic personal assignments, no partial batch/duplicates, Rome DST and Today isolation from cancelled/test payments/private bodies.');
}finally{delete globalThis.__ops;sql.close();}
