import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));
let owner=false,user=null,loseRun=false;
const db={prepare(query){const bind=(...args)=>({async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const r=sql.prepare(query).run(...args);if(loseRun){loseRun=false;throw Error('Lost response');}return {meta:{changes:Number(r.changes)}};}});return {bind,...bind()};}};
globalThis.__packages={bookingDb:()=>db,isRequestOwner:async()=>owner,getAccount:async()=>user};
async function compile(file,replace=s=>s){const s=replace(await readFile(new URL('../'+file,import.meta.url),'utf8')).replace(/import \{ bookingDb \} from '@\/lib\/booking\/runtime';/g,'const {bookingDb}=globalThis.__packages;').replace(/import \{ isRequestOwner \} from '@\/lib\/request-admin';/g,'const {isRequestOwner}=globalThis.__packages;').replace(/import \{ getAccount \} from '@\/lib\/auth\/session';/g,'const {getAccount}=globalThis.__packages;').replace("from 'zod'",'from '+JSON.stringify(import.meta.resolve('zod')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');}
const access=await compile('lib/learning/access.ts'),server=await compile('lib/packages/server.ts');
const replace=s=>s.replace("from '@/lib/learning/access'",'from '+JSON.stringify(access)).replace("from '@/lib/packages/server'",'from '+JSON.stringify(server));
const admin=await import(await compile('app/api/gestione/pacchetti/route.ts',replace)),student=await import(await compile('app/api/studente/pacchetti/route.ts',replace)),lessons=await import(await compile('app/api/studente/route.ts',replace));
const base='https://site.example',req=(path,body,origin=base)=>new Request(base+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
async function post(body,status=200){const r=await admin.POST(req('/api/gestione/pacchetti',body));assert.equal(r.status,status,await r.clone().text());return r;}
const now=new Date().toISOString(),[a,b,c]=Array.from({length:3},()=>crypto.randomUUID());
for(const [id,name] of [[a,'Anna'],[b,'Bruno'],[c,'PRIVATE OTHER']])sql.prepare("INSERT INTO students(id,name,email,notes,created_at,updated_at) VALUES(?,?,'SECRET EMAIL','SECRET NOTES',?,?)").run(id,name,now,now);
sql.prepare("INSERT INTO accounts(id,email,name,role,password_hash,must_change_password,created_at,updated_at) VALUES('parent','SECRET ACCOUNT','Parent','guardian','test',0,?,?)").run(now,now);for(const sid of [a,b])sql.prepare("INSERT INTO account_student_access(account_id,student_id,created_at) VALUES('parent',?,?)").run(sid,now);
let offset=0;
function lesson(ids,{future=true,method='cash',amount=ids.length===1?2000:1500,status='awaiting'}={}){const id=crypto.randomUUID(),start=new Date(Date.now()+(future?20:-20)*86400000+offset++*7200000).toISOString();sql.prepare("INSERT INTO scheduled_lessons(id,series_id,name,email,subject,starts_at,ends_at,mode,notes,created_at,payment_method,payment_status,student_id) VALUES(?,?,'PRIVATE NAME','SECRET EMAIL','Matematica',?,?,'Online','PRIVATE NOTES',?,?,?,?)").run(id,id,start,new Date(Date.parse(start)+3300000).toISOString(),now,method,status,ids.length===1?ids[0]:null);const payments={};for(const sid of ids){const pid=crypto.randomUUID();payments[sid]=pid;sql.prepare("INSERT INTO lesson_payments(id,lesson_id,access_token,student_id,name,email,amount,status,created_at) VALUES(?,?,'SECRET TOKEN',?,'SECRET NAME','SECRET EMAIL',?,?,?)").run(pid,id,sid,amount,status,now);}return {id,payment:payments[ids[0]]};}
const create=(studentId=a,method='cash')=>({kind:'create',id:crypto.randomUUID(),studentId,method});const cover=(pkg,l)=>({kind:'cover',id:crypto.randomUUID(),packageId:pkg.id,paymentId:l.payment});
try{
 assert.equal((await admin.GET(req('/api/gestione/pacchetti'))).status,403);assert.equal((await student.GET(req('/api/studente/pacchetti'))).status,401);owner=true;
 assert.equal((await admin.POST(req('/api/gestione/pacchetti',create(),'https://evil.example'))).status,403);
 const pkg=create();loseRun=true;await post(pkg,503);await post(pkg);assert.equal(sql.prepare('SELECT COUNT(*) n FROM lesson_packages').get().n,1);await post({...pkg,studentId:b},409);
 const target=lesson([a]);await post(cover(pkg,target),409);await post({kind:'activate',id:pkg.id,confirmed:false},400);await post({kind:'activate',id:pkg.id,confirmed:true});await post({kind:'activate',id:pkg.id,confirmed:true});
 for(const l of [lesson([b]),lesson([a,b]),lesson([a],{future:false}),lesson([a],{method:'online'}),lesson([a],{amount:1500}),lesson([a],{status:'manual_paid'})])await post(cover(pkg,l),409);
 const pending=lesson([a]);sql.prepare("UPDATE lesson_payments SET attempt_key='CHECKOUT' WHERE id=?").run(pending.payment);await post(cover(pkg,pending),409);
 const use=cover(pkg,target);loseRun=true;await post(use,503);await post(use);assert.deepEqual({...sql.prepare('SELECT amount,status FROM lesson_payments WHERE id=?').get(target.payment)},{amount:1900,status:'manual_paid'});assert.equal(sql.prepare('SELECT payment_status FROM scheduled_lessons WHERE id=?').get(target.id).payment_status,'paid');
 await post({...use,id:crypto.randomUUID()},409);await post({kind:'void',id:pkg.id,confirmed:true},409);assert.throws(()=>sql.prepare("UPDATE scheduled_lessons SET payment_method='online' WHERE id=?").run(target.id),/PACKAGE_PAYMENT_METHOD/);
 const selected=await (await lessons.GET(req('/api/studente?anteprima='+a))).json();assert.equal(selected.lessons.find(l=>l.id===target.id).package_status,'applied');assert.equal(selected.lessons.find(l=>l.id===target.id).amount,1900);
 const previousVersion=sql.prepare('SELECT version FROM scheduled_lessons WHERE id=?').get(target.id).version;sql.prepare('UPDATE scheduled_lessons SET starts_at=?,ends_at=? WHERE id=?').run(new Date(Date.now()+40*86400000).toISOString(),new Date(Date.now()+40*86400000+3300000).toISOString(),target.id);assert.equal(sql.prepare('SELECT status FROM package_uses WHERE id=?').get(use.id).status,'applied');
 await post({kind:'return',id:use.id});await post({kind:'return',id:use.id});assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(target.payment).amount,2000);assert.equal(sql.prepare('SELECT payment_status FROM scheduled_lessons WHERE id=?').get(target.id).payment_status,'awaiting');assert.ok(sql.prepare('SELECT version FROM scheduled_lessons WHERE id=?').get(target.id).version>previousVersion);
 const reused=cover(pkg,target);await post(reused);sql.prepare("UPDATE scheduled_lessons SET status='cancelled' WHERE id=?").run(target.id);assert.equal(sql.prepare('SELECT status FROM package_uses WHERE id=?').get(reused.id).status,'returned');assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(target.payment).amount,1900);assert.equal((await (await lessons.GET(req('/api/studente?anteprima='+a))).json()).lessons.find(l=>l.id===target.id).package_status,'returned');
 const six=Array.from({length:6},()=>lesson([a]));const attempts=six.map(l=>cover(pkg,l));const results=await Promise.all(attempts.map(p=>admin.POST(req('/api/gestione/pacchetti',p))));assert.deepEqual(results.map(r=>r.status).sort(),[200,200,200,200,200,409]);assert.equal((await (await admin.GET(req('/api/gestione/pacchetti?studente='+a))).json()).packages[0].remaining,0);
 const past=attempts[0];sql.prepare('UPDATE scheduled_lessons SET starts_at=?,ends_at=? WHERE id=(SELECT lesson_id FROM lesson_payments WHERE id=?)').run(new Date(Date.now()-86400000).toISOString(),new Date(Date.now()-86400000+3300000).toISOString(),past.paymentId);await post({kind:'return',id:past.id},409);
 const unused=create(b,'pos');await post(unused,201);await post({kind:'activate',id:unused.id,confirmed:true});await post({kind:'void',id:unused.id,confirmed:true});await post({kind:'void',id:unused.id,confirmed:true});await post(cover(unused,lesson([b])),409);
 const pendingVoid=create(b);await post(pendingVoid,201);await post({kind:'void',id:pendingVoid.id,confirmed:true});await post({kind:'activate',id:pendingVoid.id,confirmed:true},409);
 owner=false;user={id:'parent',auth_version:0,must_change_password:0};const own=await (await student.GET(req('/api/studente/pacchetti?studente='+a))).json();assert.equal(own.packages.length,1);assert.equal(own.packages[0].remaining,0);assert.equal(own.uses.length,7);for(const secret of ['SECRET','PRIVATE','payment_id','student_id'])assert.ok(!JSON.stringify(own).includes(secret),secret);
 assert.equal((await student.GET(req('/api/studente/pacchetti?studente='+c))).status,403);assert.equal((await admin.POST(req('/api/gestione/pacchetti',create()))).status,403);assert.equal((await student.GET(req('/api/studente/pacchetti?studente='+b))).status,200);
 sql.prepare("UPDATE account_student_access SET status='revoked' WHERE student_id=?").run(a);assert.equal((await student.GET(req('/api/studente/pacchetti?studente='+a))).status,403);owner=true;assert.equal((await student.GET(req('/api/studente/pacchetti?anteprima='+a))).status,200);
 sql.prepare("UPDATE students SET status='archived' WHERE id=?").run(c);await post(create(c),409);
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM notifications').get().n,0);
 console.log('PASS: verified prepaid packages, owner/guardian scope, fixed terms/prices, lost-write recovery, exact five concurrent allocations, individual/own/future/cash safeguards, cancellation return, immutable started history, package/lesson balance, private DTO and no provider side effects.');
}finally{delete globalThis.__packages;sql.close();}
