import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';
import { DatabaseSync } from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');
for(const f of (await readdir(new URL('../drizzle/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())sql.exec(await readFile(new URL('../drizzle/'+f,import.meta.url),'utf8'));
let owner=false,user=null,loseBatch=false,loseRun=false;
const db={prepare(query){const bind=(...args)=>({query,args,async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const r=sql.prepare(query).run(...args);if(loseRun){loseRun=false;throw Error('Lost write response');}return {meta:{changes:Number(r.changes)}};}});return {bind,...bind()};},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>({meta:{changes:Number(sql.prepare(s.query).run(...s.args).changes)}}));sql.exec('COMMIT');if(loseBatch){loseBatch=false;throw Error('Lost commit response');}return result;}catch(e){if(sql.isTransaction)sql.exec('ROLLBACK');throw e;}}};
globalThis.__referrals={bookingDb:()=>db,isRequestOwner:async()=>owner,getAccount:async()=>user,env:{DB:db}};
async function compile(path,replace=s=>s){const s=replace(await readFile(new URL('../'+path,import.meta.url),'utf8')).replace(/import \{ bookingDb \} from '@\/lib\/booking\/runtime';/g,'const {bookingDb}=globalThis.__referrals;').replace(/import \{ isRequestOwner \} from '@\/lib\/request-admin';/g,'const {isRequestOwner}=globalThis.__referrals;').replace(/import \{ getAccount \} from '@\/lib\/auth\/session';/g,'const {getAccount}=globalThis.__referrals;').replace(/import \{ env \} from '@\/lib\/runtime-env';/g,'const {env}=globalThis.__referrals;').replace("import {limitPublicRequest} from '@/lib/public-request-limit';",'const limitPublicRequest=async()=>null;').replace("from 'zod'",'from '+JSON.stringify(import.meta.resolve('zod')));return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');}
const access=await compile('lib/learning/access.ts'),rules=await compile('lib/referrals/rules.ts');
const replace=s=>s.replace("from '@/lib/learning/access'",'from '+JSON.stringify(access)).replace("from '@/lib/referrals/rules'",'from '+JSON.stringify(rules)).replace("from './rules'",'from '+JSON.stringify(rules));
const server=await compile('lib/referrals/server.ts',replace);
const linked=s=>replace(s).replace("from '@/lib/referrals/server'",'from '+JSON.stringify(server));
const admin=await import(await compile('app/api/gestione/inviti/route.ts',linked)),student=await import(await compile('app/api/studente/inviti/route.ts',linked));
const store=await compile('lib/request-store.ts');const contact=await import(await compile('app/api/contatti/route.ts',s=>linked(s).replace("from '@/lib/request-store'",'from '+JSON.stringify(store))));
const origin='https://site.example';const req=(path,body,from=origin)=>new Request(origin+path,{method:body?'POST':'GET',headers:{Origin:from,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
const now=new Date().toISOString(),claim=new Date(Date.now()-60*86400000).toISOString();
const ids=Array.from({length:6},()=>crypto.randomUUID());const [sender,friend,other,solo,waiting,fresh]=ids;
for(const [i,id] of ids.entries())sql.prepare("INSERT INTO students(id,name,email,notes,created_at,updated_at) VALUES(?,?,?,'SECRET NOTES',?,?)").run(id,['Sender','Friend','Other','Solo','Waiting','Fresh'][i],'private-'+i+'@example.com',now,now);
function account(id,students){sql.prepare("INSERT INTO accounts(id,email,name,role,password_hash,must_change_password,created_at,updated_at) VALUES(?,?,?,'guardian','test',0,?,?)").run(id,id+'@example.com',id,now,now);for(const sid of students)sql.prepare("INSERT INTO account_student_access(account_id,student_id,created_at) VALUES(?,?,?)").run(id,sid,now);return {id,auth_version:0,must_change_password:0};}
const guardian=account('guardian',[sender,solo]);let offset=0;
function lesson(students,{future=false,paid=true,method='cash'}={}){const id=crypto.randomUUID(),start=new Date(Date.now()+(future?10*86400000:-30*86400000)+(offset++)*7200000).toISOString(),end=new Date(Date.parse(start)+3300000).toISOString();sql.prepare("INSERT INTO scheduled_lessons(id,series_id,name,email,subject,starts_at,ends_at,mode,notes,status,created_at,payment_method,student_id,group_id,payment_status) VALUES(?,?,'SECRET GROUP','secret@example.com','Matematica',?,?,'Online','SECRET NOTES','planned',?,?,?,?,?)").run(id,id,start,end,now,method,students.length===1?students[0]:null,students.length>1?crypto.randomUUID():null,paid?'paid':'awaiting');const payments={};for(const sid of students){const pid=crypto.randomUUID();payments[sid]=pid;sql.prepare("INSERT INTO lesson_payments(id,lesson_id,access_token,student_id,name,email,amount,status,paid_at,created_at) VALUES(?,?,'SECRET TOKEN',?,'SECRET NAME','secret@example.com',?,?,?,?)").run(pid,id,sid,students.length===1?2000:1500,paid?'manual_paid':'awaiting',paid?now:null,now);}return {id,payments};}
async function post(body,expected=200){const r=await admin.POST(req('/api/gestione/inviti',body));assert.equal(r.status,expected,await r.clone().text());return r;}
async function code(sid){await post({kind:'code',studentId:sid});return sql.prepare('SELECT code FROM referral_codes WHERE student_id=?').get(sid).code;}
async function link(sid,c){const requestId=crypto.randomUUID(),id=crypto.randomUUID();sql.prepare("INSERT INTO requests(id,kind,name,email,subject,details,status,created_at,consent_version,student_id) VALUES(?,'contact','Private','private@example.com','Matematica',?,'new',?,'test',?)").run(requestId,JSON.stringify({referralCode:c}),claim,sid);await post({kind:'link',id,code:c,studentId:sid,requestId},201);return id;}
const approve=(id,kind,ls)=>({kind:'approve',id,operationId:crypto.randomUUID(),rewardKind:kind,lessonIds:ls.map(l=>l.id)});
try{
 assert.equal((await admin.GET(req('/api/gestione/inviti'))).status,403);assert.equal((await student.GET(req('/api/studente/inviti'))).status,401);owner=true;
 assert.equal((await admin.POST(req('/api/gestione/inviti',{kind:'code',studentId:sender},'https://evil.example'))).status,403);
 const c=await code(sender);assert.match(c,/^FF-[a-f0-9]{16}$/);assert.equal(await code(sender),c);
 await post({kind:'link',id:crypto.randomUUID(),code:c,studentId:sender},409);
 const group=Array.from({length:3},()=>lesson([sender,friend]));const invite=await link(friend,c);
 const command=approve(invite,'group',group);await post({...command,lessonIds:[group[0].id,group[0].id,group[1].id]},400);
 const mismatch=lesson([other,friend]);await post({...command,lessonIds:[group[0].id,group[1].id,mismatch.id]},409);
 sql.prepare("UPDATE lesson_payments SET status='awaiting',paid_at=NULL WHERE id=?").run(group[2].payments[sender]);await post(command,409);
 sql.prepare("UPDATE lesson_payments SET status='manual_paid',paid_at=? WHERE id=?").run(now,group[2].payments[sender]);
 const future=lesson([sender,friend],{future:true});await post({...command,lessonIds:[group[0].id,group[1].id,future.id]},409);
 sql.prepare("UPDATE scheduled_lessons SET status='cancelled' WHERE id=?").run(group[2].id);await post(command,409);sql.prepare("UPDATE scheduled_lessons SET status='planned' WHERE id=?").run(group[2].id);
 loseBatch=true;await post(command,503);await post(command);assert.equal(sql.prepare('SELECT COUNT(*) n FROM referral_credits WHERE referral_id=?').get(invite).n,2);assert.equal(sql.prepare('SELECT SUM(amount) n FROM referral_credits WHERE referral_id=?').get(invite).n,2000);
 await post({...command,operationId:crypto.randomUUID()});assert.equal(sql.prepare('SELECT COUNT(*) n FROM referral_qualifications WHERE referral_id=?').get(invite).n,3);await post({...command,rewardKind:'individual'},409);
 await post({kind:'link',id:crypto.randomUUID(),code:c,studentId:friend},409);const alternate=await code(other);await post({kind:'link',id:crypto.randomUUID(),code:alternate,studentId:friend},409);
 await post({kind:'link',id:crypto.randomUUID(),code:c,studentId:solo},201); // Fresh direct attribution, before lessons.
 const soloId=sql.prepare('SELECT id FROM referrals WHERE invited_id=?').get(solo).id;
 // A request recorded before the first lesson supports later administrative linking.
 const soloLessons=Array.from({length:3},()=>lesson([solo]));sql.prepare('UPDATE referrals SET created_at=? WHERE id=?').run(claim,soloId);
 await post(approve(soloId,'individual',soloLessons));assert.equal(sql.prepare('SELECT SUM(amount) n FROM referral_credits WHERE referral_id=?').get(soloId).n,1000);
 const testPayment=lesson([waiting],{method:'online'}),cashWaiting=Array.from({length:2},()=>lesson([waiting]));const waitingId=await link(waiting,c);await post(approve(waitingId,'individual',[...cashWaiting,testPayment]),409);
 const dto=await (await admin.GET(req('/api/gestione/inviti?studente='+sender))).json();assert.equal(dto.credits.length,2);
 const groupCredit=dto.credits.find(c=>c.kind==='group'),individualCredit=dto.credits.find(c=>c.kind==='individual');
 const packageId=crypto.randomUUID();sql.prepare("INSERT INTO lesson_packages(id,student_id,amount,units,unit_amount,payment_method,status,paid_at,created_at) VALUES(?,?,9500,5,1900,'cash','active',?,?)").run(packageId,sender,now,now);
 const packageTarget=lesson([sender],{future:true,paid:false}),coupon={kind:'redeem',id:crypto.randomUUID(),creditId:individualCredit.id,paymentId:packageTarget.payments[sender]};await post(coupon);
 assert.throws(()=>sql.prepare('INSERT INTO package_uses(id,package_id,payment_id,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),packageId,coupon.paymentId,now),/PACKAGE_UNAVAILABLE/);await post({kind:'return',id:coupon.id});
 sql.prepare('INSERT INTO package_uses(id,package_id,payment_id,created_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),packageId,coupon.paymentId,now);await post({...coupon,id:crypto.randomUUID()},409);
 sql.prepare("UPDATE scheduled_lessons SET status='cancelled' WHERE id=?").run(packageTarget.id);
 const soloFuture=lesson([sender],{future:true,paid:false});await post({kind:'redeem',id:crypto.randomUUID(),creditId:groupCredit.id,paymentId:soloFuture.payments[sender]},409);
 const wrongStudent=lesson([other],{future:true,paid:false});await post({kind:'redeem',id:crypto.randomUUID(),creditId:individualCredit.id,paymentId:wrongStudent.payments[other]},409);
 const onlineFuture=lesson([sender],{future:true,paid:false,method:'online'});await post({kind:'redeem',id:crypto.randomUUID(),creditId:individualCredit.id,paymentId:onlineFuture.payments[sender]},409);
 const target=lesson([sender,friend],{future:true,paid:false});const spend={kind:'redeem',id:crypto.randomUUID(),creditId:groupCredit.id,paymentId:target.payments[sender]};loseRun=true;await post(spend,503);await post(spend);assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(spend.paymentId).amount,1000);assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(target.payments[friend]).amount,1500);
 await post({...spend,id:crypto.randomUUID()},409);await post({...spend,creditId:individualCredit.id},409);await post({kind:'revoke',id:invite},409);
 await post({kind:'return',id:spend.id});await post({kind:'return',id:spend.id});assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(spend.paymentId).amount,1500);
 const reapplied={...spend,id:crypto.randomUUID()};await post(reapplied);assert.throws(()=>sql.prepare("UPDATE scheduled_lessons SET payment_method='online' WHERE id=?").run(target.id),/REFERRAL_CREDIT_PAYMENT_METHOD/);
 sql.prepare("UPDATE scheduled_lessons SET status='cancelled' WHERE id=?").run(target.id);assert.equal(sql.prepare('SELECT status FROM referral_redemptions WHERE id=?').get(reapplied.id).status,'returned');assert.equal(sql.prepare('SELECT amount FROM lesson_payments WHERE id=?').get(spend.paymentId).amount,1500);
 const expired=lesson([sender,friend],{future:true,paid:false});sql.prepare("UPDATE referral_credits SET expires_at='2000-01-01' WHERE id=?").run(groupCredit.id);await post({kind:'redeem',id:crypto.randomUUID(),creditId:groupCredit.id,paymentId:expired.payments[sender]},409);sql.prepare("UPDATE referral_credits SET expires_at='2100-01-01' WHERE id=?").run(groupCredit.id);
 sql.prepare("UPDATE scheduled_lessons SET status='cancelled' WHERE id=?").run(group[0].id);assert.equal((await (await admin.GET(req('/api/gestione/inviti?studente='+sender))).json()).credits.find(c=>c.id===groupCredit.id).available,0);await post({kind:'redeem',id:crypto.randomUUID(),creditId:groupCredit.id,paymentId:expired.payments[sender]},409);sql.prepare("UPDATE scheduled_lessons SET status='planned' WHERE id=?").run(group[0].id);
 const t1=lesson([sender,friend],{future:true,paid:false}),t2=lesson([sender,friend],{future:true,paid:false}),t3=lesson([sender,friend],{future:true,paid:false});const uses=[t1,t2,t3].map(l=>({kind:'redeem',id:crypto.randomUUID(),creditId:groupCredit.id,paymentId:l.payments[sender]}));const races=await Promise.all(uses.map(p=>admin.POST(req('/api/gestione/inviti',p))));assert.deepEqual(races.map(r=>r.status).sort(),[200,200,409]);assert.equal((await (await admin.GET(req('/api/gestione/inviti?studente='+sender))).json()).credits.find(c=>c.id===groupCredit.id).remaining,0);
 owner=false;user=guardian;const own=await (await student.GET(req('/api/studente/inviti?studente='+sender))).json();assert.equal(own.code,c);assert.equal(own.credits.length,2);for(const secret of ['Friend','Other','private-','SECRET NOTES','SECRET TOKEN','payment_id'])assert.ok(!JSON.stringify(own).includes(secret),secret);
 assert.equal((await student.GET(req('/api/studente/inviti?studente='+friend))).status,403);assert.equal((await student.GET(req('/api/studente/inviti?anteprima='+friend))).status,403);
 assert.equal((await student.POST(req('/api/studente/inviti',{studentId:friend}))).status,403);assert.equal((await student.POST(req('/api/studente/inviti',{studentId:solo}))).status,200);
 sql.prepare("UPDATE account_student_access SET status='revoked' WHERE student_id=?").run(sender);assert.equal((await student.GET(req('/api/studente/inviti?studente='+sender))).status,403);
 owner=true;assert.equal((await student.GET(req('/api/studente/inviti?anteprima='+friend))).status,200);assert.equal((await student.POST(req('/api/studente/inviti?anteprima='+friend,{studentId:friend}))).status,403);
 const contactBody={id:crypto.randomUUID(),name:'New friend',email:'new@example.com',subject:'Matematica',message:'Vorrei lezioni in gruppo',consent:true,website:'',referralCode:c};assert.equal((await contact.POST(req('/api/contatti',contactBody))).status,201);assert.equal(JSON.parse(sql.prepare('SELECT details FROM requests WHERE id=?').get(contactBody.id).details).referralCode,c);assert.equal((await contact.POST(req('/api/contatti',contactBody))).status,200);assert.equal((await contact.POST(req('/api/contatti',{...contactBody,id:crypto.randomUUID(),referralCode:'FF-0000000000000000'}))).status,400);
 const unusedId=await link(fresh,c);await post({kind:'reject',id:unusedId});await post({...approve(unusedId,'group',group)},409);
 const expiry=await import(rules);assert.equal(expiry.creditExpiry(new Date('2024-02-29T10:00:00Z')),'2025-02-28T10:00:00.000Z');
 assert.equal(sql.prepare('SELECT COUNT(*) n FROM notifications').get().n,0);
 console.log('PASS: attribution before first lesson, private codes/guardian scope, readonly preview, distinct individual/group qualification, verified cash/POS only, future/cancelled/unpaid/test exclusions, alternative rewards, atomic approval/retries, max 5€/quota, own credit and group restrictions, lost write recovery, concurrent exhaustion, cancellation/return, expiry, invalidated rewards and no messages/payments.');
}finally{sql.close();delete globalThis.__referrals;}
