import {publicPageMetadata} from '@/lib/site-seo';
import MaturityProgramme from '@/components/site/maturity-programme';
import ContactForm from '@/components/site/contact-form';
export function generateMetadata(){return publicPageMetadata('/maturita');}
export default function Maturita(){return <main className="wrap subject-page maturity-page">
 <section className="subject-intro"><p className="subject-audience">Matematica · Informatica · Sistemi e Reti</p><h1>Ripasso per la maturità</h1><p>Argomenti ed esercitazioni dal programma della tua classe, a Lodi oppure online.</p><div className="actions"><a className="button dark" href="/incontro">Incontro gratuito</a><a className="button outline" href="#chiedi-informazioni">Chiedi informazioni</a></div></section>
 <section className="subject-lesson"><div><h2>5 lezioni individuali</h2><p className="catalog-price">95 € <small>5 incontri da 55 minuti</small></p><p>Un primo blocco di ripasso, da concordare. Puoi scegliere anche lezioni singole a 20 € o aggiungere incontri.</p><p className="reading-note">Cinque lezioni potrebbero non bastare per tutto il programma.</p><a className="text-link" href="/prezzi">Prezzi e condizioni</a></div><aside><h3>In gruppo da 2 a 4</h3><p className="catalog-price">15 € <small>a persona, per 55 minuti</small></p><p>5 incontri costano 75 € a persona, senza ulteriori sconti.</p><a className="text-link" href="/?richiesta=group">Chiedi un gruppo</a></aside></section>
 <MaturityProgramme/>
 <section className="maturity-details"><details className="public-disclosure"><summary>Un esempio dei 5 incontri</summary><ol className="maturity-steps"><li>Basi ed esercizi che bloccano il lavoro.</li><li>Argomenti scelti dal programma.</li><li>Nuovi esercizi e revisione degli errori.</li><li>Una prova con un tempo concordato.</li><li>Correzione della prova e ultimi punti da riprendere.</li></ol><p>È un esempio; lo adattiamo al programma e alla tua preparazione.</p></details><details className="public-disclosure"><summary>Come organizziamo i gruppi</summary><p>Confronto programmi e preparazione prima di proporre un gruppo. Puoi venire con i compagni o chiedermi di cercarli; può servire tempo per trovare studenti e orari compatibili.</p></details><details className="public-disclosure"><summary>Esercizi a casa e condizioni del pacchetto</summary><p>Se concordiamo lavoro a casa, nell’area studente trovi consegne e correzioni e puoi caricare gli esercizi.</p><p>Il pacchetto si paga insieme dopo aver concordato programma, condizioni e appuntamenti. Il credito invito non si somma al pacchetto. La richiesta non prenota lezioni e non richiede pagamenti.</p><a className="text-link" href="/piattaforma">Guarda l’area studente</a></details></section>
 <section id="chiedi-informazioni" className="subject-contact"><ContactForm initialMessage="Vorrei informazioni sul ripasso per la maturità."/></section>
 </main>;}
