'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import TemplateTools from '@/components/management/template-tools';
import BulkHomework from '@/components/management/bulk-homework';
import { civilDate,lessonDate,visibilityLabels } from '@/lib/study/types';
import { late,reviewLabels,type Assignment,type HomeworkManagementData,type Submission } from '@/lib/homework/types';
export default function HomeworkManager(){
 const [data,setData]=useState<HomeworkManagementData|null>(null),[studentId,setStudentId]=useState(''),[task,setTask]=useState<Assignment|null>(null),[editing,setEditing]=useState(false),[selectedTask,setSelectedTask]=useState(''),[review,setReview]=useState<Submission|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[dirty,setDirty]=useState(false);const newId=useRef(''),taskForm=useRef<HTMLFormElement>(null);const [bulk,setBulk]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('studente');if(id)setStudentId(id);const task=new URLSearchParams(window.location.search).get('compito');if(task)setSelectedTask(task);},[]);
 useEffect(()=>{const c=new AbortController();setError('');fetch('/api/gestione/compiti'+(studentId?'?studente='+encodeURIComponent(studentId):''),{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as HomeworkManagementData&{error?:string};if(!r.ok)throw Error(d.error||'Compiti non disponibili.');return d;}).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[studentId,revision]);
 const active=data?.students.find(s=>s.id===data.selected)?.status==='active',attempts=data?.submissions.filter(s=>s.assignment_id===selectedTask)||[],locked=!!task&&!!data?.submissions.some(s=>s.assignment_id===task.id);
 async function send(body:unknown){const r=await fetch('/api/gestione/compiti',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Salvataggio non riuscito.');}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data?.selected)return;const f=new FormData(e.currentTarget),read=(name:string)=>String(f.get(name)||'');setBusy(true);setError('');setNotice('');try{await send({kind:'task',id:task?.id||newId.current,studentId:data.selected,version:task?.version??null,planId:read('planId')||null,title:read('title'),subject:read('subject'),instructions:read('instructions'),dueDate:read('dueDate')||null,status:read('status')});setEditing(false);setNotice(read('status')==='published'?'Compito condiviso nell’area studente. Nessuna email inviata.':'Compito salvato. È visibile soltanto al tutor.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!task)return;const f=new FormData(e.currentTarget);f.set('id',task.id);f.set('version',String(task.version));setBusy(true);setError('');try{const r=await fetch('/api/gestione/compiti/file',{method:'PUT',body:f}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'File non caricato.');setEditing(false);setNotice('File caricato. Il compito è tornato in bozza: riaprilo e pubblicalo quando è pronto.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function feedback(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!review)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setNotice('');try{await send({kind:'feedback',id:review.id,version:review.version,feedback:f.get('feedback'),status:f.get('status'),reviewStatus:f.get('reviewStatus')});setReview(null);setNotice(f.get('status')==='published'?'Correzione condivisa. È visibile allo studente se il compito è pubblicato. Nessuna email inviata.':'Correzione salvata in bozza, riservata al tutor.');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function edit(a:Assignment|null){newId.current=a?.id||crypto.randomUUID();setTask(a);setBulk(false);setDirty(false);setEditing(true);setReview(null);setError('');setNotice('');}
 function changeStudent(id:string){setData(null);setStudentId(id);setEditing(false);setReview(null);setSelectedTask('');setBulk(false);setNotice('');const p=new URLSearchParams(window.location.search);p.set('studente',id);window.history.replaceState(null,'','?'+p);}
 const fileUrl=(kind:'task'|'submission',id:string)=>'/api/gestione/compiti/file?'+new URLSearchParams({kind,id});
 return <>{error&&<div className="error" role="alert"><p>{error}</p><button className="button outline" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Ricarica elenco</button><p>Il testo che hai scritto resta nel modulo. Se la versione non è aggiornata, riapri il compito dall’elenco.</p></div>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p role="status">Caricamento…</p>}{data&&(!data.students.length?<section className="booking-empty"><p>Registra prima uno studente nell’anagrafica.</p><a className="button dark" href="/gestione/anagrafica">Apri anagrafica</a></section>:<>
 <div className="learning-toolbar"><label>Studente<select value={data.selected||''} disabled={busy} onChange={e=>changeStudent(e.target.value)}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}{s.status!=='active'?' · Archiviato':''}</option>)}</select></label><button className="button dark" disabled={busy||!active} onClick={()=>edit(null)}>Nuovo compito</button><button className="button outline" disabled={busy||data.students.filter(s=>s.status==='active').length<2} onClick={()=>{setBulk(true);setEditing(false);setReview(null);setSelectedTask('');setNotice('');}}>Assegna a più studenti</button>{active&&<a className="text-link" href={`/studente?anteprima=${data.selected}&vista=compiti`}>Apri anteprima studente</a>}</div>{!active&&<p>La scheda è archiviata. Puoi leggere lo storico; per fare modifiche, ripristina prima lo studente.</p>}{data.truncated&&<p>Mostriamo gli ultimi 50 compiti.</p>}{data.studentLimit&&<p>Mostriamo le prime 1.000 schede e quella selezionata.</p>}
 {bulk&&<BulkHomework students={data.students} onClose={()=>setBulk(false)} onSaved={count=>{setBulk(false);setNotice(`Creati ${count} compiti personali. Nessuna email inviata.`);setRevision(v=>v+1);}}/>}<div className="study-layout"><section aria-label="Compiti salvati">{!data.assignments.length&&<p>Nessun compito ancora assegnato.</p>}{data.assignments.map(a=>{const latest=data.submissions.find(s=>s.assignment_id===a.id),count=data.submissions.filter(s=>s.assignment_id===a.id).length;return <article className="registry-card" key={a.id}><span className="booking-badge">{visibilityLabels[a.status]}</span><h3>{a.title}</h3><p>{a.subject}{a.due_date?' · Consegna entro '+civilDate(a.due_date):''}</p><p>{count?count+(count===1?' consegna · ':' consegne · ')+reviewLabels[latest!.review_status]:'Nessuna consegna'}{latest?.feedback_status==='draft'&&latest.feedback?' · Correzione in bozza':''}</p><div className="registry-actions"><button className="button outline" disabled={busy} onClick={()=>edit(a)}>Apri compito</button><button className="button outline" disabled={busy} onClick={()=>{setSelectedTask(a.id);setEditing(false);setReview(null);setNotice('');}}>Consegne e correzioni</button></div></article>;})}</section>
 {editing&&<section className="registry-editor study-editor"><h2>{task?'Modifica compito':'Nuovo compito'}</h2>{locked&&<p>Dopo la prima consegna non puoi cambiare istruzioni, scadenza o allegato. Puoi ancora modificare la visibilità o creare un altro compito.</p>}<form key={newId.current+':'+(task?.version??'new')} ref={taskForm} onSubmit={save} onChange={()=>setDirty(true)}><fieldset disabled={busy||!active}><TemplateTools kind="task" formRef={taskForm} disabled={busy||locked} onApply={()=>setDirty(true)}/><label>Titolo<input name="title" required minLength={2} maxLength={160} defaultValue={task?.title||''} readOnly={locked}/></label><label>Materia / esame<input name="subject" required minLength={2} maxLength={160} defaultValue={task?.subject||''} readOnly={locked}/></label><label>Piano personale, facoltativo<select name="planId" defaultValue={task?.plan_id||''} disabled={locked}><option value="">Nessun collegamento</option>{task?.plan_id&&!data.plans.some(p=>p.id===task.plan_id)&&<option value={task.plan_id}>{task.plan_title||'Piano collegato'}</option>}{data.plans.map(p=><option key={p.id} value={p.id}>{p.title} · {visibilityLabels[p.status as keyof typeof visibilityLabels]}</option>)}</select></label>{locked&&<input type="hidden" name="planId" value={task?.plan_id||''}/>}<label>Istruzioni ed esercizi<textarea name="instructions" required maxLength={10000} rows={7} defaultValue={task?.instructions||''} readOnly={locked}/></label><label>Data di consegna, facoltativa<input type="date" name="dueDate" defaultValue={task?.due_date||''} readOnly={locked}/></label><p>Lo studente può consegnare anche dopo questa data. Il ritardo viene segnalato.</p><label>Visibilità<select name="status" defaultValue={task?.status||'draft'}><option value="draft">Bozza · solo tutor</option><option value="published">Visibile allo studente</option><option value="archived">Archiviato · solo tutor</option></select></label><div className="registry-actions"><button className="button dark">{busy?'Salvataggio…':'Salva compito'}</button><button className="button outline" type="button" onClick={()=>setEditing(false)}>Chiudi modulo</button></div></fieldset></form>{data.planLimit&&<p>La selezione mostra gli ultimi 50 piani.</p>}{task&&<section className="homework-upload"><h3>Allegato degli esercizi</h3>{task.filename&&<a className="button outline" href={fileUrl('task',task.id)}>Scarica {task.filename}</a>}{!locked&&active&&<form onSubmit={upload}><fieldset disabled={busy||dirty}><label>File PDF, PNG, JPEG o testo UTF-8, fino a 10 MB<input type="file" name="file" accept="application/pdf,image/png,image/jpeg,text/plain" required/></label><p>{dirty?'Salva le modifiche al compito prima di caricare il file.':'Il caricamento riporta il compito in bozza.'}</p><button className="button outline">Carica allegato</button></fieldset></form>}</section>}</section>}
 {!editing&&selectedTask&&<section className="registry-editor"><h2>Consegne: {data.assignments.find(a=>a.id===selectedTask)?.title}</h2>{!attempts.length&&<p>Nessuna consegna ricevuta.</p>}{attempts.map((s,i)=><article className="homework-review" key={s.id}><h3>Tentativo {s.attempt}</h3><p>{lessonDate(s.created_at)} · {reviewLabels[s.review_status]}{s.feedback_status==='draft'&&s.feedback?' · Bozza non condivisa':''}</p>{late(s.created_at,data.assignments.find(a=>a.id===selectedTask)?.due_date||null)&&<p>Consegnato oltre la data indicata.</p>}{s.body&&<p className="learning-copy">{s.body}</p>}{s.filename&&<a className="button outline" href={fileUrl('submission',s.id)}>Scarica consegna · {s.filename}</a>}{s.feedback&&<div className="homework-feedback"><p className="learning-copy">{s.feedback}</p></div>}{i===0&&<button className="button outline" disabled={busy||!active} onClick={()=>{setReview(s);setError('');}}>Correggi ultima consegna</button>}</article>)}{review&&<form key={review.id+':'+review.version} onSubmit={feedback}><fieldset disabled={busy||!active}><h3>Correzione · tentativo {review.attempt}</h3><label>Commento e indicazioni<textarea name="feedback" required maxLength={10000} rows={7} defaultValue={review.feedback}/></label><label>Esito<select name="reviewStatus" defaultValue={review.review_status==='pending'?'accepted':review.review_status}><option value="accepted">Compito completato</option><option value="revise">Da rivedere · abilita un nuovo tentativo</option></select></label><label>Visibilità della correzione<select name="status" defaultValue={review.feedback_status}><option value="draft">Bozza · solo tutor</option><option value="published">Condivisa con lo studente</option></select></label><button className="button dark">{busy?'Salvataggio…':'Salva correzione'}</button></fieldset></form>}</section>}
 </div></>)}</>;
}
