'use client';
import { useEffect,useState,type FormEvent } from 'react';
import { requestDetails,detailText } from '@/lib/requests/types';
import { compareCandidates,groupProblems,normalize,snapshot } from '@/lib/matching/compare';
import { reviewLabels,type Candidate,type Proposal,type ReviewKey } from '@/lib/matching/types';

type Data={candidates:Candidate[];proposals:Proposal[];limits:{candidates:boolean;proposals:boolean}};
type Checks=Record<ReviewKey,boolean>;
const emptyChecks:Checks={program:false,level:false,goal:false,availability:false,mode:false};
const fields:Record<string,string>={studentType:'Studi',institution:'Istituto',year:'Classe / corso',teacher:'Docente',program:'Programma',level:'Livello dichiarato',goal:'Obiettivo',deadline:'Data obiettivo',availability:'Disponibilità',mode:'Modalità',groupSize:'Dimensione preferita'};
function members(p:Proposal){try{return JSON.parse(p.members) as Candidate[];}catch{return [];}}
async function send(method:string,body:unknown){const r=await fetch('/api/gestione/abbinamenti',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Operazione non riuscita.');return d;}
export default function Matching(){
 const [data,setData]=useState<Data|null>(null),[selected,setSelected]=useState<string[]>([]),[subject,setSubject]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[mode,setMode]=useState('Online'),[availability,setAvailability]=useState(''),[notes,setNotes]=useState(''),[checks,setChecks]=useState<Checks>({...emptyChecks}),[attempt,setAttempt]=useState<string|null>(null);
 async function load(signal?:AbortSignal){const anchor=new URLSearchParams(window.location.search).get('richiesta');const r=await fetch('/api/gestione/abbinamenti'+(anchor?'?richiesta='+encodeURIComponent(anchor):''),{signal});const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error||'Abbinamenti non disponibili.');if(!signal?.aborted)setData(d);return d;}
 useEffect(()=>{const c=new AbortController();load(c.signal).then(d=>{const id=new URLSearchParams(window.location.search).get('richiesta');const row=d.candidates.find(r=>r.id===id);if(row&&!c.signal.aborted){setSelected([row.id]);setSubject(row.subject);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 function changed(){setChecks({...emptyChecks});setAttempt(null);setNotice('');}
 const rows=selected.map(id=>data?.candidates.find(r=>r.id===id)).filter((r):r is Candidate=>!!r);
 const anchor=rows[0];const problems=groupProblems(rows,mode);
 const visible=(data?.candidates||[]).filter(r=>(!subject||r.subject===subject)&&(!query||normalize(r.name+' '+r.student_name+' '+r.subject).includes(normalize(query)))).sort((a,b)=>{
  if(!anchor)return 0;const score=(r:Candidate)=>compareCandidates(anchor,r).filter(x=>x.status==='same').length;return score(b)-score(a);
 });
 function toggle(row:Candidate){if(selected.includes(row.id)){setSelected(ids=>ids.filter(id=>id!==row.id));changed();return;}if(selected.length>=4){setError('Puoi confrontare al massimo quattro richieste.');return;}setSelected(ids=>[...ids,row.id]);setError('');changed();if(!name)setName('Gruppo '+row.subject);}
 async function refresh(){setBusy(true);setError('');try{await load();changed();setNotice('I dati sono stati aggiornati. Ricontrolla le condizioni prima di salvare.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();if(problems.length)return;setBusy(true);setError('');const id=attempt||crypto.randomUUID();setAttempt(id);try{await send('POST',{id,name,mode,availability,notes,checks,requestIds:rows.map(r=>r.id),expected:JSON.stringify(rows.map(snapshot).sort((a,b)=>a.id.localeCompare(b.id)))});await load();setNotice('Proposta salvata. Aprila nell’elenco per controllarla e approvarla.');setAttempt(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function act(id:string,action:string,review?:Checks){setBusy(true);setError('');try{await send('PATCH',{id,action,checks:review});await load();if(action==='approve')setSelected([]);setNotice(action==='approve'?'Il gruppo è stato creato nell’anagrafica. Le richieste restano in abbinamento. Concorda le lezioni e fissale dal calendario.':'Proposta scartata. Le richieste restano disponibili.');}catch(e){setError((e as Error).message);await load().catch(()=>{});}finally{setBusy(false);}}
 return <>
  <div className="learning-notice"><p>Confronta le richieste e salva una proposta di gruppo. Prima di approvarla, verifica le condizioni con gli studenti. L’approvazione registra il gruppo nell’anagrafica; le lezioni vanno concordate e fissate dal calendario.</p><p>15 € a persona per 55 minuti · 2–4 studenti.</p></div>
  <div className="matching-toolbar"><label>Materia<select value={subject} disabled={busy} onChange={e=>setSubject(e.target.value)}><option value="">Tutte le materie</option>{[...new Set(data?.candidates.map(r=>r.subject))].sort().map(s=><option key={s}>{s}</option>)}</select></label><label>Cerca uno studente<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome o materia"/></label><button className="button outline" disabled={busy} onClick={refresh}>Aggiorna</button></div>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="matching-feedback" role="status">{notice}</p>}
  {!data?<p role="status">Caricamento…</p>:<>
   {(data.limits.candidates||data.limits.proposals)&&<p className="form-note">L’elenco contiene le ultime 500 richieste e 100 proposte. Se apri una richiesta dal suo link, viene mostrata anche se è precedente.</p>}
   <section aria-labelledby="candidates-title"><div className="learning-toolbar"><h2 id="candidates-title">Lista di abbinamento</h2><span>{selected.length} richieste selezionate</span><button className="button outline" disabled={busy||!selected.length} onClick={()=>{setSelected([]);changed();}}>Svuota selezione</button></div>
    <p className="form-note">Le richieste con più informazioni in comune compaiono per prime. Devi comunque verificare personalmente programma, orari e risultato del test.</p>
    {!visible.length?<div className="booking-empty"><p>Nessuna richiesta nella lista per questo filtro.</p><a href="/gestione">Apri tutte le richieste</a></div>:<div className="matching-candidates">{visible.map(r=>{const details=requestDetails(r.details),signals=anchor&&anchor.id!==r.id?compareCandidates(anchor,r):[];return <article key={r.id} className={'registry-card '+(selected.includes(r.id)?'learning-selected':'')}><label className="matching-choice"><input type="checkbox" checked={selected.includes(r.id)} disabled={busy||(!selected.includes(r.id)&&selected.length>=4)} onChange={()=>toggle(r)}/><strong>{r.student_name||r.name}</strong></label><p>{r.subject} · {detailText(details,'studentType')||'Studi da verificare'}</p><p>{detailText(details,'level')||'Livello non indicato'}</p><p>{detailText(details,'availability')||'Disponibilità non indicata'}</p>{signals.length>0&&<div className="matching-signals">{signals.map(s=><span key={s.key}>{fields[s.key]}: {s.status==='same'?'indicazione coincidente':s.status==='missing'?'da raccogliere':'da confrontare'}</span>)}</div>}{!r.student_id||r.student_status!=='active'?<p className="form-note">Serve una scheda studente attiva.</p>:r.existing_group_id?<p className="form-note">Già in un gruppo attivo della stessa materia.</p>:null}<a className="text-link" href={'/gestione?richiesta='+r.id}>Richiesta, test e collegamento alla scheda →</a></article>;})}</div>}
   </section>
   {rows.length>0&&<section className="learning-course" aria-labelledby="compare-title"><h2 id="compare-title">Confronto dei partecipanti</h2><Comparison rows={rows}/><form onSubmit={save} className="matching-proposal-form"><div className="form-grid"><label>Nome del gruppo<input required minLength={2} maxLength={100} value={name} disabled={busy} onChange={e=>{setName(e.target.value);setAttempt(null);}}/></label><label>Modalità proposta<select value={mode} disabled={busy} onChange={e=>{setMode(e.target.value);changed();}}><option>Online</option><option>Lodi</option></select></label><label className="full">Disponibilità condivisa da concordare<input required minLength={2} maxLength={1000} value={availability} disabled={busy} onChange={e=>{setAvailability(e.target.value);changed();}} placeholder="Es. giovedì 17–18, da confermare con tutti"/></label><label className="full">Note della proposta<textarea maxLength={800} value={notes} disabled={busy} onChange={e=>{setNotes(e.target.value);setAttempt(null);}}/></label></div><Review checks={checks} setChecks={next=>{setChecks(next);setAttempt(null);}} disabled={busy}/>{problems.length>0&&<ul className="matching-problems">{problems.map(p=><li key={p}>{p}</li>)}</ul>}<p className="form-note">Puoi salvare la proposta anche prima di completare le verifiche. Il confronto salvato non si modifica: per cambiarlo, scarta la proposta e creane un’altra.</p><button className="button dark" disabled={busy||problems.length>0} type="submit">Salva proposta</button></form></section>}
   <section className="matching-proposals" aria-labelledby="proposals-title"><h2 id="proposals-title">Proposte salvate</h2>{!data.proposals.length?<p>Nessuna proposta salvata.</p>:data.proposals.map(p=><ProposalCard key={p.id} proposal={p} candidates={data.candidates} busy={busy} act={act} reopen={ids=>{setSelected(ids);changed();setNotice('Sono stati selezionati i partecipanti con i dati aggiornati. Ripeti il confronto e salva una nuova proposta.');}}/>)}</section>
  </>}
 </>;
}
function Comparison({rows}:{rows:Candidate[]}){return <div className="matching-table-scroll" tabIndex={0} role="region" aria-label="Confronto dei programmi e delle preferenze"><table className="matching-table"><thead><tr><th scope="col">Da confrontare</th>{rows.map(r=><th scope="col" key={r.id}>{r.student_name||r.name}</th>)}</tr></thead><tbody>{Object.entries(fields).map(([key,title])=><tr key={key}><th scope="row">{title}</th>{rows.map(r=><td key={r.id}>{detailText(requestDetails(r.details),key)||'Non indicato'}</td>)}</tr>)}<tr><th scope="row">Test orientativo</th>{rows.map(r=>{const a=r.assessment?requestDetails(r.assessment):null;return <td key={r.id}>{a?`${detailText(a,'test')} · ${typeof a.score==='number'?a.score+'%':'Risultato da verificare'}`:'Non svolto'}<br/><a href={'/gestione?richiesta='+r.id}>Apri dettaglio</a></td>;})}</tr></tbody></table></div>;}
function Review({checks,setChecks,disabled}:{checks:Checks;setChecks:(value:Checks)=>void;disabled:boolean}){return <fieldset className="matching-review" disabled={disabled}><legend>Verifiche del tutor</legend>{Object.entries(reviewLabels).map(([key,label])=><label key={key} className="checkbox"><input type="checkbox" checked={checks[key as ReviewKey]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/>{label} verificati con i partecipanti</label>)}</fieldset>;}
function ProposalCard({proposal:p,candidates,busy,act,reopen}:{proposal:Proposal;candidates:Candidate[];busy:boolean;act:(id:string,action:string,checks?:Checks)=>Promise<void>;reopen:(ids:string[])=>void}){
 const stored=members(p);const [checks,setChecks]=useState<Checks>(()=>{try{return {...emptyChecks,...JSON.parse(p.checks)};}catch{return {...emptyChecks};}});
 const stale=p.status==='draft'&&stored.some(r=>{const current=candidates.find(c=>c.id===r.id);return !current||JSON.stringify(snapshot(current))!==JSON.stringify(r);});
 return <article className="registry-card"><h3>{p.name}</h3><p>{p.subject} · {p.mode} · {p.status==='draft'?'Da approvare':p.status==='approved'?'Gruppo creato':'Scartata'}</p><p>{stored.map(r=>r.student_name||r.name).join(', ')}</p><p>{p.availability}</p>{p.notes&&<p className="learning-copy">{p.notes}</p>}<details><summary>Confronto salvato e verifiche</summary><Comparison rows={stored}/><Review checks={checks} setChecks={setChecks} disabled={busy||p.status!=='draft'||stale}/></details>{stale&&<p className="error">Alcuni dati sono cambiati o alcune richieste non sono nell’elenco caricato. Aggiorna il confronto prima di creare il gruppo.</p>}{p.status==='draft'?<div className="registry-actions"><button className="button dark" disabled={busy||stale||!Object.values(checks).every(Boolean)} onClick={()=>act(p.id,'approve',checks)}>Approva e crea gruppo</button><button className="button outline" disabled={busy} onClick={()=>act(p.id,'dismiss')}>Scarta proposta</button>{stale&&<button className="button outline" disabled={busy} onClick={()=>reopen(stored.map(r=>r.id).filter(id=>candidates.some(c=>c.id===id)))}>Ripeti confronto</button>}</div>:p.status==='approved'&&p.group_id?<div className="registry-actions"><a className="button outline" href={'/gestione/anagrafica?gruppo='+p.group_id}>Apri anagrafica gruppi</a><a className="text-link" href={'/gestione/prenotazioni?richiesta='+stored[0]?.id+'&modalita='+encodeURIComponent(p.mode)}>Concorda lezioni →</a></div>:null}</article>;
}
