'use client';
import { useEffect,useState } from 'react';
import type { Student,StudentGroup } from '@/lib/students/types';
import type { RequestRow } from '@/lib/requests/types';

export default function RequestLink({row,onLinked}:{row:RequestRow;onLinked:(studentId:string|null,groupId:string|null)=>void}) {
 const [registry,setRegistry]=useState<{students:Student[];groups:StudentGroup[]}>({students:[],groups:[]});
 const [choice,setChoice]=useState('new');const [name,setName]=useState(row.name);const [contactName,setContactName]=useState('');const [member,setMember]=useState('');
 const [ready,setReady]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/gestione/anagrafica',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Anagrafica non disponibile.');return await r.json() as typeof registry;}).then(d=>{setRegistry(d);setReady(true);const existing=d.students.find(s=>s.status==='active'&&s.name===row.name&&s.email.toLowerCase()===row.email.toLowerCase());if(existing)setChoice('student:'+existing.id);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[row.id,revision]);
 const selectedGroup=choice.startsWith('group:')?registry.groups.find(g=>g.id===choice.slice(6)):null;
 const linkedStudent=registry.students.find(s=>s.id===row.student_id);const linkedGroup=registry.groups.find(g=>g.id===row.group_id);
 async function save(e:React.FormEvent) {
  e.preventDefault();setBusy(true);setError('');
  const body=choice==='new'?{id:row.id,kind:'new',name,contactName}:choice.startsWith('student:')?{id:row.id,kind:'student',studentId:choice.slice(8)}:{id:row.id,kind:'group',groupId:choice.slice(6),studentId:member};
  try{const r=await fetch('/api/gestione/richieste/anagrafica',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string;studentId:string;groupId:string|null};if(!r.ok)throw Error(d.error||'Scheda non collegata.');onLinked(d.studentId,d.groupId);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function unlink(){setBusy(true);setError('');try{const r=await fetch('/api/gestione/richieste/anagrafica',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,studentId:row.student_id,groupId:row.group_id})});if(!r.ok)throw Error('Collegamento cambiato. Ricarica le richieste.');onLinked(null,null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="request-link"><h3>Anagrafica e lezioni</h3>{error&&<p role="alert" className="error">{error}</p>}{row.student_id?<><p>Richiesta collegata a <strong>{linkedGroup?.name||linkedStudent?.name||(row.group_id?'un gruppo':'uno studente')}</strong>.</p><div className="registry-actions"><a className="button dark" href={`/gestione/prenotazioni?richiesta=${row.id}`}>Fissa lezioni</a><a className="button outline" href={`/gestione/anagrafica?${row.group_id?'gruppo='+row.group_id:'studente='+row.student_id}`}>Apri scheda</a><button className="text-link" disabled={busy} onClick={unlink}>Rimuovi collegamento</button></div><p className="form-note">Se rimuovi il collegamento, schede e appuntamenti restano salvati.</p></>:loading?<p role="status">Caricamento anagrafica…</p>:!ready?<button className="button outline" onClick={()=>setRevision(v=>v+1)}>Riprova</button>:<form onSubmit={save}><label>Collega la richiesta<select value={choice} onChange={e=>{setChoice(e.target.value);const g=registry.groups.find(g=>'group:'+g.id===e.target.value);setMember(g?.members.find(s=>s.email.toLowerCase()===row.email.toLowerCase())?.id||'');}}><option value="new">Crea una scheda studente</option><optgroup label="Studenti già registrati">{registry.students.filter(s=>s.status==='active').map(s=><option key={s.id} value={'student:'+s.id}>{s.name} · {s.email}</option>)}</optgroup><optgroup label="Gruppi già registrati">{registry.groups.filter(g=>g.status==='active'&&g.members.length>=2&&g.members.length<=4&&g.members.every(s=>s.status==='active')).map(g=><option key={g.id} value={'group:'+g.id}>{g.name} · {g.subject}</option>)}</optgroup></select></label>{choice==='new'&&<><label>Nome dello studente<input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><p>Contatto email: {row.email}</p><label>Nome del contatto, se diverso dallo studente<input maxLength={100} placeholder="Ad esempio un genitore" value={contactName} onChange={e=>setContactName(e.target.value)}/></label></>}{selectedGroup&&<label>Studente a cui riferire la richiesta<select required value={member} onChange={e=>setMember(e.target.value)}><option value="">Seleziona un partecipante</option>{selectedGroup.members.map(s=><option key={s.id} value={s.id}>{s.name} · {s.email}</option>)}</select></label>}<div className="registry-actions"><button className="button dark" disabled={busy}>{busy?'Salvataggio…':'Collega all’anagrafica'}</button><a className="text-link" href="/gestione/anagrafica">Crea o gestisci un gruppo</a></div><p className="form-note">Collegare la richiesta non prenota lezioni e non invia messaggi. Per creare un gruppo, registra prima i contatti dei partecipanti nell’anagrafica.</p></form>}</section>;
}
