'use client';
import { useEffect,useState } from 'react';
import CourseProgress from './course-progress';
import type { Course,LearningData,Material,Module } from '@/lib/learning/types';
const blankCourse={title:'',subject:'',description:'',status:'draft',id:undefined as string|undefined};
const blankModule={title:'',position:0,id:undefined as string|undefined};
const blankText={title:'',body:'',position:0,status:'draft',id:undefined as string|undefined};
const labels:Record<string,string>={draft:'Bozza',published:'Disponibile agli iscritti',archived:'Archiviato'};
export default function LearningManager(){
 const [data,setData]=useState<LearningData|null>(null);const [tab,setTab]=useState<'courses'|'access'>('courses');const [progressOpen,setProgressOpen]=useState(false);const [courseId,setCourseId]=useState('');const [moduleId,setModuleId]=useState('');const [course,setCourse]=useState(blankCourse);const [module,setModule]=useState(blankModule);const [text,setText]=useState(blankText);const [studentId,setStudentId]=useState('');const [enrollCourseId,setEnrollCourseId]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState('student');const [fileTitle,setFileTitle]=useState('');const [file,setFile]=useState<File|null>(null);const [fileInput,setFileInput]=useState(0);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/gestione/formazione',{cache:'no-store'});const d=await r.json() as LearningData&{error?:string};if(!r.ok)throw Error(d.error||'Gestione non disponibile.');setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function save(body:object,done?:()=>void){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/gestione/formazione',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Salvataggio non riuscito.');await load();done?.();setMessage('Modifica salvata.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(e:React.FormEvent){e.preventDefault();if(!file)return;setBusy(true);setError('');setMessage('');try{const form=new FormData();form.set('moduleId',moduleId);form.set('title',fileTitle);form.set('position',String(data?.materials.filter(m=>m.module_id===moduleId).length||0));form.set('file',file);const r=await fetch('/api/gestione/formazione',{method:'PUT',body:form});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Caricamento non riuscito.');await load();setFile(null);setFileTitle('');setFileInput(n=>n+1);setMessage('File caricato in bozza. Rendilo disponibile quando è pronto.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function choose(c:Course){setProgressOpen(false);setCourseId(c.id);setModuleId('');setCourse(c);setModule(blankModule);setText(blankText);setFile(null);setFileTitle('');setFileInput(n=>n+1);}
 function chooseModule(u:Module){setModuleId(u.id);setModule(u);setText(blankText);setFile(null);setFileTitle('');setFileInput(n=>n+1);}
 const active=data?.students.filter(s=>s.status==='active')||[];const selected=data?.courses.find(c=>c.id===courseId);
 return <><div className="learning-toolbar" role="group" aria-label="Gestione formazione"><button className="button outline" aria-pressed={tab==='courses'} onClick={()=>setTab('courses')}>Corsi e materiali</button><button className="button outline" aria-pressed={tab==='access'} onClick={()=>setTab('access')}>Iscrizioni</button></div>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}{!data?<div className="booking-empty">{error?<button className="button outline" onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Riprova</button>:<p role="status">Caricamento…</p>}</div>:tab==='access'?<>
 <div className="learning-notice"><p>Il tutor crea gli account con email e password e li collega alle schede degli studenti. Durante la revisione il sito resta privato. Per aprire l’anteprima non serve creare un account studente.</p></div>
 <div className="registry-layout"><section><h2>Account della piattaforma</h2><p>Crea e modifica gli accessi dalla pagina account. Per assegnare i corsi, usa questa pagina.</p><a className="button dark" href="/gestione/account">Gestisci account e accessi</a><h2>Iscrizioni ai corsi</h2>{!data.enrollments.some(e=>e.status==='active')&&<p>Nessun corso assegnato.</p>}{data.enrollments.filter(e=>e.status==='active').map(e=><article key={e.student_id+e.course_id} className="registry-card"><h3>{data.students.find(s=>s.id===e.student_id)?.name}</h3><p>{data.courses.find(c=>c.id===e.course_id)?.title} · {labels[data.courses.find(c=>c.id===e.course_id)?.status||'draft']}</p><button className="button outline" disabled={busy} onClick={()=>save({kind:'enrollment',studentId:e.student_id,courseId:e.course_id,status:'revoked'})}>Revoca iscrizione</button></article>)}</section><section className="registry-editor"><h2>Anteprima studente e corsi</h2><label>Studente<select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Scegli studente</option>{active.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{studentId?<p><a className="button outline" href={'/studente?anteprima='+studentId}>Apri anteprima studente</a></p>:<p>Seleziona una scheda attiva per aprire l’anteprima. {!active.length&&<a href="/gestione/anagrafica">Registra prima uno studente.</a>}</p>}<hr/><h2>Assegna un corso</h2><form onSubmit={e=>{e.preventDefault();void save({kind:'enrollment',studentId,courseId:enrollCourseId,status:'active'});}}><label>Corso<select value={enrollCourseId} onChange={e=>setEnrollCourseId(e.target.value)}><option value="">Scegli corso</option>{data.courses.filter(c=>c.status!=='archived').map(c=><option key={c.id} value={c.id}>{c.title} · {labels[c.status]}</option>)}</select></label><p>Assegna tu il corso allo studente. Per mostrarne i contenuti devi rendere disponibili sia il corso sia i materiali; le bozze restano nascoste.</p><button className="button dark" disabled={busy||!studentId||!enrollCourseId}>Assegna corso</button></form></section></div></>:<>
 <div className="registry-layout"><section><div className="learning-toolbar"><h2>Corsi</h2><button className="button outline" disabled={busy} onClick={()=>{setCourseId('');setModuleId('');setCourse(blankCourse);setModule(blankModule);setText(blankText);}}>Nuovo corso</button></div>{!data.courses.length&&<div className="booking-empty"><p>Non hai ancora creato corsi. Quando ne crei uno, titolo, moduli e materiali restano in bozza finché non li rendi disponibili.</p></div>}{data.courses.map(c=><article key={c.id} className={'registry-card '+(c.id===courseId?'learning-selected':'')}><span className="booking-badge">{labels[c.status]}</span><h3>{c.title}</h3><p>{c.subject}</p><p>{data.modules.filter(u=>u.course_id===c.id).length} moduli · {data.enrollments.filter(e=>e.course_id===c.id&&e.status==='active').length} iscritti</p><button className="button outline" disabled={busy} onClick={()=>choose(c)}>Gestisci corso</button></article>)}</section>
 <section className="registry-editor"><h2>{course.id?'Modifica corso':'Nuovo corso'}</h2><form onSubmit={e=>{e.preventDefault();void save({kind:'course',...course},()=>{if(!course.id)setCourse(blankCourse);});}}><label>Titolo<input required minLength={2} maxLength={150} value={course.title} onChange={e=>setCourse({...course,title:e.target.value})}/></label><label>Materia / esame<input required minLength={2} maxLength={150} value={course.subject} onChange={e=>setCourse({...course,subject:e.target.value})}/></label><label>Descrizione<textarea maxLength={3000} value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/></label><label>Disponibilità<select value={course.status} onChange={e=>setCourse({...course,status:e.target.value})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>Il corso disponibile si vede soltanto dagli account degli iscritti autorizzati. Questa operazione non attiva prezzi o acquisti.</p><button className="button dark" disabled={busy}>Salva corso</button></form></section></div>
 {selected&&<section className="learning-course"><div className="learning-toolbar"><h2>Moduli · {selected.title}</h2><button className="button outline" aria-expanded={progressOpen} onClick={()=>setProgressOpen(!progressOpen)}>{progressOpen?'Chiudi avanzamento':'Avanzamento degli iscritti'}</button></div>{progressOpen&&<CourseProgress key={courseId} courseId={courseId}/>}<div className="learning-module-tabs">{data.modules.filter(u=>u.course_id===courseId).map(u=><button key={u.id} className="button outline" disabled={busy} aria-pressed={moduleId===u.id} onClick={()=>chooseModule(u)}>{u.position+1}. {u.title}</button>)}<button className="button outline" disabled={busy} onClick={()=>{setModuleId('');setModule({...blankModule,position:data.modules.filter(u=>u.course_id===courseId).length});setText(blankText);}}>Nuovo modulo</button></div><form className="learning-inline-form" onSubmit={e=>{e.preventDefault();void save({kind:'module',courseId,...module},()=>{if(!module.id)setModule(blankModule);});}}><label>Titolo del modulo<input required minLength={2} maxLength={150} value={module.title} onChange={e=>setModule({...module,title:e.target.value})}/></label><label>Posizione (da 0)<input type="number" min={0} max={999} required value={module.position} onChange={e=>setModule({...module,position:Number(e.target.value)})}/></label><button className="button dark" disabled={busy}>Salva modulo</button></form>
 {moduleId&&<><h3>Materiali · {data.modules.find(u=>u.id===moduleId)?.title}</h3>{!data.materials.some(m=>m.module_id===moduleId)&&<p>Il modulo non ha ancora materiali.</p>}{data.materials.filter(m=>m.module_id===moduleId).map(m=><MaterialRow key={m.id} material={m} busy={busy} save={save} edit={()=>setText({id:m.id,title:m.title,body:m.body,position:m.position,status:m.status})}/>)}<div className="registry-layout"><section className="registry-editor"><h3>{text.id?'Modifica spiegazione':'Nuova spiegazione'}</h3><form onSubmit={e=>{e.preventDefault();void save({kind:'material',moduleId,...text},()=>setText(blankText));}}><label>Titolo<input required minLength={2} maxLength={150} value={text.title} onChange={e=>setText({...text,title:e.target.value})}/></label><label>Testo<textarea className="learning-text-editor" required maxLength={30000} value={text.body} onChange={e=>setText({...text,body:e.target.value})}/></label><label>Posizione (da 0)<input type="number" min={0} max={999} value={text.position} onChange={e=>setText({...text,position:Number(e.target.value)})}/></label><label>Disponibilità<select value={text.status} onChange={e=>setText({...text,status:e.target.value})}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="registry-actions"><button className="button dark" disabled={busy}>Salva spiegazione</button>{text.id&&<button type="button" className="button outline" disabled={busy} onClick={()=>setText(blankText)}>Nuova spiegazione</button>}</div></form></section><section className="registry-editor"><h3>Carica file o video</h3><form onSubmit={upload}><label>Titolo<input required minLength={2} maxLength={150} value={fileTitle} onChange={e=>setFileTitle(e.target.value)}/></label><label>File<input key={fileInput} type="file" required accept="application/pdf,image/png,image/jpeg,video/mp4,video/webm" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><p>PDF, PNG, JPEG, MP4 o WebM, fino a 50 MB. Il file caricato resta in bozza.</p><button className="button dark" disabled={busy||!file}>{busy?'Operazione in corso…':'Carica in bozza'}</button></form></section></div></>}
 </section>}</> }</>;
}
function MaterialRow({material:m,busy,save,edit}:{material:Material;busy:boolean;save:(body:object)=>Promise<void>;edit:()=>void}){
 const [position,setPosition]=useState(m.position);const [title,setTitle]=useState(m.title);useEffect(()=>{setPosition(m.position);setTitle(m.title);},[m.position,m.title]);
 return <article className="registry-card"><h4>{m.title}</h4><p>{m.kind==='text'?'Spiegazione':m.kind==='video'?'Video':'File'} · {labels[m.status]}{m.filename?' · '+m.filename:''}</p><div className="learning-inline-form"><label>Titolo del materiale<input minLength={2} maxLength={150} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Posizione (da 0)<input type="number" min={0} max={999} value={position} onChange={e=>setPosition(Number(e.target.value))}/></label><button className="button outline" disabled={busy||position<0||position>999||!Number.isInteger(position)||title.trim().length<2||title.length>150} onClick={()=>save({kind:'material-status',id:m.id,status:m.status,position,title})}>Salva titolo e ordine</button>{m.kind!=='text'&&<a className="button outline" href={'/api/gestione/formazione/materiali?materiale='+m.id} target={m.kind==='video'?'_blank':undefined} rel={m.kind==='video'?'noreferrer':undefined}>{m.kind==='video'?'Apri video':'Scarica file'}</a>}{m.kind==='text'&&<button className="button outline" disabled={busy} onClick={edit}>Modifica testo</button>}{m.status!=='published'&&<button className="button dark" disabled={busy} onClick={()=>save({kind:'material-status',id:m.id,status:'published',position})}>Rendi disponibile</button>}{m.status==='published'&&<button className="button outline" disabled={busy} onClick={()=>save({kind:'material-status',id:m.id,status:'draft',position})}>Torna in bozza</button>}{m.status!=='archived'&&<button className="text-link" disabled={busy} onClick={()=>save({kind:'material-status',id:m.id,status:'archived',position})}>Archivia</button>}</div></article>;
}
