'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {templateFields,templateKinds,templateValues,type TemplateKind,type TutorTemplate} from '@/lib/management/templates';
export default function Templates(){
 const [models,setModels]=useState<TutorTemplate[]>([]),[selected,setSelected]=useState<TutorTemplate|null>(null),[kind,setKind]=useState<TemplateKind>('message'),[filter,setFilter]=useState('all'),[editor,setEditor]=useState(false),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[truncated,setTruncated]=useState(false);const id=useRef('');
 useEffect(()=>{const c=new AbortController();setLoading(true);fetch('/api/gestione/modelli',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as {templates:TutorTemplate[];truncated:boolean;error?:string};if(!r.ok)throw Error(d.error||'Modelli non disponibili.');return d;}).then(d=>{if(!c.signal.aborted){setModels(d.templates);setTruncated(d.truncated);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[reload]);
 function begin(m:TutorTemplate|null){setSelected(m);setKind(m?.kind||'message');id.current=m?.id||crypto.randomUUID();setEditor(true);setError('');setNotice('');}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setNotice('');const f=new FormData(e.currentTarget),content=Object.fromEntries(templateFields[kind].map(field=>[field.name,String(f.get(field.name)||'')]));try{const r=await fetch('/api/gestione/modelli',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.current,version:selected?.version??null,kind,name:f.get('name'),content,status:f.get('status')})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Modello non salvato.');setEditor(false);setNotice('Modello salvato. Nessun messaggio inviato o esercizio assegnato.');setReload(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const values=selected?templateValues(selected.kind,selected.content):{};
 return <><p>Salva testi da riutilizzare. Il modello non contiene destinatari, date, file o visibilità dello studente: li scegli quando prepari il contenuto. Evita dati personali nei testi riutilizzabili.</p><div className="learning-toolbar"><label>Tipo di modello<select disabled={busy} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tutti</option>{Object.entries(templateKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="button dark" disabled={busy} onClick={()=>begin(null)}>Nuovo modello</button><button className="button outline" disabled={busy||loading} onClick={()=>setReload(n=>n+1)}>Aggiorna elenco</button></div>{error&&<p role="alert" className="error">{error} I testi rimangono nel modulo. Se la versione è cambiata, riapri il modello dall’elenco.</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Caricamento…</p>}{truncated&&<p>Mostriamo i primi 200 modelli.</p>}<div className="registry-layout"><section aria-label="Modelli salvati">{!loading&&!models.length&&<p>Nessun modello salvato. Puoi crearne uno qui o dai moduli di compiti e piani.</p>}{models.filter(m=>filter==='all'||m.kind===filter).map(m=><article className="registry-card" key={m.id}><span className="booking-badge">{m.status==='active'?'Disponibile':'Archiviato'}</span><h2>{m.name}</h2><p>{templateKinds[m.kind]}</p><button className="button outline" disabled={busy} onClick={()=>begin(m)}>Apri modello</button></article>)}</section>{editor&&<section className="registry-editor"><h2>{selected?'Modifica modello':'Nuovo modello'}</h2><form key={id.current+':'+kind+':'+(selected?.version??'new')} onSubmit={save}><fieldset disabled={busy}><label>Nome del modello<input name="name" required minLength={2} maxLength={120} defaultValue={selected?.name||''}/></label><label>Tipo<select value={kind} disabled={!!selected} onChange={e=>setKind(e.target.value as TemplateKind)}>{Object.entries(templateKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{kind==='message'&&<p>Puoi scrivere {'{nome}'} e {'{materia}'}: vengono sostituiti quando prepari la bozza da una richiesta.</p>}{templateFields[kind].map(field=><label key={field.name}>{field.label}<textarea name={field.name} rows={field.max===160?2:5} required={field.required} maxLength={field.max} minLength={field.required&&field.max===160?2:undefined} defaultValue={values[field.name]||''}/></label>)}<label>Disponibilità<select name="status" defaultValue={selected?.status||'active'}><option value="active">Disponibile</option><option value="archived">Archiviato · conserva il testo</option></select></label><div className="registry-actions"><button className="button dark">{busy?'Salvataggio…':'Salva modello'}</button><button className="button outline" type="button" onClick={()=>setEditor(false)}>Chiudi modulo</button></div></fieldset></form></section>}</div></>;
}
