import { z } from 'zod';
import { createHash } from 'node:crypto';
import { bookingDb } from '@/lib/booking/runtime';
import { getAccount } from '@/lib/auth/session';
import { failure,LearningError,privateHeaders,sameOrigin,studentScope } from '@/lib/learning/access';
import { homeworkData } from '@/lib/homework/data';
import { discardUnusedFile,homeworkFile,putHomeworkFile,readHomeworkForm } from '@/lib/homework/files';
export async function GET(request:Request){try{const scope=await studentScope(request),selected=new URL(request.url).searchParams.get('studente')||scope.students[0]?.id;if(!selected)return Response.json({assignments:[],submissions:[],truncated:false,canSubmit:false},{headers:privateHeaders});if(!scope.students.some(s=>s.id===selected))throw new LearningError('Accesso non consentito.',403);const account=scope.preview?null:await getAccount(request);return Response.json({...await homeworkData(selected,true),canSubmit:account?.role==='student'&&!scope.preview},{headers:privateHeaders});}catch(e){return failure(e);}}
export async function POST(request:Request){let key:string|null=null;try{
 sameOrigin(request);const scope=await studentScope(request);if(scope.preview)throw new LearningError('L’anteprima è in sola lettura.',403);const account=await getAccount(request);if(!account||account.role!=='student')throw new LearningError('La consegna è riservata all’account studente. Il referente può consultare.',403);
 const f=await readHomeworkForm(request);const parsed=z.object({id:z.string().uuid(),assignmentId:z.string().uuid(),body:z.string().trim().max(10000)}).safeParse({id:f.get('id'),assignmentId:f.get('assignmentId'),body:f.get('body')||''});if(!parsed.success)throw new LearningError('Controlla il testo della consegna.');const p=parsed.data,db=bookingDb();
 const task=await db.prepare("SELECT id,student_id FROM homework_assignments WHERE id=? AND status='published'").bind(p.assignmentId).first<{id:string;student_id:string}>();if(!task||!scope.students.some(s=>s.id===task.student_id))throw new LearningError('Compito non disponibile.',403);
 const file=await homeworkFile(f.get('file'));if(!p.body&&!file)throw new LearningError('Scrivi una risposta o allega un file.');
 const hash=createHash('sha256').update(JSON.stringify([p.body,file?.hash||'',file?.filename||'',file?.mime||''])).digest('hex');
 const existing=await db.prepare('SELECT assignment_id,submitted_by,content_hash FROM homework_submissions WHERE id=?').bind(p.id).first<{assignment_id:string;submitted_by:string;content_hash:string}>();
 if(existing){if(existing.assignment_id===p.assignmentId&&existing.submitted_by===account.id&&existing.content_hash===hash)return Response.json({ok:true,id:p.id},{headers:privateHeaders});throw new LearningError('Il tentativo è già stato usato. Ricarica i compiti.',409);}
 if(file){key=`homework/submissions/${p.id}/${crypto.randomUUID()}`;await putHomeworkFile(key,file);}
 const result=await db.prepare(`INSERT INTO homework_submissions(id,assignment_id,submitted_by,attempt,body,object_key,filename,mime,size,content_hash,created_at) SELECT ?,a.id,?,COALESCE((SELECT MAX(attempt) FROM homework_submissions WHERE assignment_id=a.id),0)+1,?,?,?,?,?,?,? FROM homework_assignments a JOIN students s ON s.id=a.student_id JOIN account_student_access access ON access.student_id=s.id JOIN accounts actor ON actor.id=access.account_id WHERE a.id=? AND a.status='published' AND s.status='active' AND access.account_id=? AND access.status='active' AND actor.status='active' AND actor.role='student' AND actor.must_change_password=0 AND actor.auth_version=? AND (SELECT count(*) FROM homework_submissions WHERE assignment_id=a.id)<20 AND (NOT EXISTS(SELECT 1 FROM homework_submissions WHERE assignment_id=a.id) OR EXISTS(SELECT 1 FROM homework_submissions latest WHERE latest.assignment_id=a.id AND latest.attempt=(SELECT MAX(attempt) FROM homework_submissions WHERE assignment_id=a.id) AND latest.feedback_status='published' AND latest.review_status='revise')) ON CONFLICT DO NOTHING`).bind(p.id,account.id,p.body,key,file?.filename||null,file?.mime||null,file?.size||null,hash,new Date().toISOString(),p.assignmentId,account.id,account.auth_version).run();
 if(!result.meta.changes){const saved=await db.prepare('SELECT submitted_by,content_hash FROM homework_submissions WHERE id=? AND assignment_id=?').bind(p.id,p.assignmentId).first<{submitted_by:string;content_hash:string}>();if(!saved||saved.submitted_by!==account.id||saved.content_hash!==hash)throw new LearningError('Accesso o compito aggiornato. Un nuovo tentativo è possibile solo dopo una richiesta di revisione, fino a 20 consegne.',409);}
 await discardUnusedFile(key);return Response.json({ok:true,id:p.id},{headers:privateHeaders});
 }catch(e){await discardUnusedFile(key);return failure(e);}}
