"use client";
import WhatsAppIcon from '@/components/site/whatsapp-icon';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { consultationDate,consultationTime,consultationDay,type ConsultationSlot } from '@/lib/consultations';
import { schoolSubjects,universitySubjects } from '@/lib/catalog';
import { studio } from '@/lib/public-offer';
import type { Assessment } from './types';
import ConsultationDays from './consultation-days';
import ConsultationTimes from './consultation-times';
import {useSitePreview} from './site-preview-context';
type Appointment={starts_at:string;ends_at:string;mode:string;status:string};
export default function ConsultationBooking({subject='Matematica',assessment=null,standalone=false,referralCode='',initialSlot=''}:{subject?:string;assessment?:Assessment|null;standalone?:boolean;referralCode?:string;initialSlot?:string}){
 const Heading=standalone?'h1':'h2';
 const preview=useSitePreview();
 const [slots,setSlots]=useState<ConsultationSlot[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(''),[day,setDay]=useState(''),[mode,setMode]=useState('Online'),[busy,setBusy]=useState(false),[appointment,setAppointment]=useState<Appointment|null>(null),[truncated,setTruncated]=useState(false);
 const [draft,setDraft]=useState<Record<string,string>>({name:'',email:'',phone:'',message:'',subject,studentType:universitySubjects.includes(subject)?'Università':'Superiori',consent:''});
 const id=useRef<string|null>(null),payload=useRef<string|null>(null),[uncertain,setUncertain]=useState(false);
 const initialApplied=useRef(false),[slotNotice,setSlotNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/incontri',{cache:'no-store'}),d=await r.json() as {slots:ConsultationSlot[];truncated:boolean;error?:string};if(!r.ok)throw Error(d.error);setSlots(d.slots);setTruncated(d.truncated);if(initialSlot&&!initialApplied.current){initialApplied.current=true;const slot=d.slots.find(s=>s.id===initialSlot);if(slot){setSelected(slot.id);setDay(consultationDay(slot.starts_at));setMode(slot.mode==='Lodi'?'Lodi':'Online');}else setSlotNotice('Questo orario non è più disponibile. Scegli un altro incontro oppure scrivimi.');}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(!preview)void Promise.resolve().then(load);},[preview]);
 const days=[...new Set(slots.map(s=>consultationDay(s.starts_at)))],active=days.includes(day)?day:days[0],chosen=slots.find(s=>s.id===selected);
 async function book(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!chosen)return;const form=new FormData(event.currentTarget);id.current??=crypto.randomUUID();setBusy(true);setError('');setUncertain(true);
  payload.current??=JSON.stringify({id:id.current,slotId:chosen.id,name:form.get('name'),email:form.get('email'),phone:form.get('phone'),subject:form.get('subject'),studentType:form.get('studentType'),message:form.get('message'),...(String(form.get('referralCode')||'').trim()?{referralCode:String(form.get('referralCode')).trim()}:{}),mode:chosen.mode==='Entrambe'?mode:chosen.mode,consent:form.get('consent')==='on',website:form.get('website'),assessment});
  try{const r=await fetch('/api/incontri',{method:'POST',headers:{'Content-Type':'application/json'},body:payload.current});const d=await r.json() as {appointment:Appointment;error?:string};if(!r.ok){if(r.status===409||r.status===400||r.status===403){setUncertain(false);id.current=null;payload.current=null;if(r.status===409){setSelected('');void load();}}throw Error(d.error||'Prenotazione non riuscita.');}setAppointment(d.appointment);setUncertain(false);}catch(e){setError((e as Error).message||'Conferma non ricevuta. Riprova con gli stessi dati.');}finally{setBusy(false);}}
 if(preview)return <><Heading id="dialog-title">Prenota un incontro gratuito</Heading><p>15 minuti per conoscerci e guardare il programma, online o a Lodi.</p><section className="booking-empty"><h2>Calendario in preparazione</h2><p>Potrai scegliere e confermare un orario all’apertura del sito.</p><a className="button outline" href="/catalogo">Guarda le lezioni</a></section></>;
 if(appointment?.status==='cancelled')return <section className="success" aria-live="polite"><Heading id="dialog-title">Incontro cancellato</Heading><p>Questo incontro risulta cancellato. Scrivimi per concordare un nuovo orario.</p><a className="button dark" href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Scrivimi su WhatsApp</a></section>;
 if(appointment)return <section className="success" aria-live="polite"><Heading id="dialog-title">Incontro prenotato</Heading><p><strong>{consultationDate(appointment.starts_at)}</strong><br/>{consultationTime(appointment.starts_at)}–{consultationTime(appointment.ends_at)} · {appointment.mode==='Lodi'?'In presenza a Lodi':'Online'}</p><p>{appointment.mode==='Lodi'?`${studio.address}, ${studio.city}.`:'Ti comunicherò il collegamento alla videochiamata prima dell’incontro.'}</p><p>15 minuti gratuiti per conoscerci e guardare il programma. Non è una lezione di prova e non devi pagare nulla.</p><p className="form-note">Non viene inviata un’email automatica. Annota giorno e orario. Per spostare o cancellare l’incontro, scrivimi.</p><a className="button dark" href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Scrivimi su WhatsApp</a></section>;
 return <><Heading id="dialog-title">Prenota un incontro gratuito</Heading><p>Scegli giorno e orario per i 15 minuti gratuiti dedicati al tuo programma.</p><p className="form-note">Prenota con almeno 24 ore di anticipo. Gli orari seguono il fuso di Roma. La conferma è immediata, senza pagamenti.</p>{slotNotice&&<p className="form-note" role="status">{slotNotice}</p>}{error&&<p className="error" role="alert">{error}</p>}{loading&&!slots.length?<p role="status">Caricamento degli orari…</p>:!slots.length?<div className="booking-empty"><p>Non ci sono ancora orari disponibili per l’incontro gratuito.</p><p>Puoi <a className="text-link" href={`/contatti?materia=${encodeURIComponent(subject)}${referralCode?'&invito='+encodeURIComponent(referralCode):''}`}>lasciarmi un messaggio</a> oppure chiedermi un orario su WhatsApp.</p><div className="booking-empty-actions"><button className="button outline" onClick={()=>{setError('');void load();}}>Aggiorna il calendario</button><a className="button dark" href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Chiedi un orario su WhatsApp</a></div></div>:<form onSubmit={book} onChange={e=>{const f=new FormData(e.currentTarget),values:Record<string,string>={};for(const [k,v] of f)if(typeof v==='string')values[k]=v;if(chosen)values.consent=f.get('consent')==='on'?'on':'';setDraft(current=>({...current,...values}));}}>
 <fieldset disabled={busy||uncertain} className="consultation-fields"><legend>Scegli giorno e orario</legend><div className="consultation-picker"><ConsultationDays days={days} selected={active} onSelect={d=>{setDay(d);setSelected('');}}/><div className="consultation-day-times"><h3>{consultationDate(active+'T12:00:00.000Z')}</h3><ConsultationTimes key={active} slots={slots.filter(s=>consultationDay(s.starts_at)===active)} selected={selected} onSelect={s=>{setSelected(s?.id||'');if(s)setMode(s.mode==='Lodi'?'Lodi':'Online');}}/></div></div>{truncated&&<p>Mostriamo i primi 1300 orari disponibili.</p>}
 {chosen&&<><div className="consultation-selection"><strong>{consultationDate(chosen.starts_at)} · {consultationTime(chosen.starts_at)}</strong>{chosen.mode==='Entrambe'?<label>Come preferisci incontrarci?<select value={mode} onChange={e=>setMode(e.target.value)}><option value="Online">Online</option><option value="Lodi">In presenza a Lodi</option></select></label>:<p>{chosen.mode==='Lodi'?'In presenza a Lodi':'Online'}</p>}{(chosen.mode==='Lodi'||chosen.mode==='Entrambe'&&mode==='Lodi')&&<p>{studio.address}, {studio.city}. L’orario scelto è riservato all’incontro gratuito.</p>}</div><div className="form-grid"><label>Nome e cognome<input defaultValue={draft.name} name="name" autoComplete="name" required minLength={2} maxLength={100}/></label><label>Email<input defaultValue={draft.email} name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Telefono (facoltativo)<input defaultValue={draft.phone} name="phone" type="tel" autoComplete="tel" maxLength={40}/></label><label>Studente delle<select name="studentType" defaultValue={draft.studentType}><option>Superiori</option><option>Università</option></select></label><label className="full">Materia / esame<select name="subject" defaultValue={draft.subject}>{[...schoolSubjects,...universitySubjects,'Altro esame'].map(s=><option key={s}>{s}</option>)}</select></label><label className="full">Cosa devi preparare? (facoltativo)<textarea defaultValue={draft.message} name="message" maxLength={1000} placeholder="Puoi indicare gli argomenti o la data della verifica o dell’esame."/></label></div><label>Codice invito (facoltativo)<input defaultValue={draft.referralCode??referralCode} name="referralCode" maxLength={19} autoComplete="off"/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{assessment&&<p className="form-note">La prenotazione include il risultato del test: {assessment.test}.</p>}<p className="form-privacy">Uso questi dati per gestire l’incontro e ricontattarti. Se sei minorenne, compila con un genitore e usa il suo recapito.</p><label className="checkbox"><input defaultChecked={draft.consent==='on'} name="consent" type="checkbox" required/>Ho letto queste informazioni e acconsento all’uso dei dati per l’incontro.</label></>}
 </fieldset>{chosen&&<button className="button dark" disabled={busy} type="submit">{busy?'Conferma in corso…':uncertain?'Verifica e riprova la prenotazione':'Conferma l’incontro gratuito'}</button>}{uncertain&&!busy&&<p role="status">La conferma non è ancora arrivata. Riprova con gli stessi dati: non verrà creata una seconda prenotazione.</p>}</form>}</>;
}
