'use client';
import {useState} from 'react';
import {examEstimate,recommendedLessons,type ExamPlan} from '@/lib/exam-preparation';
import {bookingRules} from '@/lib/catalog';
export default function ExamPlanner({plan}:{plan:ExamPlan}){
 const [indices,setIndices]=useState(()=>plan.blocks.map((_,i)=>i)),[extra,setExtra]=useState(0);
 const estimate=examEstimate(plan,indices,extra);
 const contact='/contatti?'+new URLSearchParams({materia:plan.name,piano:plan.slug,argomenti:indices.join(','),extra:String(extra)});
 return <section className="exam-planner" aria-labelledby="piano-title"><div className="exam-plan-intro"><p className="subject-audience">Ripasso dopo aver seguito il corso</p><h2 id="piano-title">Da {recommendedLessons(plan)} lezioni consigliate</h2><p>Questo è il minimo consigliato per lo schema qui sotto, con basi già presenti e studio tra gli incontri. Nel primo incontro guardiamo il programma del docente, gli esercizi e la data dell’appello: il numero adatto a te può cambiare.</p><p>Puoi saltare gli argomenti che conosci, fare meno lezioni o aggiungerne. Non devi acquistare l’intero piano.</p></div><div className="exam-plan-layout"><fieldset className="exam-blocks"><legend>Quali argomenti vuoi ripassare?</legend>{plan.blocks.map((block,i)=><label key={block.title}><input type="checkbox" checked={indices.includes(i)} onChange={e=>setIndices(old=>e.target.checked?[...old,i].sort((a,b)=>a-b):old.filter(n=>n!==i))}/><span><b>{block.title}</b><small>{block.lessons} {block.lessons===1?'lezione consigliata':'lezioni consigliate'}</small></span></label>)}<label className="exam-extra"><span>Lezioni aggiuntive di esercizio</span><select value={extra} onChange={e=>setExtra(Number(e.target.value))}>{Array.from({length:11},(_,i)=><option key={i} value={i}>{i}</option>)}</select></label><button className="text-link" type="button" onClick={()=>{setIndices(plan.blocks.map((_,i)=>i));setExtra(0);}}>Ripristina la proposta</button></fieldset><aside className="exam-estimate" aria-live="polite" aria-atomic="true"><h3>Il piano che hai selezionato</h3>{estimate.lessons?<><p className="exam-count"><strong>{estimate.lessons}</strong> {estimate.lessons===1?'lezione':'lezioni'} da {bookingRules.lessonMinutes} minuti</p><p><b>{estimate.individual} €</b> individuale{estimate.packages?` · ${estimate.packages} ${estimate.packages===1?'pacchetto':'pacchetti'} da 5 a 95 €${estimate.singles?` + ${estimate.singles} ${estimate.singles===1?'singola':'singole'} a 20 €`:''}`:' · 20 € per lezione'}.</p><p><b>{estimate.group} € a persona</b> in un gruppo compatibile di 2–4: 15 € a lezione.</p><p className="offer-note">È un conto orientativo, senza prenotazioni o pagamenti. Prima concordiamo programma, numero di incontri e condizioni dei pacchetti. Il credito invito non si somma al pacchetto.</p><a className="button dark" href={contact}>Parliamo di questo piano</a></>:<p>Seleziona un argomento o aggiungi una lezione di esercizio per vedere il conto.</p>}<a className="text-link calendar-link" href={'/incontro?'+new URLSearchParams({materia:plan.name})}>Incontro gratuito di 15 minuti</a></aside></div></section>;
}
