'use client';
import {useState} from 'react';
import {Sigma,Code2,Network} from 'lucide-react';
const programmes=[
 {name:'Matematica',icon:Sigma,intro:'Scegliamo gli esercizi dalle prove e dal programma della tua classe.',modules:[['Funzioni e studio di funzione','Dominio, limiti, continuità e lettura dei grafici. Prima controlliamo le basi di algebra che servono per svolgere gli esercizi.'],['Derivate e problemi','Derivate, tangenti, massimi e minimi. Lavoriamo anche su come impostare un problema e controllare il risultato.'],['Integrali e altri argomenti del programma','Integrali, aree, probabilità o geometria, se presenti nel tuo programma. Il tempo dipende da ciò che hai già studiato.'],['Una prova da svolgere e correggere','Provi a risolvere gli esercizi con un tempo concordato. Poi rivediamo metodo, passaggi, errori e gestione del tempo.']]},
 {name:'Informatica',icon:Code2,intro:'Partiamo dai linguaggi, dagli strumenti e dalle tracce che usate a scuola.',modules:[['Programmazione','Algoritmi, strutture dati e organizzazione del codice, nel linguaggio del tuo corso. Eseguiamo il programma e proviamo casi diversi.'],['Database e SQL','Dal testo del problema al modello dei dati, alle tabelle e alle query. Controlliamo relazioni, vincoli e risultati.'],['Progetti e applicazioni','Riprendiamo i collegamenti tra codice, dati e applicazione, quando rientrano nel programma. Guardiamo anche come spiegare le scelte fatte.'],['Una traccia completa','Leggiamo la richiesta, dividiamo il lavoro e realizziamo la soluzione. La correggiamo guardando sia il risultato sia il ragionamento.']]},
 {name:'Sistemi e Reti',icon:Network,intro:'Seguiamo gli argomenti e gli esercizi previsti dal tuo indirizzo.',modules:[['Reti e indirizzamento','Protocolli, TCP/IP, indirizzi e sottoreti. Alterniamo ripasso ed esercizi di progettazione.'],['Servizi e sicurezza','Riprendiamo i servizi di rete e le misure di sicurezza affrontate a scuola, collegandoli a casi concreti.'],['Progettare e motivare una soluzione','Leggiamo i requisiti, proponiamo una rete e spieghiamo le scelte: dispositivi, servizi e protezioni.'],['Esercitazione e discussione','Affrontiamo una traccia del tuo programma e discutiamo la soluzione, anche a voce. Rivediamo i punti che restano poco chiari.']]},
];
export default function MaturityProgramme(){const [selected,setSelected]=useState(0),p=programmes[selected];return <section className="maturity-programme"><h2>Il programma, materia per materia</h2><p>Questi sono gli argomenti su cui possiamo lavorare. Li confrontiamo con il programma effettivo della tua classe: non devi ripassare tutto se ti servono solo alcuni punti.</p><div className="maturity-subjects" role="group" aria-label="Materia per il ripasso">{programmes.map((s,i)=><button className="button outline" key={s.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}><s.icon size={20} aria-hidden="true"/>{s.name}</button>)}</div><div className="reading-callout" aria-live="polite"><h3>{p.name}</h3><p>{p.intro}</p>{p.modules.map(([title,text],i)=><details key={p.name+title} suppressHydrationWarning open={i===0}><summary>{title}</summary><p>{text}</p></details>)}</div></section>;}
