"use client";
import { useState } from 'react';

export default function StudyGraphic() {
 const [mode,setMode]=useState<'math'|'code'>('math');
 const [value,setValue]=useState(1);
 const number=(n:number)=>new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(n);
 const points=Array.from({length:101},(_,i)=>{const x=(i-50)/12;return `${40+i*4.4},${270-value*x*x*16}`;}).join(' ');
 return <div className="study-scene"><div className="study-window"><div className="exercise-toolbar"><div className="graphic-tabs"><button aria-pressed={mode==='math'} onClick={()=>setMode('math')}>Matematica</button><button aria-pressed={mode==='code'} onClick={()=>setMode('code')}>Informatica</button></div></div>{mode==='math'?<><div className="graph-title"><span>{value===0?'Retta y = 0':'Grafico della parabola'}</span><strong>y = {value.toFixed(1)}x²</strong></div><svg viewBox="0 0 520 340" role="img" aria-label={`Grafico di y uguale ${value} x al quadrato`}><defs><pattern id="study-grid" width="44" height="44" patternUnits="userSpaceOnUse"><path d="M 44 0 L 0 0 0 44" fill="none" stroke="#ffffff12"/></pattern><clipPath id="graph-clip"><rect x="20" y="10" width="480" height="310"/></clipPath></defs><rect width="520" height="340" fill="url(#study-grid)"/><path d="M20 270H500 M260 20V320" stroke="#ffffff55"/><text x="492" y="291" fill="#a9b6cd">x</text><text x="275" y="25" fill="#a9b6cd">y</text><g clipPath="url(#graph-clip)"><polyline points={points} fill="none" stroke="#a8c6ff" strokeWidth="4" strokeLinecap="round"/></g><circle cx="260" cy="270" r="6" fill="#fff"/></svg><label className="graph-control">Cambia il coefficiente <output>a = {value.toFixed(1)}</output><input aria-label="Coefficiente della parabola" type="range" min="-2" max="2" step="0.1" value={value} onInput={e=>setValue(Number(e.currentTarget.value))} onChange={e=>setValue(Number(e.target.value))}/></label><div className="graphic-explanation"><b>Un passaggio dell’esercizio</b><p>Con x = 2, il quadrato è 4. Quindi y = {number(value)} × 4 = {number(value*4)}.</p><p>{value===0?'Con a = 0, y è sempre zero: il grafico è una retta sull’asse x.':value<0?'Il coefficiente è negativo: la parabola si apre verso il basso.':'Il coefficiente è positivo: la parabola si apre verso l’alto.'}</p></div></>:<div className="code-example"><p>Esempio di ciclo</p><pre><code><span>const</span> numeri = [2, 4, 6];{'\n\n'}<span>for</span> (const n of numeri) {'{'}{'\n'}  console.log(n * {value.toFixed(1)});{'\n'}{'}'}</code></pre><div className="code-output"><span>Risultato</span><strong>{[2,4,6].map(n=>(n*value).toFixed(1)).join('   ')}</strong></div><label className="graph-control">Moltiplicatore <output>{value.toFixed(1)}</output><input aria-label="Moltiplicatore" type="range" min="-2" max="2" step="0.1" value={value} onInput={e=>setValue(Number(e.currentTarget.value))} onChange={e=>setValue(Number(e.target.value))}/></label><div className="graphic-explanation"><b>Cosa fa questo ciclo</b><p>Prende 2, poi 4, poi 6. Ogni volta moltiplica il numero per {number(value)} e stampa il risultato. Il primo calcolo è 2 × {number(value)} = {number(2*value)}.</p></div></div>}</div></div>;
}
