'use client';
import { useEffect,useState } from 'react';
type Notice={id:string;recipient:string;subject:string;body:string;status:string;error?:string;created_at:string};
const labels:Record<string,string>={superseded:'Sostituita da una modifica successiva',prepared:'Anteprima · invio non attivo',queued:'In attesa di invio',sending:'Invio in verifica',sent:'Invio accettato dal servizio email',failed:'Invio non confermato',suppressed:'Invio disattivato',manual_review:'Esito da verificare manualmente'};
export default function Log(){const [data,setData]=useState<{notifications:Notice[];ready:boolean;from:string}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function load(){try{const r=await fetch('/api/gestione/notifiche');const d=await r.json() as {notifications:Notice[];ready:boolean;from:string;error?:string};if(!r.ok)throw Error(d.error||'Registro non disponibile.');setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function retry(id:string){setBusy(id);setError('');try{const r=await fetch('/api/gestione/notifiche',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <>{data&&<div className="notification-setup"><strong>{data.ready?'Invio automatico attivo':'Invio email da collegare'}</strong><p>Mittente: {data.from}</p>{!data.ready&&<p>Per ora le email vengono salvate come anteprime. Prima di inviarle devi collegare il servizio email e verificare il dominio. Attivare gli invii non spedisce le anteprime già salvate.</p>}<p>Ogni messaggio va a un solo destinatario. Non mostra i contatti degli altri studenti.</p></div>}{error&&<p role="alert" className="error">{error}</p>}{!data?<p role="status">Caricamento…</p>:!data.notifications.length?<p>Nessuna notifica ancora generata. Conferme, modifiche e cancellazioni compariranno qui.</p>:<section className="notification-list">{data.notifications.map(n=><article className="registry-card" key={n.id}><span className="booking-badge">{labels[n.status]||n.status}</span><h2>{n.subject}</h2><p>{n.recipient} · {new Intl.DateTimeFormat('it-IT',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(n.created_at))}</p>{n.error&&<p>{n.error}</p>}<details><summary>Leggi il messaggio</summary><pre className="notification-body">{n.body}</pre></details>{data.ready&&['failed','queued'].includes(n.status)&&<button className="button outline" disabled={!!busy} onClick={()=>retry(n.id)}>{busy===n.id?'Verifica…':'Riprova invio'}</button>}</article>)}</section>}</>;
}
