'use client';
import { useEffect,useState } from 'react';
type Payment={testMode:boolean;status:string;lesson_status:string;payment_method:string;starts_at:string;ends_at:string;mode:string;subject:string;amount:number;payment_deadline:string};
const date=(s:string)=>new Intl.DateTimeFormat('it-IT',{dateStyle:'full',timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(s));
export default function Page(){
 const [payment,setPayment]=useState<Payment|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const id=new URLSearchParams(location.search).get('saldo');const token=location.hash.slice(1);
 async function load(){try{if(!id||!token)throw Error('Il link è incompleto. Chiedi a Francesco il tuo link personale.');const r=await fetch(`/api/lesson-payment?id=${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json() as Payment & {error?:string;url:string};if(!r.ok)throw Error(d.error||'Questo link non è disponibile.');if(active){setPayment(d);setError('');if(['pending','awaiting'].includes(d.status)&&d.lesson_status==='planned')timer=setTimeout(load,10000);}}catch(e){if(active){setError((e as Error).message);timer=setTimeout(load,15000);}}finally{if(active)setLoading(false);}}
 load();return()=>{active=false;clearTimeout(timer);};},[]);
 async function pay(){setBusy(true);setError('');try{const id=new URLSearchParams(location.search).get('saldo');const r=await fetch('/api/lesson-payment',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${location.hash.slice(1)}`},body:JSON.stringify({id})});const d=await r.json() as Payment & {error?:string;url:string};if(!r.ok)throw Error(d.error);location.assign(d.url);}catch(e){setError((e as Error).message);setBusy(false);}}
 const paid=payment&&['paid','manual_paid'].includes(payment.status);const closed=payment&&(payment.lesson_status!=='planned'||payment.status==='expired');
 return <><header><a className="brand" href="/"><img className="brand-logo" src="/francesco-fracchia-logo.png" alt="Francesco Fracchia" width={2172} height={724}/></a></header><main className="wrap booking-page"><h1>La tua lezione</h1>{payment?.testMode?<p>Modalità prova: nessun addebito reale.</p>:<p>Il pagamento con carta si apre su Stripe.</p>}{loading?<p role="status">Caricamento…</p>:payment&&<section className="booking-status"><span className="booking-badge">{paid?'Saldo ricevuto':payment.status==='payment_review'?'Pagamento da verificare':payment.lesson_status==='cancelled'?'Appuntamento cancellato':closed?'Prenotazione scaduta':'Posto riservato'}</span><h2>{payment.subject}</h2><p>{date(payment.starts_at)} · {payment.mode} · 55 minuti</p><p className="lesson-payment-price">{payment.amount/100} €</p>{paid?<p>Il tuo saldo è registrato.{['expired','cancelled'].includes(payment.lesson_status)?' Contatta Francesco per verificare l’appuntamento.':' Se fai parte di un gruppo, Francesco verifica anche i saldi degli altri partecipanti.'}</p>:payment.status==='payment_review'?<p>Il pagamento richiede una verifica di Francesco. Non effettuare un secondo pagamento.</p>:payment.lesson_status==='cancelled'?<p>L’appuntamento è stato cancellato. Se hai già pagato, contatta Francesco per accordarti sul saldo versato.</p>:closed?<p>Il termine è passato. Contatta Francesco per concordare un nuovo appuntamento.</p>:payment.payment_method==='online'?<><p>Pagamento entro <strong>{date(payment.payment_deadline)}</strong>.</p><p>Se il collegamento al pagamento scade, puoi riaprirlo fino al termine indicato. Conserva questo link per controllare il saldo.</p><button className="button dark" disabled={busy} onClick={pay}>{busy?'Apertura…':`Paga ${payment.amount/100} €${payment.testMode?" · prova":""}`}</button></>:<p>Pagamento concordato con {payment.payment_method==='pos'?'POS':'contanti'}, prima di iniziare.</p>}</section>}{error&&<p role="alert" className="error">{error}</p>}<a className="text-link" href="/studente?vista=lezioni">Apri area studente</a><p><a className="text-link" href="/">Torna al sito</a></p></main></>;
}
