'use client';
import { useState } from 'react';
export type AppointmentEvent={id:string;version:number;starts_at:string;mode:string;notes?:string;series_id?:string;name:string;status:string};
const part=(s:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('en-CA',{...options,timeZone:'Europe/Rome'}).format(new Date(s));
export default function Actions({appointment:a,onSaved,onBusyChange}:{appointment:AppointmentEvent;onSaved:()=>Promise<void>;onBusyChange?:(busy:boolean)=>void}){
 const [action,setAction]=useState<''|'modify'|'cancel'>('');const [date,setDate]=useState(part(a.starts_at,{year:'numeric',month:'2-digit',day:'2-digit'}));const [time,setTime]=useState(part(a.starts_at,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}));const [mode,setMode]=useState(a.mode);const [notes,setNotes]=useState(a.notes||'');const [busy,setBusyState]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState('');
 const setBusy=(value:boolean)=>{setBusyState(value);onBusyChange?.(value);};
 const [now]=useState(()=>Date.now());
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/gestione/appuntamenti',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,version:a.version,entity:a.series_id?'lesson':'booking',action,date,time,mode,notes})});const d=await r.json() as {error?:string;refundReview?:boolean};if(!r.ok)throw Error(d.error||'Aggiornamento non riuscito.');setResult(d.refundReview?'Appuntamento cancellato. Verifica il saldo e concorda l’eventuale rimborso.':'Appuntamento aggiornato. Le comunicazioni sono nel registro notifiche.');setAction('');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(Date.parse(a.starts_at)<=now||!['planned','confirmed','pending','awaiting_payment','payment_review'].includes(a.status))return null;
 return <div className="appointment-actions">{!action?<div className="registry-actions"><button className="button outline" onClick={()=>setAction('modify')}>Sposta / modifica</button><button className="text-link" onClick={()=>setAction('cancel')}>Cancella appuntamento</button></div>:<form onSubmit={save}><h4>{action==='cancel'?'Cancella questo appuntamento':'Modifica questo appuntamento'}</h4>{action==='modify'?<><div className="form-grid"><label>Nuova data<input required type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label>Nuovo orario (Roma)<input required type="time" value={time} onInput={e=>setTime(e.currentTarget.value)} onChange={e=>setTime(e.target.value)}/></label></div><label>Modalità<select value={mode} onChange={e=>setMode(e.target.value)}><option>Online</option><option>Lodi</option></select></label>{a.series_id&&<label>Note interne<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>}</>:<p>L’orario tornerà disponibile e la cancellazione resterà nello storico. I saldi già ricevuti restano registrati. Questa operazione non esegue rimborsi.</p>}<p>La comunicazione riguarda solo questa lezione, anche se appartiene a una serie.</p><div className="registry-actions"><button className="button dark" disabled={busy}>{busy?'Salvataggio…':action==='cancel'?'Conferma cancellazione':'Salva modifiche'}</button><button type="button" className="button outline" disabled={busy} onClick={()=>setAction('')}>Annulla</button></div></form>}{error&&<p className="error" role="alert">{error}</p>}{result&&<p role="status">{result}</p>}</div>;
}
