'use client';
import { useState } from 'react';
export type Payment={id:string;name:string;email:string;amount:number;status:string;paid_at?:string;package_status?:string|null};
const labels:Record<string,string>={awaiting:'Da pagare',pending:'Pagamento aperto',paid:'Pagato con Stripe',manual_paid:'Saldo registrato da te',expired:'Termine scaduto',payment_review:'Pagamento da verificare'};
export default function Saldos({lessonId,method,payments,onSaved,onBusyChange,readOnly=false}:{lessonId:string;method:string;payments:Payment[];onSaved:()=>Promise<void>;onBusyChange?:(busy:boolean)=>void;readOnly?:boolean}){
 const [links,setLinks]=useState<Record<string,string>>({});const [busy,setBusyState]=useState('');const [error,setError]=useState('');
 const setBusy=(value:string)=>{setBusyState(value);onBusyChange?.(!!value);};
 async function link(p?:Payment){setError('');setBusy(p?.id||'new');try{const r=await fetch('/api/gestione/link-pagamento',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId,paymentId:p?.id})});const d=await r.json() as {error?:string;url:string;paymentId:string};if(!r.ok)throw Error(d.error);setLinks({...links,[d.paymentId]:d.url});if(!p)await onSaved();try{await navigator.clipboard.writeText(d.url);}catch{/* A selectable URL remains available when clipboard access is denied. */}}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function check(paymentId?:string,action?:string){setBusy('check');setError('');try{const r=await fetch('/api/gestione/saldi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lessonId,paymentId,action})});const d=await r.json() as {error?:string;url:string;paymentId:string};if(!r.ok)throw Error(d.error);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <div className="lesson-saldos">{!readOnly&&!payments.length&&method==='online'&&<button className="button outline" disabled={!!busy} onClick={()=>link()}>Prepara link individuale · 20 €</button>}{payments.map(p=><div className="participant-saldo" key={p.id}><div><strong>{p.name}</strong><p>{p.email}</p><p>{p.amount/100} €{payments.length>1?' a persona':''} · {p.package_status==='applied'?'Coperta dal pacchetto':p.package_status==='returned'?'Lezione restituita al pacchetto':labels[p.status]||p.status}</p><p>{p.package_status?'La quota di 19 € è attribuita al pacchetto; il saldo di 95 € è registrato una sola volta nella gestione pacchetti.':''}</p></div>{!readOnly&&method==='online'&&['awaiting','pending'].includes(p.status)&&<button className="button outline" disabled={!!busy} onClick={()=>link(p)}>{busy===p.id?'Preparazione…':'Copia link di pagamento'}</button>}{!readOnly&&p.status==='payment_review'&&<button className="button outline" disabled={!!busy} onClick={()=>check(p.id,'approve-review')}>Accetta pagamento tardivo</button>}{!readOnly&&['pos','cash'].includes(method)&&p.status==='awaiting'&&<button className="button outline" disabled={!!busy} onClick={()=>check(p.id)}>Registra saldo ricevuto</button>}{links[p.id]&&<label className="payment-link-label">Link personale da condividere<input readOnly value={links[p.id]} onFocus={e=>e.target.select()}/></label>}</div>)}{!readOnly&&method==='online'&&payments.some(p=>p.status==='expired')&&payments.some(p=>['paid','manual_paid','payment_review'].includes(p.status))&&<button className="button outline" disabled={!!busy} onClick={()=>check(undefined,'allow-pos')}>Concorda saldo residuo con POS</button>}{!readOnly&&payments.some(p=>['pending','awaiting'].includes(p.status))&&method==='online'&&<button className="text-link" disabled={!!busy} onClick={()=>check()}>{busy==='check'?'Verifica…':'Aggiorna saldi da Stripe'}</button>}{error&&<p role="alert" className="error">{error}</p>}</div>;
}
