import { noticeStatements,dispatchAppointmentNotices } from '@/lib/notifications/appointments';
import { bookingDb,paymentConfig,stripe } from './runtime';
import { deadlinePassed } from './payment-policy';
export async function reconcileBooking(id:string){const db=bookingDb();const b=await db.prepare('SELECT b.status,b.version,b.stripe_session,s.starts_at FROM bookings b JOIN booking_slots s ON s.id=b.slot_id WHERE b.id=?').bind(id).first<{status:string;version:number;stripe_session:string|null;starts_at:string}>();if(!b||!['pending','awaiting_payment'].includes(b.status)||!b.stripe_session||!paymentConfig().ready)return;
 const session=await stripe(`checkout/sessions/${encodeURIComponent(b.stripe_session)}?expand%5B%5D=payment_intent.latest_charge`) as unknown as {id:string;livemode:boolean;payment_status:string;amount_total:number;currency:string;status:string;metadata:{booking_id:string};payment_intent?:{latest_charge?:{created:number}}};
 if(session.livemode!==!!paymentConfig().live||session.metadata.booking_id!==id||session.amount_total!==2000||session.currency!=='eur')return;
 let next:string|null=null;
 if(session.payment_status==='paid'){const paidAt=session.payment_intent?.latest_charge?.created;next=!paidAt||paidAt*1000>Date.parse(b.starts_at)-3600000?'payment_review':'confirmed';}
 else if(deadlinePassed(b.starts_at)){if(session.status==='open'){await stripe(`checkout/sessions/${encodeURIComponent(session.id)}/expire`,new URLSearchParams());}next='expired';}
 else if(session.status==='expired')next='awaiting_payment';
 if(!next)return;const notices=['confirmed','expired'].includes(next)?await noticeStatements('booking',id,next==='confirmed'?'confirmed':'expired',b.version,{payment_status:next==='confirmed'?'paid':'awaiting'},"status='"+next+"'"):[];await db.batch([db.prepare("UPDATE bookings SET status=? WHERE id=? AND status IN ('pending','awaiting_payment') AND version=? AND stripe_session=?").bind(next,id,b.version,b.stripe_session),next==='confirmed'?db.prepare("UPDATE booking_slots SET status='booked' WHERE booking_id=? AND EXISTS(SELECT 1 FROM bookings WHERE id=? AND status='confirmed')").bind(id,id):next==='expired'?db.prepare("UPDATE booking_slots SET status='available',booking_id=NULL WHERE booking_id=? AND EXISTS(SELECT 1 FROM bookings WHERE id=? AND status='expired')").bind(id,id):db.prepare('SELECT 1'),...notices]);await dispatchAppointmentNotices();
}
export async function reconcileExpiredBookings(){if(!paymentConfig().ready)return;const rows=await bookingDb().prepare("SELECT b.id FROM bookings b JOIN booking_slots s ON s.id=b.slot_id WHERE b.status IN ('pending','awaiting_payment') AND b.stripe_session IS NOT NULL AND (b.created_at < ? OR s.starts_at <= ?) ORDER BY s.starts_at LIMIT 20").bind(new Date(Date.now()-31*60000).toISOString(),new Date(Date.now()+3600000).toISOString()).all<{id:string}>();await Promise.allSettled(rows.results.map(r=>reconcileBooking(r.id)));}
