"use client";
import DailyConsultations from '@/components/management/daily-consultations';
import { useState,useEffect,useRef } from 'react';
import { consultationDate,consultationTime,consultationDay,type ConsultationSlot,type Consultation } from '@/lib/consultations';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
export default function Manager(){
 const [clock,setClock]=useState(()=>Date.now());
 const [slots,setSlots]=useState<ConsultationSlot[]>([]),[appointments,setAppointments]=useState<Consultation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[day,setDay]=useState(''),[cancel,setCancel]=useState<Consultation|null>(null),[truncated,setTruncated]=useState(false);
 const batch=useRef<string|null>(null),batchBody=useRef<string|null>(null),[uncertain,setUncertain]=useState(false);
 async function load(){try{const r=await fetch('/api/gestione/incontri',{cache:'no-store'}),d=await r.json() as {slots:ConsultationSlot[];appointments:Consultation[];truncated:boolean;error?:string};if(!r.ok)throw Error(d.error);setClock(Date.now());setSlots(d.slots);setAppointments(d.appointments);setTruncated(d.truncated);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void Promise.resolve().then(load);},[]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);batch.current??=crypto.randomUUID();batchBody.current??=JSON.stringify({id:batch.current,date:form.get('date'),from:form.get('from'),to:form.get('to'),mode:form.get('mode')});setBusy(true);setUncertain(true);setError('');setSuccess('');try{const r=await fetch('/api/gestione/incontri',{method:'POST',headers:{'Content-Type':'application/json'},body:batchBody.current}),d=await r.json() as {created:number;count:number;error?:string};if(!r.ok){if(r.status===400||r.status===403){setUncertain(false);batch.current=null;batchBody.current=null;}throw Error(d.error);}setSuccess(`${d.created} nuovi orari aggiunti. Gli orari già presenti sono conservati; quelli occupati da lezioni o blocchi non sono prenotabili.`);batch.current=null;batchBody.current=null;setUncertain(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function change(id:string,action:string,version?:number){setBusy(true);setError('');try{const r=await fetch('/api/gestione/incontri',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,version})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setSuccess(action==='cancel'?'Incontro cancellato. Avvisa personalmente il partecipante; non viene inviata un’email.':'Disponibilità aggiornata.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);setCancel(null);}}
 const days=[...new Set(slots.map(s=>consultationDay(s.starts_at)))],active=days.includes(day)?day:days[0];
 return <><p className="context-action"><a href="/incontro">Vedi il calendario sul sito pubblico</a></p><DailyConsultations onSaved={load}/><p>Apri soltanto gli orari che puoi confermare subito, in presenza oppure online. Ogni incontro dura 15 minuti, con 5 minuti prima dell’appuntamento successivo.</p>{error&&<p className="error" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 <section className="consultation-admin-editor"><h2>Aggiungi disponibilità</h2><p>Una fascia di un’ora contiene tre incontri. Prenotazioni con almeno 24 ore di anticipo, entro un anno. Questa fascia singola si aggiunge alla disponibilità giornaliera eventualmente attiva.</p><p className="form-note">Apri gli incontri in presenza soltanto per le date in cui la sede sarà pronta.</p><form onSubmit={create}><fieldset disabled={busy||uncertain} className="consultation-fields"><div className="form-grid"><label>Data<input name="date" type="date" min={consultationDay(new Date(clock).toISOString())} required/></label><label>Modalità<select name="mode"><option value="Online">Online</option><option value="Lodi">In presenza a Lodi</option><option value="Entrambe">Online o in presenza, a scelta</option></select></label><label>Dalle (Roma)<input name="from" type="time" defaultValue="16:00" required/></label><label>Alle (Roma)<input name="to" type="time" defaultValue="17:00" required/></label></div></fieldset><button className="button dark" disabled={busy}>{busy?'Salvataggio…':uncertain?'Verifica e riprova gli stessi orari':'Aggiungi gli orari'}</button>{uncertain&&!busy&&<p>Conferma non ricevuta: riprova con gli stessi dati, senza duplicare gli orari.</p>}</form></section>
 {loading?<p role="status">Caricamento…</p>:<><section className="admin-bookings"><h2>Incontri prenotati</h2><p>La prenotazione è già confermata. Qui trovi i recapiti per comunicare il collegamento online o concordare eventuali cambiamenti.</p>{!appointments.length?<p>Nessun incontro prenotato.</p>:appointments.map(a=><article key={a.id} className="admin-booking"><div><span className="booking-badge">{a.status==='confirmed'?'Confermato · gratuito':'Cancellato'}</span><h3>{a.name} · {a.subject}</h3><p>{consultationDate(a.starts_at)} · {consultationTime(a.starts_at)}–{consultationTime(a.ends_at)} · {a.mode==='Lodi'?'In presenza a Lodi':'Online'}</p><p>{a.email}{a.phone?' · '+a.phone:''} · {a.student_type}</p>{a.message&&<p className="learning-copy">{a.message}</p>}<a className="text-link" href={`/gestione?richiesta=${a.request_id}`}>Apri richiesta e anagrafica</a>{a.status==='confirmed'&&Date.parse(a.starts_at)>clock&&<button className="button outline" disabled={busy} onClick={()=>setCancel(a)}>Cancella incontro</button>}</div></article>)}</section>
 <section className="admin-slots"><h2>Orari aperti</h2>{days.length?<><label>Giorno<select value={active} onChange={e=>setDay(e.target.value)}>{days.map(d=><option key={d} value={d}>{consultationDate(slots.find(s=>consultationDay(s.starts_at)===d)!.starts_at)}</option>)}</select></label><div className="admin-slot-grid">{slots.filter(s=>consultationDay(s.starts_at)===active).map(s=>{const booked=appointments.some(a=>a.slot_id===s.id&&a.status==='confirmed');return <article key={s.id}><b>{consultationTime(s.starts_at)}–{consultationTime(s.ends_at)}</b><p>{s.mode==='Lodi'?'In presenza a Lodi':s.mode==='Entrambe'?'Online o in presenza':'Online'}</p><p>{booked?'Incontro prenotato':s.status==='blocked'?'Bloccato':s.occupied?'Occupato da un altro appuntamento o blocco':'Disponibile'}</p>{!booked&&<button className="button outline" disabled={busy} onClick={()=>change(s.id,s.status==='blocked'?'unblock':'block')}>{s.status==='blocked'?'Rendi disponibile':'Blocca orario'}</button>}</article>;})}</div></>:<p>Non hai ancora aperto orari futuri.</p>}</section>{truncated&&<p>Mostriamo fino a 1500 orari futuri e gli ultimi 200 incontri.</p>}</>}
 <AlertDialog open={!!cancel} onOpenChange={open=>{if(!open&&!busy)setCancel(null);}}><AlertDialogContent className="ff-confirm-dialog"><AlertDialogHeader><AlertDialogTitle>Cancellare l’incontro?</AlertDialogTitle><AlertDialogDescription>{cancel?.name} · {cancel&&consultationDate(cancel.starts_at)} · {cancel&&consultationTime(cancel.starts_at)}. L’orario tornerà prenotabile se è ancora disponibile. Avvisa personalmente il partecipante.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="button outline" disabled={busy}>Mantieni incontro</AlertDialogCancel><AlertDialogAction className="button dark" disabled={busy} onClick={e=>{e.preventDefault();if(cancel)void change(cancel.id,'cancel',cancel.version);}}>Cancella incontro</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
