'use client';
import {useEffect,useState} from 'react';
const groups=[['Studenti e gruppi',['students','student_groups','group_members']],['Richieste e attività',['requests','request_followups']],['Agenda e disponibilità',['scheduled_lessons','bookings','booking_slots','consultations','consultation_slots']],['Corsi e studio',['courses','course_modules','course_materials','course_enrollments','material_progress','study_plans','lesson_summaries','homework_assignments','homework_submissions']],['Pagamenti e pacchetti',['lesson_payments','lesson_packages','package_uses']],['Inviti e abbinamenti',['referral_codes','referrals','referral_qualifications','referral_credits','referral_redemptions','matching_proposals']],['Account, modelli e registro notifiche',['accounts','account_student_access','tutor_templates','notifications']]] as const;
export default function ExportData(){
 const [counts,setCounts]=useState<Record<string,number>|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setCounts(null);setError('');fetch('/api/gestione/esportazione',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as {error?:string;counts:{name:string;count:number}[]};if(!r.ok)throw Error(d.error||'Dati non disponibili.');return d;}).then(d=>{if(!c.signal.aborted)setCounts(Object.fromEntries(d.counts.map((row:{name:string;count:number})=>[row.name,row.count])));}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[revision]);
 async function download(){setBusy(true);setError('');setNotice('');try{
  const r=await fetch('/api/gestione/esportazione',{method:'POST',cache:'no-store'});if(!r.ok){const d=await r.json() as {error?:string;counts:{name:string;count:number}[]};throw Error(d.error||'Copia non preparata.');}
  const blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='francesco-fracchia-dati-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  setNotice('Download avviato. Conserva il file in un posto sicuro: contiene dati personali degli studenti.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="learning-card export-panel"><p>Scarica una copia delle richieste, dell’agenda e dei dati degli studenti, con corsi, compiti, correzioni, pacchetti e inviti. Sono comprese anche le bozze e le schede archiviate.</p><p>Il file contiene dati personali e note riservate. Puoi scaricarlo solo dalla gestione.</p><div className="export-totals" aria-live="polite">{counts?groups.map(([label,tables])=><div key={label}><strong>{label}</strong><span>{tables.reduce((n,t)=>n+(counts[t]||0),0)} record</span></div>):<p>{error?'Conteggio non disponibile.':'Caricamento…'}</p>}</div><div className="export-actions"><button className="button dark" onClick={()=>void download()} disabled={busy||!counts}>{busy?'Preparazione…':'Scarica copia dati (JSON)'}</button><button className="button outline" onClick={()=>setRevision(n=>n+1)} disabled={busy}>Aggiorna conteggio</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<h2>Cosa resta fuori</h2><p>Password, sessioni e link riservati di pagamento non vengono esportati. Del registro notifiche sono inclusi i destinatari, gli oggetti e gli stati, senza il testo dei messaggi.</p><p>Gli allegati e i video restano nella piattaforma: nel file trovi il loro elenco, con nome e riferimento. Per conservarne una copia devi scaricarli dalle pagine dei materiali e dei compiti.</p><p>Questa copia permette di consultare i dati fuori dalla piattaforma. Per ripristinare tutta l’app servono anche il backup del database e dei file. Il ripristino automatico e i backup programmati non sono ancora disponibili.</p></section>;
}
