import { z } from 'zod';
import { bookingDb } from '@/lib/booking/runtime';
import { isRequestOwner } from '@/lib/request-admin';
import { failure,LearningError,privateHeaders,sameOrigin } from '@/lib/learning/access';
import { serveMaterialFile } from '@/lib/learning/files';
import { discardUnusedFile,homeworkFile,putHomeworkFile,readHomeworkForm } from '@/lib/homework/files';
export async function GET(request:Request){try{if(!await isRequestOwner())throw new LearningError('Accesso riservato al tutor.',403);const p=new URL(request.url).searchParams,id=z.string().uuid().safeParse(p.get('id')),kind=p.get('kind');if(!id.success||!['task','submission'].includes(kind||''))throw new LearningError('File non valido.');const file=await bookingDb().prepare(`SELECT object_key,filename,mime,'file' kind FROM ${kind==='task'?'homework_assignments':'homework_submissions'} WHERE id=?`).bind(id.data).first<{object_key:string|null;filename:string|null;mime:string|null;kind:string}>();if(!file)throw new LearningError('File non disponibile.',404);return await serveMaterialFile(request,file);}catch(e){return failure(e);}}
export async function PUT(request:Request){let key:string|null=null;try{
 if(!await isRequestOwner())throw new LearningError('Accesso riservato al tutor.',403);sameOrigin(request);const f=await readHomeworkForm(request),p=z.object({id:z.string().uuid(),version:z.string().regex(/^\d+$/).transform(Number).refine(Number.isSafeInteger)}).safeParse({id:f.get('id'),version:f.get('version')});if(!p.success)throw new LearningError('Compito non valido.');const db=bookingDb();const task=await db.prepare('SELECT object_key FROM homework_assignments WHERE id=? AND version=?').bind(p.data.id,p.data.version).first<{object_key:string|null}>();if(!task)throw new LearningError('Compito aggiornato: riaprilo prima di caricare il file.',409);const file=await homeworkFile(f.get('file'));if(!file)throw new LearningError('Scegli un file.');key=`homework/tasks/${p.data.id}/${crypto.randomUUID()}`;await putHomeworkFile(key,file);
 const result=await db.prepare(`UPDATE homework_assignments SET object_key=?,filename=?,mime=?,size=?,status='draft',version=version+1,updated_at=? WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM students WHERE id=homework_assignments.student_id AND status='active') AND NOT EXISTS(SELECT 1 FROM homework_submissions WHERE assignment_id=homework_assignments.id)`).bind(key,file.filename,file.mime,file.size,new Date().toISOString(),p.data.id,p.data.version).run();if(!result.meta.changes)throw new LearningError('Compito aggiornato o già consegnato. Il file non è stato sostituito.',409);await discardUnusedFile(task.object_key);return Response.json({ok:true,id:p.data.id,status:'draft'},{headers:privateHeaders});
 }catch(e){await discardUnusedFile(key);return failure(e);}}
