import {publicPageMetadata} from '@/lib/site-seo';
import {MessagesSquare} from 'lucide-react';
import WhatsAppIcon from '@/components/site/whatsapp-icon';
export function generateMetadata(){return publicPageMetadata('/francesco');}
export default function Page(){return <main className="wrap subject-page profile-page">
 <section className="subject-intro profile-intro"><img className="profile-portrait" src="/images/francesco-fracchia.jpg" alt="Francesco Fracchia" width={1179} height={1497}/><div><h1>Ciao, sono Francesco.</h1><p>Sono laureato in Informatica e frequento la magistrale. Prima ho studiato Informatica e Telecomunicazioni al Volta di Lodi. Ho anche una certificazione di inglese B2.</p></div></section>
 <section className="reading-split profile-story"><div><h2>Le lezioni private</h2></div><div><p>Da diversi anni seguo studenti delle superiori e dell’università in matematica e informatica. C’è chi deve recuperare le basi, chi prepara una verifica e chi un esame. Partiamo dal programma e dal tempo disponibile per scegliere cosa affrontare prima.</p><a className="text-link" href="/metodo">Come lavoro a lezione</a></div></section>
 <section className="reading-split"><div><span className="public-icon-badge"><MessagesSquare aria-hidden="true"/></span><h2>Il rapporto con gli studenti</h2></div><div><p>Essendo ancora studente, conosco le preoccupazioni prima di un esame e la frustrazione quando un argomento non torna. Cerco di mettere i ragazzi a proprio agio. Puoi fare domande o chiedermi di rispiegare, anche se abbiamo già visto quel passaggio.</p></div></section>
 <section className="reading-split"><div><h2>L’esperienza con ragazzi con DSA</h2></div><div><p>Ho seguito molti ragazzi con DSA. Partiamo dalle abitudini di studio e dagli strumenti usati a scuola, concordando schemi, tempi ed eventuale lavoro a casa. Sui passaggi più difficili ci fermiamo quanto serve.</p></div></section>
 <section className="conversation-panel"><h2>Scrivimi</h2><p>Dimmi la materia, la classe o l’esame da preparare. Puoi contattarmi anche per tuo figlio.</p><div className="actions"><a className="button dark" href="https://wa.me/393500316324" target="_blank" rel="noopener noreferrer"><WhatsAppIcon/>Scrivimi su WhatsApp</a><a className="button outline" href="/incontro">Incontro gratuito</a></div></section>
 </main>;}
